clients/vscode/src/TabbyClient.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/webpack.config.js, tabby/server/models.py
Use [language identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers) as language field in completion request.
=> VSCode extension: add language field in completion request.

clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/yarn.lock
* Improve UI of suggestion delay configuration, now providing a set of choices. 
A customized value is also available, you can input a string like "1.5s" or "500ms". 
And add validation to prevent a minus value. 
* Add validation of server URL.
=> Improve VSCode extension configuration and validation.

clients/vim/.gitignore, clients/vim/README.md, clients/vim/autoload/tabby.vim, clients/vim/doc/tabby.txt, clients/vim/plugin/tabby.vim
* Add help document. Use `:help Tabby` or `:Tabby help [subject]` to search help document. 
* Add command line completion.
* Move `suggestion_delay` to `g:tabby_suggestion_delay`
=> VIM plugin: Improve commands, and help document.

clients/vscode/package.json, clients/vscode/src/CompletionCache.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/yarn.lock
#127 
Add a LRU cache to save recently completions. 
* When a completion returned from server and will show up, add it to cache.
* If prompt text range remains unchanged, and inputed characters after prompt text range are matched with any choice of a cached completion, use cached completion instead of making new request.
=> VSCode extensions: add completion cache.

clients/vscode/src/CompletionCache.ts
Small fix changing `>`  to `>=` to fix the bug that when making `add()` to an already full cache, the `evict()` and then `prepend()` would make the cache size to be `capacity+1`.
Also some small renaming for better readability.
Technically the evicting while loop should be fenced with `capacity != 0`. Now that it is hardcoded as a static value, it's fine so far. In the future when we decide to make it configurable, we need to add the fence in `add()`.
Also, would prefer classic LRU implementation with a hashmap together with a linked list. The current implementation's matching is a full O(n) complexity, and so is `refresh()`. Would be a nice-to-have to reduce the complexity with a custom hash function for `documentId`, `text` and `cursor`. Could leave it as a TODO.
=> small fix for completion cache

clients/vim/autoload/tabby.vim, clients/vim/autoload/tabby/virtual_text.vim
=> fix: vim plugin inline completion display error if starts with newline.

clients/vim/autoload/tabby.vim
=> fix(vim): text inserted position error when completion ends with empty line.

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/src/serve/health.rs
Tested locally with Postman:
```
{
"model": "/data/models/TabbyML/T5P-220M",
"device": "cpu",
"compute_type": "auto",
"arch": "x86_64",
"cpu_info": "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz",
"cpu_count": 8
}
```
=> feat: add architecture/cpu info to health api response [TAB-162]

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/build.rs, crates/tabby/src/serve/health.rs
Example:
```json
{
"model": "TabbyML/SantaCoder-1B",
"device": "cpu",
"compute_type": "auto",
"arch": "aarch64",
"cpu_info": "Apple M2 Max",
"cpu_count": 12,
"version": {
"build_date": "2023-08-20",
"build_timestamp": "2023-08-20T15:11:31.236276000Z",
"git_sha": "84c1673c6701aeb6d5779b04a29d891b74e417a6",
"git_describe": "84c1673c6"
}
}
```
=> feat: add version information in health state.

crates/tabby/src/serve/completions/prompt.rs
All tests passed.
`prompt rewrite` disabled
valid `prompt template` | no `prompt template`
some text `prefix` | empty `prefix`
some text `suffix` | none `suffix` | empty `suffix`
=> test: unit tests to prompt builder [TAB-180]

crates/tabby/src/serve/completions/prompt.rs
Add comment signs to extended languages, so that prompt rewrite could be used on these languages
=> feat: add single line comment to languages so they can be used in prompting [TAB-181]

crates/tabby/src/serve/completions/prompt.rs
1. Add unit testing to `PromptBuilder::build_prefix()` so that prompt rewriting could be fenced in a readable fashion.
2. Add unit testing to `PromptBuilder::build_prefix()` to guarantee the snippet count-and-select strategy works as expected. With doing this, also debug and remove a redundant counting line of code.
=> test: add build prefix test and debug chars counting [TAB-184]

crates/tabby/src/serve/completions/prompt.rs
1. Make readable snippets closer to real case.
2. Make snippets vector sum more than `MAX_SNIPPET_CHARS_IN_PROMPT` chars
=> test: use function call style snippet for prompt builder unit test

crates/llama-cpp-bindings/include/engine.h, crates/llama-cpp-bindings/src/engine.cc, crates/llama-cpp-bindings/src/lib.rs
Chip: Apple M2 Max
Memory: 96 GB
All tests all done with `TabbyML/CodeLlama-7B`
Request
```
curl -X 'POST' \
'http://localhost:8080/v1/completions' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"language": "python",
"segments": {
"prefix": "def fib(n):\n    ",
"suffix": "\n        return fib(n - 1) + fib(n - 2)"
}
}'
```
```
llama_print_timings:        load time = 18446.19 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per token,      inf tokens per second)
llama_print_timings: prompt eval time =   450.79 ms /    29 tokens (   15.54 ms per token,    64.33 tokens per second)
llama_print_timings:        eval time =  2345.53 ms /    29 runs   (   80.88 ms per token,    12.36 tokens per second)
llama_print_timings: …
```
=> feat: tune llama metal backend performance

clients/intellij/package.json, clients/vim/package.json, clients/vscode/package.json
Fix `error Couldn't find package "tabby-agent@0.0.1" required by "vscode-tabby@0.3.0" on the "npm" registry.` issue due to tabby-agent version #389 update.
```shell
$ yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
error Couldn't find package "tabby-agent@0.0.1" required by "vscode-tabby@0.3.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "tabby-agent@0.0.1" required by "vim-tabby@0.0.1" on the "npm" registry.
at MessageError.ExtendableBuiltin (/Users/guoxudong/.asdf/installs/yarn/1.22.10/lib/cli.js:721:66)
at new MessageError (/Users/guoxudong/.asdf/installs/yarn/1.22.10/lib/cli.js:750:123)
at PackageRequest.<anonymous> …
```
=> fix: 🐛 Couldn't find package "tabby-agent@0.0.1"

experimental/prompt-rewrite-eval/README.md, experimental/prompt-rewrite-eval/dashboard.py, experimental/prompt-rewrite-eval/eval.toml, experimental/prompt-rewrite-eval/evaluator.py, experimental/prompt-rewrite-eval/requirements.txt
```
pip install -r requirements.txt
```
1. tweak `eval.toml`
- tabby binary path
- index repo url (the repo you want tabby to index from)
- sample repo url (the repo you want to generate completion requests from)
- language
- prompt count
2. run `python evaluation.py`
```
streamlit run dashboard.py
```
- Tweak the slider bar to change how many recent prompts you want to review.
- Change the language to filter only the specific language you are interested in.
=> feat: prompt rewrite eval tool

clients/vscode/src/TabbyCompletionProvider.ts
=> fix(vscode): do not show inline completion when autocomplete widget is visible.

crates/http-api-bindings/src/fastchat.rs, crates/http-api-bindings/src/lib.rs, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/mod.rs
* feat: add support fastchat http bindings
=> feat: add support fastchat http bindings

crates/tabby/src/serve/mod.rs
```
servers(
(url = "https://playground.app.tabbyml.com", description = "Playground server"),
(url = "http://localhost:8080", description = "Local server"),
),
```
The default is to use port 8080, but serve can customize the port through --port, resulting in request errors
=> fix(tabby): fix swagger's local server use local port

crates/tabby-common/src/config.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/src/serve/mod.rs
Before the Tabby service, if there is nginx's reverse proxy service, users can access Tabby's services through domain names. Currently, swagger only has https://playground.app.tabbyml.com and local service options, and cannot perform service completion through domain names.
current server：
add proxy server
=> feat: proxy server address mapping to the model server

README.md
Hi Guys,
I faced an issue while trying to clone code and compile it on my Mac. I realized that I had forgotten to include the recurse-submodules option during the initial cloning process. As a result, I received an error message indicating that the `llma.cpp` directory was empty.
To improve the process and help others avoid this issue, it might be beneficial to add an additional step, advising users to clone submodules using the following command:
```
git submodule update --recursive --init
```
This will ensure that all necessary submodules are fetched and initialized, preventing similar problems in the future.
If you have any further suggestions or need additional assistance, please feel free to let me know.
=> docs: add alternative submodule fetching to contributing guide

clients/intellij/package.json, clients/tabby-agent/package.json, clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/vim/package.json, clients/vscode/README.md, clients/vscode/assets/walkthroughs/codeCompletion.md, clients/vscode/package.json, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/commands.ts, clients/vscode/src/extension.ts
Fix TAB-19 
Fix TAB-133
Fix #103 
As mentioned in issue #103, the Tabby extension returns a list of choices (InlineCompletionItems) to the vscode completion engine for each call. Without registering a callback using the [proposed VSCode API](https://github.com/microsoft/vscode/blob/e3da120e0808f36e45e6783b611cc943d7fdd61c/src/vscode-dts/vscode.proposed.inlineCompletionsAdditions.d.ts#L20), it is uncertain which choice is currently being viewed.
The Tabby server api schema allows generating multiple choices at once, but the Tabby server only generates one choice per request. In this PR, the extension is modified to return only one choice to the vscode completion engine, assuming that this choice is viewed immediately. The extension send the `view` event before return each choice, as a …
=> fix(vscode): completion view/select event.

clients/intellij/package.json, clients/tabby-agent/package.json, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/CompletionProviderStats.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/vim/package.json, clients/vscode/CHANGELOG.md, clients/vscode/package.json
Fixes:
- Filtered out `AgentStats` events with no data.
- Removed debouncing and timeout config data in AgentStats events.
- Fixed the issue where `stats.completion_request_canceled.latency_avg` was displayed as null when not available. It has now been set to `undefined` and will no longer be displayed when not available.
- Fixed a bug that could cause incorrect user properties value when user settings `inlineCompletion.triggerMode` and `keybindings` were updated.
=> fix(agent): hotfix vscode extension 0.6.1. Filter out no data AgentStats event.

Dockerfile
to avoid dubious ownership warning for git.
#569
=> fix: set safe.directory in Dockerfile

Cargo.lock, crates/ctranslate2-bindings/Cargo.toml, crates/ctranslate2-bindings/build.rs
The current building flow will fail on Jetson, because the CTranslate2 binding turns the "sse4.1" flag on while it's not available on Jetson.
I've added a function to check whether it's building on the NVIDIA Jetson device or not. If true, it will turn on CUDA and CUDNN flags of CTranslate2.
I've tested building on Intel CPU, AMD CPU, Jetson Orin Nano, Jetson Orin AGX.
=> chore: add support for building on jetson device

clients/vim/autoload/tabby.vim
I've found this when wondering why I'm not getting any completion and status was saying "Tabby is initializing"
=> Don't get stuck in 'initializing' when script not found

CHANGELOG.md, crates/llama-cpp-bindings/src/engine.cc, crates/tabby-common/src/path.rs, crates/tabby-download/src/lib.rs, crates/tabby/src/serve/engine.rs
this change will merge once we've updated gguf files for all models in https://tabby.tabbyml.com/docs/models/
fix TAB-281
=> feat: upgrade llama.cpp

crates/llama-cpp-bindings/include/engine.h, crates/llama-cpp-bindings/src/engine.cc, crates/llama-cpp-bindings/src/lib.rs, crates/tabby/src/download.rs, crates/tabby/src/serve/engine.rs
On Modal T4 (`k6 tests/*.loadtest.js`), StarCoder-1B
0.4.0 (ctranslate2)
```
✗ success
↳  95% — ✓ 60 / ✗ 3
checks.........................: 95.23% ✓ 60       ✗ 3
data_received..................: 63 kB  2.1 kB/s
data_sent......................: 16 kB  506 B/s
http_req_blocked...............: avg=24.06ms  min=0s      med=1µs     max=322.84ms p(90)=169.29ms p(95)=170.47ms
http_req_connecting............: avg=10.3ms   min=0s      med=0s      max=83.21ms  p(90)=80.51ms  p(95)=81ms
✗ http_req_duration..............: avg=2.87s    min=964.2ms med=3.1s    max=4.18s    p(90)=3.73s    p(95)=4.04s
{ expected_response:true }...: avg=2.82s    min=964.2ms med=3.05s   max=4.18s    p(90)=3.42s    p(95)=3.9s
✗ http_req_failed................: 4.76%  ✓ 3        ✗ 60
http_req_receiving.............: …
```
=> feat: support continuous batching in llama.cpp backend

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts
Complete TAB-268
Add this config to enable experimental feature:
```
[completion.prompt]
stripAutoClosingCharacters = true
```
Example:
For this case:
```js
function fib(n) {║}
```
off(default):
```
// prompt
{
prefix: "function fib(n) {",
suffix: "}\n",
}
```
on:
```
// prompt
{
prefix: "function fib(n) {",
suffix: "\n",
}
```
=> feat(agent): add experimental option: strip auto-closing chars in prompt suffix.

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.test.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.ts
Complete TAB-268
Add this config to enable experimental feature:
```
[postprocess.limitScopeByIndentation]
keepBlockScopeWhenCompletingLine = true
```
When completion is continuing the current line, limit the scope to:
- false(default): the line scope, meaning use the next indent level as the limit.
- true: the block scope, meaning use the current indent level as the limit.
Example:
off:
on:
=> feat(agent): add experimental option: scope of indentation filter.

clients/intellij/package.json, clients/tabby-agent/package.json, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/Auth.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts, clients/vim/package.json, clients/vscode/package.json, yarn.lock
Complete: TAB-235
* Added `token` in `server` section, updated config template:
```toml
``` 
* Fix datastore to watch file changes
=> feat(agent): add auth token config.

CHANGELOG.md, crates/tabby-common/src/index.rs, crates/tabby-scheduler/src/index.rs
Example query:
```
name:get_l AND kind:function
```
```json
{
"num_hits": 2,
"hits": [
{
"score": 18.802094,
"doc": {
"body": "fn get_language(ext: &OsStr) -> Option<&str> {\n    let ext = ext.to_str().unwrap_or(\"\");\n    EXTENSION_LANGUAGE.get(ext).copied()\n}",
"filepath": "crates/tabby-scheduler/src/dataset.rs",
"git_url": "https://github.com/TabbyML/tabby",
"kind": "function",
"language": "rust",
"name": "get_language"
},
"id": 1961
},
{
"score": 18.802094,
"doc": {
"body": "pub fn get_language(language: &str) -> &'static Language {\n    CONFIG\n        .config\n        .iter()\n        .find(|c| c.languages.iter().any(|x| x == language))\n        .unwrap_or(&UNKNOWN_LANGUAGE)\n}",
"filepath": "crates/tabby-common/src/languages.rs",
"git_url": "https://github.com/TabbyML/tabby", …
```
=> feat: support prefix query on name field

crates/llama-cpp-bindings/src/lib.rs, crates/llama-cpp-bindings/src/llama.rs, crates/tabby/src/serve/engine.rs
In background job thread, we first lock `requests`, then lock `engine`, while in generate_stream thread, we first lock `engine`, then lock `requests`.
This creates a classic deadlock.
Fix #718
=> fix: deadlock between background job and requests

crates/llama-cpp-bindings/src/engine.cc
i think we don't need to use `llama_set_n_threads` method. it's likely used for runtime modifications. we only need to set ctx_params
fixes #738
=> feat: add LLAMA_CPP_N_THREADS env

crates/tabby-scheduler/src/index.rs
https://github.com/quickwit-oss/tantivy/issues/2156
related #752
=> fix: tantivy requires more memory for indexing in new version.

crates/tabby/Cargo.toml, crates/tabby/src/serve/engine.rs, crates/tabby/src/serve/mod.rs
This PR is for closing https://github.com/TabbyML/tabby/issues/735
-  Add `experimental-http` feature in `Cargo.toml`
- Make dependency `http-api-bindings` as `optional`
- Update `create_engine` method, only when `experimental-http is enabled` **AND** `tabby serve --device experimental-http`, call `http_api_bindings::create`, other cases go to normal flow
- Update `main` method, only when `experimental-http is enabled` **AND** `tabby serve --device experimental-http`, just log message without loading model, other cases load model normally.
=> refactor: add experimental-http feature

Cargo.lock, crates/tabby-common/src/path.rs, crates/tabby/src/worker.rs, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/api.rs, ee/tabby-webserver/src/db.rs, ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/schema.rs, ee/tabby-webserver/src/server.rs
For closing https://github.com/TabbyML/tabby/issues/786
- Add `token` argument in `WorkerArgs` struct
- Add db schema
- Update `Hub::register_worker` to pass `token` from worker side. In `HubImpl`, do token validation
- Update `ServerContext` struct, add db connection, add 2 public methods to query/update token which persisted in `sqlite` db
- Update graphql, add `Mutation` to support refresh token on server side
=> feat: validate token during worker registration

crates/tabby/src/services/model.rs, ee/tabby-webserver/src/db.rs
- Move db file from `~/.tabby/db.sqlite3` to `~/.tabby/ee/db.sqlite`
- Fix compile error when `experimental-http` feature is enabled
=> fix: move db to `ee` directory

clients/vscode/package.json, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/TabbyStatusBarItem.ts, clients/vscode/src/commands.ts, clients/vscode/src/extension.ts, clients/vscode/src/notifications.ts
Complete TAB-325
Changes:
* Update notification messages, add "Don't show again" for completion response time issues warnings:
* Add online help links
=> feat(vscode): Add dont-show-again for warnings.  Add online help links.

CHANGELOG.md, Cargo.lock, Makefile, crates/tabby/Cargo.toml, crates/tabby/src/routes/metrics.rs, crates/tabby/src/routes/mod.rs, crates/tabby/src/serve.rs, crates/tabby/src/worker.rs
1) Added `axum-prometheus` to Cargo.toml
2) Added `metrics.rs` as a simple route to produce a metrics endpoint with prometheus-formatted events
3) Added `/v1/metrics` endpoint with API doc entry
4) Added the `PrometheusLayer` to the root layers.
This change effectively allows for external Prometheus to scrape metrics from Tabby during execution in order to monitor operations (resources, timings and overall usage).
Metrics can be viewed from the API docs and by calling `/v1/metrics` on a running instance.
=> feat: add Prometheus support to Tabby.

clients/vscode/CHANGELOG.md, clients/vscode/package.json, clients/vscode/src/TabbyStatusBarItem.ts
FIX TAB-350
- Fixed a bug that caused the disconnected notification to show up every time when VSCode is started. Now, the notification will only appear after the user modifies the server endpoint settings and the connection fails.
=> fix(vscode): Hotfix 1.1.3.  Do not show disconnected notification when initializing

crates/tabby-common/src/usage.rs
I noticed the file `usage_anonymous_id` (containing the anonymous identifier) was written to disk even when tracking has been disabled. This seems unnecessary since it's not used as far as I can tell.
=> fix: Skip creating `usage_anonymous_id` when TABBY_DISABLE_USAGE_COLLECTION is set

Cargo.lock, crates/tabby-common/src/config.rs, crates/tabby-common/src/lib.rs, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/docs/api_spec.md, ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/repositories.rs, ee/tabby-webserver/src/repositories/repo.rs, ee/tabby-webserver/src/repositories/resolve.rs
For closing https://github.com/TabbyML/tabby/issues/815
- Add 2 public APIs
- `resolve` for fetching file or dir info from local repository located at `~/.tabby/repositories/`
- `meta` for fetching dataset info from file `~/.tabby/dataset/files.jsonl`
- Add api spec doc
Please check `ee/tabby-webserver/docs/api_spec.md` for response examples.
=> feat: add api to serve files under repositories

clients/vscode/src/TabbyCompletionProvider.ts
Complete TAB-340
Related #788 
Fix the context for notebooks in VSCode:
* For completion in code cells (python supported currently), the text in markdown cells will be added as comments, as well as if there are any cells in different code language.
* For completion in markdown cells, all code cells will be added as code blocks (```).
=> fix(vscode): get text from other cells of current notebook as prompt.

clients/tabby-agent/src/CompletionContext.ts, clients/tabby-agent/src/postprocess/formatIndentation.test.ts, clients/tabby-agent/src/postprocess/formatIndentation.ts, clients/tabby-agent/src/postprocess/index.ts, clients/vscode/src/TabbyCompletionProvider.ts
Complete TAB-315
This PR try to post-process completion by formatting the indentation.
If there is alreay some indentation in context, the server output should have learned from it, so we just process the case of when:
- there is no indentation in context (including prefix and suffix)  
- and we can get the specified indentation type from current editor  
- and there is any indentation in the completion text, but it is not matched with current editor config  
then we reindent the completion text with the current editor config.  
The indentation dectection in this PR supports for dectecting tab, 2 spaces or 4 spaces.
=> feat(agent): format indentation if not match with editor config.

crates/llama-cpp-bindings/src/engine.cc
According to the information available at https://github.com/ggerganov/llama.cpp/issues/3960, the issue appears to exclusively impact CUDA, aligning with our observations.
Nevertheless, we are implementing a mutex for all backends regardless.
=> fix: avoid llama.cpp's racing

Cargo.lock, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/db.rs, ee/tabby-webserver/src/schema.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/server.rs, ee/tabby-webserver/src/server/auth.rs
For closing https://github.com/TabbyML/tabby/issues/805
- Update GraphQL schema, add 4 mutations, generated schema looks like
```
type Mutation {
register(
email: String!
username: String!
password1: String!
password2: String!
): RegisterResponse!
tokenAuth(
email: String
username: String
password: String!
): TokenAuthResponse!
verifyToken(token: String!): VerifyTokenResponse!
}
```
The `refreshToken` implementation has not been finalized, so I do plan to raise separate PR for it.
- Update mutation `resetRegistrationToken`, only `admin` is allowed to execute it
There are some implementations need to be discussed, **comment inline**.
=> feat(ee): implement user authentication api

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/db.rs
follow up of https://github.com/TabbyML/tabby/pull/912
Add `me` query similar to https://django-graphql-auth.readthedocs.io/en/latest/api/#mequery
=> feat: Add me_query API

crates/llama-cpp-bindings/build.rs
rocminfo reports that my AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics gpu version is gfx1103
=> feat: Add support for 7840U iGPU type

.github/workflows/release.yml, Cargo.lock, ci/prepare_build_environment.ps1, crates/llama-cpp-bindings/build.rs, crates/llama-cpp-bindings/src/engine.cc, crates/tabby-common/Cargo.toml, crates/tabby-common/src/path.rs
For https://github.com/TabbyML/tabby/issues/909
The trial is partially successful, raise PR for further discussion.
See comments inline.
=> feat: support build tabby on windows

crates/tabby/src/routes/mod.rs, crates/tabby/src/serve.rs, crates/tabby/src/worker.rs
* Add --host option to specify the host Tabby server will listen on (default remains 0.0.0.0 if option is not specified)
* Correct small typo in startup message: "Starting server, this might ~takes~ **take** a few minutes..."
=> feat(core): add --host option to specify the host Tabby server will listen on.

Dockerfile
Resolve issue #623 - Linux arm64/v8 support in Dockerfile
=> fix: Resolve issue #623 - Linux arm64/v8 support in Dockerfile

ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/service/cron.rs
When I run webserver locally, I found `Ok(None)` condition is triggered.
I shortern the job run from `2 hours` to `2 minutes`, comment out `return` from `Ok(None)` condition, observed it might be triggered once or twice from time to time.
Originally, I put `return` here because if scheduler has no job added, `time_till_next_job` will always return `Ok(None)`.
But since this condition can be reached even when job exists in scheduler, we shouldn't return directly.
This pr fixes it.
==
Track down `time_till_next_job` a bit, internally job's `next_tick` is compared with current timestamp, if next_tick < now, `Ok(None)` is returned.
Based on the [doc](https://docs.rs/tokio-cron-scheduler/0.9.4/tokio_cron_scheduler/struct.JobScheduler.html#method.start), a tokio task will run tick method every …
=> fix: prevent early return of cron job

crates/tabby/src/services/event.rs
For closing https://github.com/TabbyML/tabby/issues/1036
- remove `std::io`, apply `tokio::io` completely to prevent blocking
- create event log file based on the date when receive the event
- add tests
=> fix: create event file by event timestamp, refactoring code

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/dataset/tags.rs, website/docs/programming-languages.md
Requires:
- https://github.com/tree-sitter/tree-sitter-c/pull/175
- https://github.com/tree-sitter/tree-sitter-cpp/pull/233
=> feat: add stop words / repository context support for C/C++

ee/tabby-webserver/src/path.rs, ee/tabby-webserver/src/service/db/mod.rs
Follow up of https://github.com/TabbyML/tabby/pull/1057
In that PR, we pass the db file path for `create_dir_all` which will cause the exception when run the webserver.
This PR fix it.
=> fix: pass ee root when call create_dir_all

ee/tabby-ui/components/chat-panel.tsx
=> fix(ui): fix gradient in darkmode playground chat box

crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/index.rs
Follow up of PR: https://github.com/TabbyML/tabby/pull/1064
`atty` lacks maintenance, latest version was almost 4 years ago.
Luckily, from rust v1.70.0, std provides `IsTerminal` [trait](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html#tymethod.is_terminal)
Test if stdout refers to an terminal/tty, only display progress bar if it does.
=> feat(scheduler): only display tqdm progress bar in interactive terminal (tty)

ee/tabby-webserver/src/service/cron/job_utils.rs, ee/tabby-webserver/src/service/cron/mod.rs, ee/tabby-webserver/src/service/cron/repository.rs, ee/tabby-webserver/src/service/db/job_runs.rs
Follow up of PR: https://github.com/TabbyML/tabby/pull/1064#discussion_r1431078578
Main changes:
- Add db update for `job_runs` table
- Refactor `repository_job` method
- take `stdout` & `stderr` from child process, create separate tasks to read from them, for each line, save into db
=> feat: support streaming process output into db

clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/vscode/package.json, clients/vscode/src/TabbyStatusBarItem.ts, clients/vscode/src/agent.ts, clients/vscode/src/commands.ts, clients/vscode/src/notifications.ts
Complete TAB-384
- Supported set auth token via VSCode command, should be useful for users connecting to a Tabby server running with `--webserver` option.  
- Token set in IDE have higher priority than in `~/.tabby-client/agent/config.toml`
- **Removed** support for `open auth page` when using Tabby Cloud.
Preview:
=> feat(vscode): support set auth token via vscode command.

website/docs/configuration.md
Hello! I noticed that the configuration docs points to a non-existing file for the health.rs configuration. It was incorrectly 'serve' instead of 'services'
=> docs: Replace dead health.rs link

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/db/job_runs.rs, ee/tabby-webserver/src/service/db/users.rs
For closing issue: https://github.com/TabbyML/tabby/issues/1117
- Add `job_runs` api + service implementation + db query, similar to the `usersNext` & `invitationsNext`
- move `User` object to `auth` mod, together with the other type definitions, then re-export in the `mod.rs`
=> feat: display job run results in page

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/src/routes/chat.rs, crates/tabby/src/services/chat.rs
=> feat: Convert completion chunk API response to OpenAI-compatible event stream

clients/tabby-agent/tsup.config.ts
=> fix(agent): fix tree-shaking file-stream-rotator in building browser scripts.

ee/tabby-webserver/src/repositories/mod.rs
Follow up of issue: https://github.com/TabbyML/tabby/issues/815#issuecomment-1870146269
- ignore `.git` directory from resolve api, return `404` directly
- add fallback handling
=> fix(webserver): ignore .git for /repositories resolve api

clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/postprocess/base.ts, clients/tabby-agent/src/postprocess/calculateReplaceRange.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.test.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeBySyntax.test.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeBySyntax.ts, clients/tabby-agent/src/postprocess/golden/limit_scope/experimental_block_01.toml, clients/tabby-agent/src/postprocess/golden/limit_scope/experimental_block_02.toml, clients/tabby-agent/src/postprocess/golden/replace_range/experimental_syntax_mismatched_01.toml, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/src/postprocess/limitScope.ts, clients/tabby-agent/src/postprocess/limitScopeBySyntax.ts, clients/tabby-agent/src/postprocess/postprocess.test.ts
Changes: 
- Refactor `calculateReplaceRange` as a postprocess filter, will be invoked by `postCacheProcess`.
- Make syntaxBased filter fallback to non-SyntaxBased filter when syntax parser error.
Fix TAB-365
=> refactor(agent): move calcReplaceRange to a postprocess filter.

clients/vscode/src/TabbyCompletionProvider.ts
Follow up #885 
Remove the clipboard reading in every code completion request for now, considering: 
- The clipboard content have not been used as prompt for now.
- In the browser enviroment, reading clipboard causes the browser prompts the user for clipboard permission once user editing a file.
=> fix(vscode): remove the clipboard accessing in getting inline completion.

ee/tabby-db/src/invitations.rs, ee/tabby-webserver/src/oauth/mod.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/service/auth.rs
Follow up of PR: https://github.com/TabbyML/tabby/pull/1160
During oauth login by github
- first, check if user exists, if so, skip password verification, generate access/refresh token for the user
- if user not exist, check if user has been invited, if so, register user with empty password, then generate tokens
- if user not exist & not invited, return `401`
=> feat(webserver): complete `github_auth` method

clients/vim/README.md, clients/vim/autoload/tabby/keybindings.vim
Fix TAB-371
Related to #862
Changes:
- Fix the script error that occurs when attempting to remap `<tab>` with a fallback but the original `rhs` is not found.
- Add a new section `Known Conflicts` to README.md.
- Simplify the `Installation` section, removing instructions on how to use 3rd-party vim plugin managers. This section now only includes sample config file examples for each plugin manager.
=> fix(vim): fix errors caused by <tab> keymapping conflicts.

crates/tabby-common/src/api/event.rs, crates/tabby/src/routes/events.rs
=> feat: Add a new event type:`dismiss`. Add `view_id` and `elapsed` in event body.

ee/tabby-db/migrations/06-github-oauth-credential/up.sql, ee/tabby-db/src/github_oauth_credential.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/dao.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
Removes the active field and determines active status based on whether the credential is present or not
=> feat: Remove 'active' field from OAuth credentials

clients/tabby-agent/README.md, clients/tabby-agent/package.json, clients/tabby-agent/src/LspServer.ts, clients/tabby-agent/src/cli.ts, yarn.lock
Add basic lsp support.
Complete TAB-388
Add command line arg `--lsp` will run agent as a lsp server.
Supported client -> server method:
- initialize
- shutdown
- exit
- textDocument/completion
Used server -> client method:
- window/showMessage
- show warning when disconnected
=> feat(agent): add lsp support to agent.

ee/tabby-db/migrations/09-google-oauth-credential/down.sql, ee/tabby-db/migrations/09-google-oauth-credential/up.sql, ee/tabby-db/src/google_oauth_credential.rs, ee/tabby-db/src/lib.rs, ee/tabby-webserver/src/oauth/github.rs, ee/tabby-webserver/src/oauth/google.rs, ee/tabby-webserver/src/oauth/mod.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/dao.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
For closing issue: https://github.com/TabbyML/tabby/issues/1039
Similar to Github oauth, add following changes
- Add `google_oauth_credential` db table, and read/write operations
- it's slightly different from `github_oauth_credential`, we need to keep `redirect_uri` because it's a `required` parameter when exchange access token (unlike github which is optional)
- Add `google` client, implement token exhange and user email fetching
- Add `/oauth_callback/google` route, extract common response handling logic into `match_auth_result` method
- google oauth is very simliar to github oauth, so refactor `github_auth` method to take care of both providers
- update graphql api to update/return `redirect_uri` field, this field is defined as optional, so should break nothing
=> feat(webserver): Add Google oauth support

crates/tabby-common/src/registry.rs
I've come across a situation where a locally compiled TabbyML failed to download a remote model because the directory `~/.tabby` already existed. 
This PR should remedy that problem and give the user some more feedback.
=> fix(download): Improve error handling for remote registry

clients/intellij/node_scripts/tabby-agent.js, clients/tabby-agent/src/cli.ts, clients/vim/node_scripts/tabby-agent.js
macOS does not have `/bin/env`, so let's point to `/usr/bin/env` like the other instances.
=> fix(agent): Use /usr/bin/env instead of /bin/env

website/docs/programming-languages.md
I assume Kotlin is supported as stated above. The documentation seems outdated.
=> Delete Kotlin from the missing support list in programming-languages.md

ee/tabby-ui/lib/tabby/gql.ts
`urql` wraps the original error
=> fix(ui): display root error in `form` after integrating `urql`

clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/types/tabbyApi.d.ts
Related to #1159
Changes:
- Fixed the error handling of code 405
- Fallback to POST if GET is not allowed when health checking (compatible with older server version)
=> fix(agent): make health checking compatible with older server version only support POST.

crates/juniper-axum/src/relay/connection.rs, crates/juniper-axum/src/relay/mod.rs, ee/tabby-webserver/src/service/auth.rs
Remaining flaw: `has_previous_page` will always be true if `before` or `after` are specified, even if all possible values are returned. This cannot be resolved with the current setup of functions.
=> fix(juniper_axum): Fix how has_previous_page and has_next_page are computed

clients/vscode/CHANGELOG.md, clients/vscode/package.json
=> chore(vscode): bump VSCode Extension version to 1.3.0.

website/docs/extensions/configurations.md, website/docs/extensions/troubleshooting.md
Remove documentation about the client-side timeout limit, as the timeout limit has been removed in clients after version 1.3.0.
=> docs: update online docs for clients config about timeout limit.

Cargo.lock, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/queries/csharp.scm, crates/tabby-scheduler/src/dataset/tags.rs, website/docs/programming-languages.md
This should close #239, I noticed that #1030 had done most of the job but didn't update docs so, I've taken the liberty of doing that. Not sure if this will slip into RC or not but I've made an assumption it will for docs.
**Commits**
- feat(scheduler, docs): Add repo context support for C#, added language to supported list in docs
=> feat(scheduler, docs): Added repository context support for C#

.github/workflows/release.yml, Dockerfile, crates/tabby/Cargo.toml, ee/tabby-db/Cargo.toml, ee/tabby-db/src/path.rs, ee/tabby-webserver/Cargo.toml
Closes #1272 
NOTE: This will immediately present a breaking change for anyone who currently has a prod db and is expecting it to be used on startup. We might want to document this, but if so, which document(s)?
=> feat(db): Split prod and dev db, default to dev

ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/mod.rs
cc @boxbeam , when we migrate ID type to hashids, we missed graphql pagination cursor (which should be convert to ID as well)
=> fix(tabby-ui, webserver): migrate pagination to ID type

website/docs/installation/docker-compose.mdx
=> docs: fix tabby-cpu entrypoint override in docker-compose.mdx

ee/tabby-webserver/src/service/auth.rs
There is currently no way to update `is_admin` for a user, we will have to remember to apply this same check when we get to that.
=> feat(webserver): Prevent disabling owner user

CONTRIBUTING.md
Without it, the standard test suite will fail.
=> docs: mention mailtutan dependency for tests

clients/tabby-agent/openapi/tabby.json, clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/Auth.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts, clients/tabby-agent/src/types/tabbyApi.d.ts, clients/vscode/src/agent.ts
Complete TAB-528
Added support for fetching the server config `disable_client_side_telemetry`:
- When set to true, no tracking data will be sent, regardless of the client-side configuration `anonymousUsageTracking`.
- When set to false, the client-side configuration `anonymousUsageTracking` will be used.
=> feat(agent): support fetching server-provided client-side config.

ee/tabby-webserver/development/Caddyfile
=> fix: fix caddy redirect for api page

clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/Auth.ts, clients/tabby-agent/src/CompletionCache.ts, clients/tabby-agent/src/JsonLineServer.ts, clients/tabby-agent/src/LspServer.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/configFile.ts, clients/tabby-agent/src/loadCaCerts.ts, clients/tabby-agent/src/logger.ts, clients/tabby-agent/src/postprocess/base.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/TabbyStatusBarItem.ts, clients/vscode/src/agent.ts, clients/vscode/src/commands.ts, clients/vscode/src/extension.ts, clients/vscode/src/logger.ts, clients/vscode/src/notifications.ts
Complete TAB-486
Added support for logging to the VSCode output channel.
Preview:
VSCode output log level could be set by `Developer: Set Log Level...` in the command palette.
=> feat(agent&vscode): add support for agent log to vscode output.

clients/vscode/assets/walkthroughs/codeCompletion.md, clients/vscode/package.json
=> fix(vscode): fix keybinding next word (cmd+right) for macOS.

clients/tabby-agent/src/Auth.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts
Fix #1568 
Do not export FileDataStore to a wide scope, so that it can be treeshaked in browser build.
=> fix(agent): Do not export FileDataStore to a wide scope

ee/tabby-ui/app/(dashboard)/cluster/components/cluster.tsx, ee/tabby-ui/app/(dashboard)/page.tsx
=> fix(ui): modify token color

Cargo.lock, crates/tabby-common/src/lib.rs, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset/deps/javascript.rs, crates/tabby-scheduler/src/dataset/deps/mod.rs, crates/tabby-scheduler/testdata/package-lock.json, crates/tabby-scheduler/testdata/package.json
Continuation of #1004 that filters and returns direct project dependencies with resolved versions. Due to differences between lockfile versions I also had to load package.json to correctly identify immediate deps.
Closes #877
=> feat: extract JS deps from package-lock.json

crates/tabby/src/main.rs
Directories without the execute bit set cannot be traversed, oddly
=> fix(tabby): Set directory permissions to 700 instead of 600

CHANGELOG.md, crates/tabby/src/serve.rs
A implementation of issue #1659 
The very simple implementation of the --chat-device flag to override device to use for chat model. This implementation, however, rejects arguments if --chat-device specified without the --chat-model flag. The issue suggests giving a warning instead, but I found out a good `clap` macro to achieve the implemented behaviour. I decided to not implement a logging warning message and give the situation handling to the `clap` crate to keep the code clean.
Tested with rocm + cpu devices. I cannot test other devices myself.
---
closes  #1659
=> feat(tabby): Added --chat-device arg for serve subcommand

ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/lib/tabby/auth.tsx
=> feat(ui): check admin status via service instead of JWT

crates/tabby-scheduler/src/index.rs
Fixes TAB-570, closes https://github.com/TabbyML/tabby/issues/1697
=> fix(scheduler): Log and skip instead of panicking on invalid tag range

.github/workflows/release.yml, CONTRIBUTING.md, crates/llama-cpp-bindings/build.rs, website/docs/installation/windows/index.mdx
I tried compiling the Vulkan feature on Windows, but was running into the vulkan library not being found by the build script. This is the fix. Now I can run tabby on my AMD 5700XT on Windows. It's seems quite fast too!
Changes:
* Remove `=native` in vulkan feature in build.rs so that all library kinds are part of the search. This *shouldn't* break the Linux builds, but if it does CI should catch it.
* Add a CI step to create a Windows Vulkan build automatically. If I'm lucky it'll work first try? 🤞
* User-facing documentation changes to reflect Vulkan support.
=> ci: support Vulkan build on Windows

crates/tabby-common/src/registry.rs, crates/tabby-download/src/lib.rs
Fixes TAB-564, closes https://github.com/TabbyML/tabby/issues/1318
=> feat(download): Add support for segmented model urls

ee/tabby-ui/app/(dashboard)/profile/components/avatar.tsx
Profile page enhancements
* Fix image overlap bug when uploading an avatar
* Adjust avatar upload tip position for alignment
=> fix(ui): avatar uploading ui bugs in profile page

ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-list.tsx, ee/tabby-ui/app/globals.css
=> feat(ui): adjust the dark theme for card and popup

ee/tabby-db/src/user_completions.rs, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/analytic.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/analytic.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver): implement AnalyticService

crates/tabby-common/src/api/event.rs
To fix the error
```rust
error[E0277]: the trait bound `Declaration: Clone` is not satisfied
--> crates/tabby-common/src/api/event.rs:98:5
|
86 | #[derive(Serialize, Deserialize, Debug, Clone)]
|                                         ----- in this derive macro expansion
...
98 |     pub declarations: Option<Vec<Declaration>>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `Declaration`, which is required by `std::option::Option<std::vec::Vec<Declaration>>: Clone`
|
```
=> fix(core): add Clone trait to the Declaration

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx
=> fix(ui): format of accept rate in report page

crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/completion/completion_prompt.rs
TAB-512
Changes:
- Added `recent_snippets` in completion request segments.
- Updated comments using rustdoc links. (But it does not seem to be compiled to openapi doc links)
=> feat(core): added recent snippets in completion request segments.

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx
=> fix(ui): report page title format & language selection order

ee/tabby-ui/app/(home)/page.tsx
=> fix(ui): fix activities display in home page

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/oauth/github.rs, ee/tabby-webserver/src/oauth/google.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/dao.rs
=> refactor: use graphql(skip) to omit field in graphql response

CHANGELOG.md, crates/tabby/src/serve.rs
=> feat(core): turn on --webserver by default

website/docs/installation/modal/index.md, website/docs/installation/skypilot/index.md, website/docs/installation/skypilot/tabby.yaml
To prepare for the default enabling of `--webserver`
=> docs: remove curl test from installation guides

ee/tabby-ui/app/(dashboard)/profile/components/avatar.tsx
Test:
* .png, .jpg, .jpeg are supported to upload, updated and display
* other files are not selectable, e.g.:
=> fix(ui): restrict image type of avatar

clients/vscode/CHANGELOG.md, clients/vscode/package.json
V1.5.2 is a pre-release version.
=> chore(vscode): bump vsce version to 1.5.2.

ee/tabby-webserver/src/juniper/relay/mod.rs, ee/tabby-webserver/src/schema/mod.rs, rules/use-schema-result.yml
=> refactor(webserver): always use schema::Result for graphql api responses

ee/tabby-ui/app/(dashboard)/reports/components/annual-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/daily-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx, ee/tabby-ui/app/(home)/components/stats.tsx
Testing examples:
**Now in Shanghai, China, its 2024-04-22**
**Now in Los Angeles, its 2024-04-21**
**?sample=true page should cover all dates, no matter where you are**
**The report page should also address this inconsistency**
**Shanghai**
**Los Angeles**
=> fix(ui): time zone inconsistency in charts

ee/tabby-ui/components/prompt-form.tsx
Prevent form submission on pressing Enter when the response is still loading in the playground
=> fix(ui): block form submission upon loading of response in playground

ee/tabby-ui/app/(dashboard)/reports/components/daily-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx, ee/tabby-ui/app/(home)/components/stats.tsx
To support the backend changes in this PR: https://github.com/TabbyML/tabby/pull/1920
**Fix query date range**
Before: `2024-04-16T00:00:00Z - 2024-04-24T00:00:00Z`
After: `2024-04-15T16:00:00Z - 2024-04-23T15:59:59Z`
**Fix date display**
Before: `2024-04-15T16:00:00Z` will be counted as `2024-04-15`.
After: `2024-04-15T16:00:00Z` will be counted as `2024-04-16`
Tested:
pages: home / reports / ?sampe=true
timezone: Shanghai / Los Angeles
=> fix(ui): analytics daily report date query and display

ee/tabby-ui/app/(dashboard)/reports/components/annual-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/daily-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx, ee/tabby-ui/app/(home)/components/stats.tsx, ee/tabby-ui/lib/tabby/query.ts
Replace `.completions` with `views` in all places, but the text on the page is still named 'Completions'.
Including:
* Home page - yearly activity
* Home page - daily charts
* Home page - language charts
* Report page - yearly activity
* Report page - daily charts
=> fix(ui): using views to represent completion data in analytics charts

ee/tabby-ui/app/(dashboard)/reports/components/daily-activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx, ee/tabby-ui/app/(home)/components/stats.tsx, ee/tabby-ui/lib/tabby/query.ts
- Removing redundant API calls for the language charts
- Reconstructed the data from `dailyStats` to populate the language charts
- Updated the sample page to include language charts for Rust, Python, and TypeScript
- Removing the `language` parameter in the `dailyStats` request
- Moved language selection logic to the frontend, no extra API requests
- Updated the sample page to include the data for Rust, Python, and TypeScript
fix TAB-557
=> fix(ui): optimize daily language stats data fetching

CHANGELOG.md, ee/tabby-db/src/user_completions.rs, ee/tabby-webserver/src/service/analytic.rs
=> fix(db): don't count inactive users in stats

ee/tabby-db/src/github_repository_provider.rs, ee/tabby-db/src/lib.rs, ee/tabby-db/src/user_completions.rs, ee/tabby-db/src/user_events.rs, ee/tabby-webserver/src/integrations/github.rs, ee/tabby-webserver/src/service/analytic.rs
=> fix(db): fix bugs based on sqlite date format difference from chrono

Cargo.lock, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/path.rs, ee/tabby-webserver/src/schema/analytic.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/analytic.rs
=> feat(webserver): add endpoint to calculate disk usage

ee/tabby-db/src/github_repository_provider.rs, ee/tabby-db/src/gitlab_repository_provider.rs, ee/tabby-db/src/repositories.rs, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/handler.rs, ee/tabby-webserver/src/repositories/mod.rs, ee/tabby-webserver/src/repositories/resolve.rs, ee/tabby-webserver/src/schema/git_repository.rs, ee/tabby-webserver/src/schema/github_repository_provider.rs, ee/tabby-webserver/src/schema/gitlab_repository_provider.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/schema/repository.rs, ee/tabby-webserver/src/service/git_repository.rs, ee/tabby-webserver/src/service/github_repository_provider.rs, ee/tabby-webserver/src/service/gitlab_repository_provider.rs, ee/tabby-webserver/src/service/repository.rs
=> refactor(webserver): support browsing github / gitlab repositories.

clients/vscode/src/CodeSearchEngine.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/utils.ts
Complete TAB-623
Changes:
- Use DocumentSemanticTokensProvider to get semantic symbols instead of simply spliting words
- Only extract declarations for these symbol types:
- class 
- decorator
- enum
- function
- interface
- macro
- method
- namespace
- struct
- type
- typeParameter
=> fix(vscode): improve extracting declarations using DocumentSemanticTokensProvider.

crates/tabby-common/src/languages.rs, crates/tabby-common/src/lib.rs, crates/tabby-scheduler/src/dataset/mod.rs, crates/tabby-scheduler/src/index.rs, crates/tabby-scheduler/src/lib.rs, crates/tabby-scheduler/src/repository.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/src/main.rs
1. Handle error as early as possible, e.g when clone failed, remove the cloned directory.
2. For IO related error (e.g open a file, read database, just panic if there's an error).
=> refactor(scheduler): restructure scheduler error handling.

Cargo.lock, crates/tabby-scheduler/src/repository.rs, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/cron/controller.rs, ee/tabby-webserver/src/cron/db/github.rs, ee/tabby-webserver/src/cron/db/gitlab.rs, ee/tabby-webserver/src/cron/db/mod.rs, ee/tabby-webserver/src/cron/mod.rs, ee/tabby-webserver/src/cron/scheduler.rs, ee/tabby-webserver/src/schema/mod.rs
=> refactor(webserver): extract JobController

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/stats.tsx, ee/tabby-ui/lib/hooks/use-server-info.ts
* Enable demo view when server start with `TABBY_WEBSERVER_DEMO_MODE=true`
* Reduce the acceptance rate for the demo view
=> feat(ui): support demo mode

CONTRIBUTING.md
Toolchain installed on Ubuntu working with command `cargo run -r --features cuda serve --model TabbyML/StarCoder-1B --device cuda`.
For me I needed to set https://getdocs.org/Cmake/docs/3.21/envvar/cudacxx in your environment (`~/.bashrc` for me adding `export CUDACXX=/usr/local/cuda/bin/nvcc` after install of CUDA)
Closes #2033
=> docs: note on intalling GPU toolkits for contributors

crates/llama-cpp-bindings/src/engine.cc
This PR allows to set the `LLAMA_CPP_N_GPU_LAYERS` env var to specify the number of layers to offload to GPU (using the `llama.cpp --n-gpu-layers` flag). Fixes #892.
=> feat: Add environment variable to specify the number of layers to offload to GPU

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/add-repository-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/github-provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/components/tabs-header.tsx, ee/tabby-ui/app/files/components/blob-header.tsx, ee/tabby-ui/app/files/components/file-directory-view.tsx, ee/tabby-ui/app/files/components/repository-kind-icon.tsx
1. Do not display Content-Length when it is not set
2. Scroll bar should keep at top when inputing
https://jam.dev/c/a1d76cd0-816f-48c6-b7ae-bd5c7673b1dc
3. Change the icon for git repositories
=> fix(ui): do not display Content-Length when it is not set

ee/tabby-ui/app/(dashboard)/components/main-content.tsx, ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/page.tsx, ee/tabby-ui/app/playground/components/chat-sessions.tsx, ee/tabby-ui/components/demo-banner.tsx, ee/tabby-ui/components/providers.tsx
* Refactor the demo-banner component to use Context instead of a simple hook because a hook cannot trigger re-renders in other components.
* Testing more pages/layouts with and without the banners.
`/api`
`/playground`
`/files`
`/auth`
=> fix(ui): refactor demo-banner to fix ui bugs

clients/vim/autoload/tabby/agent.vim
In the vim plugin, whenever the tabby-agent exits (unexpectedly) the s:tabby variable is set to `{}` instead of the numeric `0` to indicate that the agent job is not running.
This leads to the agent functions trying to send messages anyway and error messages being spammed for almost any editor event, for the wrong variable type and subsequent errors, like:
```
line    8:
E731: using Dictionary as a String
line   12:
E474: Invalid argument
```
and
```
Error detected while processing BufLeave Autocommands for "*"... [...]
```
Setting the s:tabby variable to `0` on agent exit solves it.
=> fix(vim): fix agent exit wrong type bug

crates/tabby-common/src/index.rs, crates/tabby-common/src/lib.rs, crates/tabby-scheduler/src/cache.rs, crates/tabby-scheduler/src/index.rs, crates/tabby-scheduler/src/lib.rs
=> feat(scheduler): implement incremental indexing for tantivy

ee/tabby-ui/lib/hooks/use-health.tsx
logout -> clean sessionStorage -> manually open http://loclhost:8080
Before login, useHealth received a 401 error in `http://localhost:8080`. useSWR will cache the data as undefined.
When quickly login and calling useHealth, it uses the cached data and returns undefined, causing the page to stop rendering.
~Prevent the cache for a 401 error.~ No cache for any response error
~Using `useSWRImmutable` instead of `useSWR` to reduce the number of fetches.~
Screen record: https://jam.dev/c/f2838518-22ff-4c46-aa7c-1962fb72e08d
=> fix(ui): prevent storing useHealth cache for unauthorized error

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/add-repository-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/github-provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/gitlab-provider-detail.tsx, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/0ba6d9e6-7472-49df-b79a-b7ade4fd396d
=> fix(ui): filtering repos by active status

ee/tabby-ui/app/files/components/file-tree-header.tsx
=> fix(ui): adjust style of selected repository in code browser

ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx
1. display a skeleton after switching repositories
before: https://jam.dev/c/dd54032d-ad8b-497e-b03a-02baa0eda59e
after: https://jam.dev/c/68f58438-73d3-4b7f-9032-7a7df0ae554f
2. Reduce the delay time for showing the loading indicator after clicking the expand button in the file tree.
=> fix(ui): display a skeleton after switching repositories

clients/tabby-agent/package.json, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/Auth.ts, clients/tabby-agent/src/CompletionCache.ts, clients/tabby-agent/src/JsonLineServer.ts, clients/tabby-agent/src/LspServer.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/configFile.ts, clients/tabby-agent/src/env.ts, clients/tabby-agent/src/loadCaCerts.ts, clients/tabby-agent/src/logger.ts, clients/tabby-agent/src/postprocess/base.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/postprocess/dropDuplicated.ts, clients/tabby-agent/src/postprocess/formatIndentation.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.ts, clients/tabby-agent/src/postprocess/removeDuplicatedBlockClosingLine.ts, clients/tabby-agent/src/postprocess/removeLineEndsWithRepetition.ts, clients/tabby-agent/src/postprocess/removeRepetitiveBlocks.ts, clients/tabby-agent/src/postprocess/removeRepetitiveLines.ts, clients/tabby-agent/src/postprocess/trimMultiLineInSingleLineMode.ts, clients/tabby-agent/src/utils.ts, clients/vscode/src/RecentlyChangedCodeSearch.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/TabbyStatusBarItem.ts, clients/vscode/src/commands.ts, clients/vscode/src/extension.ts, clients/vscode/src/logger.ts, clients/vscode/src/notifications.ts
Complete TAB-606 TAB-620
Changes:
Refine all logging levels to `error`, `info`, `debug`, and `trace`. All runtime variable values will only be logged at the `trace` level.
Preview in VSCode Output:
=> fix(agent&vscode): improve logging.

ee/tabby-ui/app/(dashboard)/activities/components/activity.tsx
In the Activities page, the `Last 24 hours` is requesting the wrong range of data.
=> fix(ui): activity page default range

crates/llama-cpp-bindings/build.rs
Even in currently used version (5.7.1) all lib symlinks are available in /opt/rocm-xxx/lib/.
Sin ROCm 6.0.0 there is no separate folders with dev libs for each lib.
=> core: fix building rocm version with modern ROCm

clients/tabby-chat-panel/dist/index.cjs, clients/tabby-chat-panel/dist/index.d.cts, clients/tabby-chat-panel/dist/index.d.mts, clients/tabby-chat-panel/dist/index.d.ts, clients/tabby-chat-panel/dist/index.mjs, clients/tabby-chat-panel/dist/react.cjs, clients/tabby-chat-panel/dist/react.d.cts, clients/tabby-chat-panel/dist/react.d.mts, clients/tabby-chat-panel/dist/react.d.ts, clients/tabby-chat-panel/dist/react.mjs, clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/index.ts, clients/tabby-chat-panel/src/react.ts, clients/tabby-chat-panel/yarn.lock
* Using @quilted/threads to replace remote-ui/rpc
* Change FileContext
```
export interface LineRange {
start: number
end?: number
}
export interface FileContext {
kind: 'file'
range?: LineRange
language?: string
path: string
}
```
* Add `sendMessage` to the interface `Api`, the sendMessage is used for scenarios like `explain it`.
* In the `src/react` update method `useClient` and `useServer` (make sure the iframe is rendering)
=> feat(client): update chat-pannel and switch to threads

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/Agent.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/AgentService.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/git/DefaultGitContextProvider.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/git/Git4IdeaGitContextProvider.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/git/GitContextProvider.kt, clients/intellij/src/main/resources/META-INF/git4idea-features.xml, clients/intellij/src/main/resources/META-INF/plugin.xml
This MR adds some aditional context to completion requests from intelij idea
Fixes #1962
=> clients: extend completion request context for intelij idea

clients/tabby-chat-panel/dist/index.cjs, clients/tabby-chat-panel/dist/index.d.cts, clients/tabby-chat-panel/dist/index.d.mts, clients/tabby-chat-panel/dist/index.d.ts, clients/tabby-chat-panel/dist/index.mjs, clients/tabby-chat-panel/dist/react.cjs, clients/tabby-chat-panel/dist/react.d.cts, clients/tabby-chat-panel/dist/react.d.mts, clients/tabby-chat-panel/dist/react.d.ts, clients/tabby-chat-panel/dist/react.mjs, clients/tabby-chat-panel/src/index.ts, clients/tabby-chat-panel/src/react.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/lib/event-emitter.ts, ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/types/chat.ts
https://jam.dev/c/84eb9ae8-8a7b-477f-bc38-9a44b7d2cf6d
* `tabby-chat-panel`: New client-side API `navigate`. One use case for invoking `navigate` is when a user clicks on a reference link in the chat.
* `tabby-chat-panel/react`: Enhance the initialization of useServer and useClient. Prevent duplicate rendering in React development mode.
* `ee/tabby-ui/chat`: New page which embed the Chat component, it owner userServer
* `ee/tabby-ui/files/components/chat-side-bar.tsx`: Embed /chat iframe with useClient
=> feat(ui): add chat page and integrate with files

docker/Dockerfile.cuda, docker/Dockerfile.rocm
There was missing `&&` so `cp` commands always fails and `tabby-cpu` was copied from unmounted cache so it fails too
=> fix(docker): correct dockerfiles to fix build

ee/tabby-ui/components/providers.tsx, ee/tabby-ui/lib/tabby/auth.tsx
When I render `/chat` in the VSCode side bar, I don't wanna jump to the login page.
Without logging in, the chat component won't display the user's avatar (the image below). Looks we need to enhance the UI for this scenario. @liangfung
=> fix(ui): allow rendering chat without auth

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx
finish 0s ago => 0s
finish 50s ago => 50s
finish 1m ago => 2m 
**^This seems odd; another approach could be directly using the humanizerDuration output, 1m=>1m; 1m10s=>1m; 
1m30s=>2m**
finish 1m1s ago => 2m
finish 2h40m ago => 3h
=> fix(ui): fix the duration display on the job list

ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/constant.ts, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/page.tsx, ee/tabby-ui/app/auth/signin/components/signin-section.tsx, ee/tabby-webserver/src/routes/oauth.rs
create gitlab oauth credential:
preview: https://jam.dev/c/232b488c-f9d4-4e97-aa0f-5f5e6c82feea
sign in with gitlab:
=> feat(ui): add gitlab sso support

ee/tabby-db/src/lib.rs, ee/tabby-db/src/refresh_tokens.rs, ee/tabby-db/src/users.rs, ee/tabby-webserver/src/oauth/github.rs, ee/tabby-webserver/src/oauth/gitlab.rs, ee/tabby-webserver/src/oauth/google.rs, ee/tabby-webserver/src/oauth/mod.rs, ee/tabby-webserver/src/service/analytic.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/event_logger.rs, ee/tabby-webserver/src/service/user_event.rs
Follow up of https://github.com/TabbyML/tabby/pull/2100#pullrequestreview-2053445842
~~This PR is almost done, so I want to raise it for review, to make sure I'm on the correct direction.~~
The core changes in this PR resides in following places
- Add extra `name: Option<String>,` parameters for `create_user` & `create_user_with_invitation` methods inside of `tabby-db` crate
- A lot of unit tests depend on this 2 methods, so update all of them accordingly.
- Extract token exchange logic from `fetch_user_email` method, added new `fetch_user_full_name` method, pass in access token to fetch user email & user name
- Update google oauth scope to request user's profile info
- Update gitlab integration
- Improve unit test for `get_or_create_oauth_user`
Tested registration by invitation branch …
=> feat: fill user's name when register by oauth

ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx
1. Auto-scrolls the active code line into view within the code browser for navigation
2. Auto-scrolls the active file tree node into view
https://jam.dev/c/1865fdbc-47e6-4e64-a9bc-35c49f28ac77
=> refactor(ui): scroll active code line into view

ee/tabby-ui/components/chat/chat-scroll-anchor.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/lib/hooks/use-at-bottom.tsx
1. scroll to bottom when a prompt is sent
https://jam.dev/c/c7466c7e-8414-4116-a490-2a97c9de66fa
2. fix the issue where it wasn't automatically scrolling to the bottom during the process of generating an answer
=> fix(ui): scroll to bottom when a prompt is sent

Cargo.lock, Cargo.toml, crates/http-api-bindings/Cargo.toml, crates/http-api-bindings/src/chat/mod.rs, crates/http-api-bindings/src/completion/mod.rs, crates/http-api-bindings/src/embedding/mod.rs, crates/llama-cpp-server/src/lib.rs, crates/ollama-api-bindings/Cargo.toml, crates/ollama-api-bindings/src/chat.rs, crates/ollama-api-bindings/src/completion.rs, crates/ollama-api-bindings/src/embedding.rs, crates/ollama-api-bindings/src/lib.rs, crates/ollama-api-bindings/src/model.rs, crates/tabby/src/services/model/mod.rs
A full-featured completion, chat, embedding ollama api binding. Currently, tries to pull model automatically on Ollama side if cannot find it.
---
Closes #2176
=> feat: Added ollama api connection options

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-ui/app/auth/signup/components/user-register-form.tsx, ee/tabby-webserver/src/service/auth.rs
Register with name
* The `name` field is required
* Admin register with name
* Member register with invitationCode & name
=> feat(ui): register with name

ee/tabby-ui/app/(dashboard)/profile/components/change-name.tsx, ee/tabby-ui/app/(dashboard)/profile/components/profile.tsx, ee/tabby-ui/lib/hooks/use-me.ts
* If name unchanged, the button is disabled
* If name is empty, the button is disabled
Screen record: https://jam.dev/c/2ae4fc65-a124-47ca-86e9-973015450071
=> feat(ui): modify name in profile

clients/tabby-chat-panel/src/index.ts, clients/tabby-chat-panel/src/react.ts
I tried another way - destroying previous instance and create a new one
```
function useServer(api: ServerApi) {
const [server, setServer] = useState<ClientApi | null>(null)
let abortController:AbortController
useEffect(() => {
const isInIframe = window.self !== window.top
if (isInIframe) {
abortController?.abort()
abortController = new AbortController()
setServer(createServer(api, abortController.signal))
}
}, [])
return server
}
```
But in this way, the thread lib will throw error, so I keep using `isCreated` for simplify
=> fix(chat-panel): react rendering

ee/tabby-ui/components/ui/scroll-area.tsx
The chat component in `/playground` is wrapped with`ScrollArea`, but after wrapping, the markdown does not adapt to the width automatically.
Set `display: block` for ScrollArea Viewport
=> fix(ui): scroll-area display style

clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/copy-button.tsx, ee/tabby-ui/components/ui/codeblock.tsx, ee/tabby-ui/lib/hooks/use-copy-to-clipboard.tsx
Screen record: https://jam.dev/c/815a5168-36c7-467a-8015-356454fdc93c
Changes:
* Remove the `download` on the code block
* For the `copy`, I removed the error handler to simplify the logic and make the `copy` always sending a message to its parent environment so that in VSCode, it can catch the event and use its native clipboard API. I also tested in code browser and I don't see any side effect.
=> fix(vscode): copy function for vscode and remove codeblock download

ee/tabby-ui/components/chat/question-answer.tsx
The following changes only take affect when width smaller than `md` 
* Avatar into one column 
* Action icons go to the top-right and only display when hover
hover on the user's question, so the delete icon showed
hover on the answer
=> feat(ui): chat layout change to 1 col under md

clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/ContextVariables.ts, clients/vscode/src/chat/ChatViewProvider.ts, clients/vscode/src/chat/chatPanel.ts, ee/tabby-ui/app/chat/page.css, ee/tabby-ui/components/chat/question-answer.tsx
* `tabby.experimental.chat.explainCodeBlock` -> `tabby.chat.explainCodeBlock`
* Remove `tabby.explainCodeBlockEnabled`
* Remove `right-click` menu
* Add 3 more commands to the command palette (see the below)
=> feat(vscode): add commands for the chat panel

crates/ollama-api-bindings/src/model.rs
If model tag is unspecified the check will fail because `/api/tags` returns model name with `:latest` appended, so the check will mismatch. However, `/api/show` handles it correctly.
**example**
Specifying `llama3` as chat model was fail because was checked on 'llama3:latest'
My mistake, I've tested it on explicit tags on when implementing because using q5_K_M models. I am sorry, that I did not found it before release of 0.12 :cry:
=> fix(ollama-api-bindings): Fix model availability check

crates/llama-cpp-server/src/supervisor.rs
find_binary_name() already returns .exe at the end for the executable. So there is no need to add .exe a second time. Removing this fixes the bug on Windows where it will search for a binary ending on ".exe.exe". I have only tested this on Windows 11 23H2, but I don't think behaviour on other versions would be different.
Current behaviour:
Behaviour after commit:
=> fix: Windows server_binary path adding unnecessary ".exe"

ee/tabby-ui/components/providers.tsx, ee/tabby-ui/lib/posthog.tsx, ee/tabby-ui/package.json, pnpm-lock.yaml
=> feat(ui): add posthog tracking on the demo web

ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/error-view.tsx, ee/tabby-ui/app/files/components/file-directory-breadcrumb.tsx, ee/tabby-ui/app/files/components/file-directory-view.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/file-tree-panel.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/text-file-view.tsx, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/components/topbar-progress-indicator.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/hooks/use-router-stuff.ts, ee/tabby-webserver/development/Caddyfile
1. Support browsing different git tree in code browser
2. Optimize Code Browser URL Pattern
3. Simplify the implementation logic of the code browser and add cache refreshing when navigating in code browser
4. Add error view
5. Fix: handle gitlab project with multiple nested organization properly
https://jam.dev/c/ff1a9189-f029-46d3-81e9-ee009ce817ff
=> feat(ui): support browsing different git tree in code browser

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/user-panel.tsx
* Display `settings` in the user-panel on the home page
* In settings page, clicking `home` should not opening new page
* Align the header's css between home and settings
=> fix(ui): align header between home and settings

ee/tabby-ui/components/chat/question-answer.tsx
1. truncate overflowing text with an ellipsis
2. remove props that cannot be recognized
screen shot: https://jam.dev/c/163533bd-8b1d-4462-b424-1f3435bda9d4
=> fix(ui): adjust the display of code references

ee/tabby-ui/app/(home)/components/search.tsx
Show stop button `setShowStop(true)` after 1500ms when `isLoading` is true. However, a bug could occur if isLoading changes to false within those 1500ms. 
I used useLatest(isLoading) to double-check the isLoading state before showing the stop button.
=> fix(ui): stop button display after loading

ee/tabby-ui/components/ui/codeblock.tsx
The code block fails to display .toml files correctly
`[workspace]` becomes multiple lines because `react-syntax-highlighter` add `.table` to the `workspace`, causing it to be displayed as a table and occupy a whole line
I didn't find any discuss addressing this issue so I guess that's because `react-syntax-highlighter` can't handle .toml correctly 
Use the bash syntax to render .toml files
=> chore(ui): render toml code syntax correctly

ee/tabby-ui/app/(home)/components/search.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/textarea-search.tsx
When clicking the `stop` button immediately after starting a search, the answer still appears to be loading.
The logic `if (!answer) return` is useless.
Previously, the stop button was displayed after a 1500ms delay, which prevented this potential bug 
happened when the height is very small
issue: https://jam.dev/c/ca8e58cb-07e7-4bb6-aaff-75ad7ba0e673 
CSS problem, adding `min-h-0`
In the home page, auto focus on the input at the beginning
=> fix(ui): fix home height and autofocus and stop button not working

ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/lib/hooks/use-router-stuff.ts, ee/tabby-ui/lib/utils.ts
In PR #2436 , i updated the comcatenation logic for URL in the chat view of VSCode client to use hash  like `#L{number}` instead of  searchParam like `?line={number}`
https://github.com/TabbyML/tabby/pull/2436/files#diff-22897189febb57c85bc910ac40ed86b59d35c03d5e051b9c4741c37eb749bfc7R109
add a backward compatibilty logic
=> fix(ui): add backward compatibilty for line query

Cargo.lock, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/code/cache.rs, crates/tabby-scheduler/src/code/index.rs, crates/tabby-scheduler/src/code/mod.rs, crates/tabby-scheduler/src/code/source_file_key.rs, crates/tabby-scheduler/src/indexer.rs, crates/tabby-scheduler/src/lib.rs, ee/tabby-webserver/src/service/background_job/git.rs
After investigating tantivy in depth - it concludes that the KV functionality can be fully replaced by reading tantivy directly
=> refactor(scheduler): remove kv cache, using tantivy directly for incremental indexing + garbage collection

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/components/common-provider-form.tsx
=> fix(ui): correct the placholder for provider display name

Cargo.lock, crates/tabby-common/Cargo.toml, crates/tabby-common/src/config.rs, crates/tabby/src/main.rs
Original issue https://github.com/TabbyML/tabby/issues/2228 suggests print warning or error log if `config.toml` is invalid.
Well, it's viable, what I'm thinking is perhaps stop until `config.toml` is fixed properly by the user.
This change applies following logic
- If `config.toml` is missing, return default config allow tabby to be started with a `Warning` mesage
- if `config.toml` is invalid, panic & display error
=> refactor: panic on invalid config.toml loading

docker/Dockerfile.cuda
When use `tabbyml/tabby:latest`, we got
`WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:88: llama-server exited with status code 127, restarting...`
in container try run `llama-server` we got
`llama-server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`
So we add environment `LD_LIBRARY_PATH` to fix this base image bug
=> ci: add compat ld path for locatinglibcuda.so.1 in docker build

ee/tabby-ui/app/files/components/line-menu-extension/line-menu-extension.tsx
change 'Copy permalink' to 'Copy link'
=> fix(ui): correct text of line menu in code browser

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx
https://jam.dev/c/a8a60d50-f9ee-4e46-b477-1410613ecd89
=> fix(ui): only display the spinner when the job state is 'running'

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/code/languages.rs, website/docs/programming-languages.md
Attempting to add Lua support, following the recommended example #553.
I'm not so used to GH Pull requests, so feel free to fix and make recomendations along the way.
Cheers!
=> feat: support for Lua

ee/tabby-ui/lib/posthog.tsx
When loading the site inside iFrame with postHogProvider, the iframe page is empty
PostHogProvider from `posthog-js/react` makes the bug, but not sure about the root reason at the moment.
PostHog has official doc about [Iframe recording](https://posthog.com/docs/session-replay/iframes), it says `If the iframe is from the same domain as the main page, there is no special setup needed.`. I didn't find we have setting up any restriction like Content-Security-Policy, so not sure what we can fix with PostHogProvider.
Disable PostHogProvider inside iFrame
now when user opening `Ask Tabby` inside code browser, the event on PostHog dashboard is:
=> fix(ui): disable posthog inside iframe

docker/Dockerfile.cuda, docker/Dockerfile.rocm
ref: https://github.com/ggerganov/llama.cpp/pull/7780
fix `tabbyml/tabby:nightly` cannot run with
`WARN llama_cpp_server::supervisor: crates/llama-cpp-server/src/supervisor.rs:106: <embedding>: /opt/tabby/bin/llama-server: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory`
=> ci: add openmp lib to dockerfiles

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/textarea-search.tsx
The dark theme looks fine, so keep it same as before
Smaller search input
=> fix(ui): adjust border color of search input in search page

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/components/header.tsx
Because too much width looks not suitable for the charts
Before:
After:
=> chore(ui): admin report padding & admin header padding

clients/tabby-chat-panel/src/index.ts, clients/vscode/assets/chat-panel.css, clients/vscode/src/chat/ChatViewProvider.ts, clients/vscode/src/chat/chatPanel.ts, clients/vscode/src/extension.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/globals.css, ee/tabby-ui/components/providers.tsx, pnpm-lock.yaml
* In the chat panel, we render the /chat website asap without waiting agent's response
* In the `/vscode/src/extension.ts`, I move the place of registering chat panel before `await client.start()` because client.start usually takes 2+ seconds
* Inside /chat page, adding new logics to
* Display loading
* Display error message
* When VSCode side got error (Unauthorized or unavailable), it send message to /chat page to display the error
* In ChatViewProvider, now I have 2 separate logics for the chat page
1. **renderChatPage**: this will render the /chat iframe, only `endpoint` is needed; This method will be called for the first time opening the panel & `agent.on("didUpdateServerInfo"`
2. **reloadChatPage** (maybe can have a better name): it will fetchServerInfo and check agent.status, able …
=> feat(vscode): separate chat panel rendering

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/Commands.ts, clients/vscode/src/chat/ChatViewProvider.ts, clients/vscode/src/chat/chatPanel.ts, clients/vscode/src/extension.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx
When code is selected in the editor, the chat panel can send a message containing the selected code to the server
If no code is selected, the chat panel will not include additional information
1. The `/chat` page has a new query parameter `handle-message-submit`. When `handle-message-submit=true`, `/chat` page delegates the handling of the submitted message to its parent container (e.g., VSCode).
2. In VSCode, when `onSubmitMessage` is called, it attempts to fetch the selected code snippets.
3. VSCode then calls the `/chat` endpoint to process the new message, including the selected code as relavantContext, and inside the /chat, it will take relavantContext as code_query.
=> feat(vscode): send chat message with selection if available

ci/prepare_build_environment.sh
Related https://github.com/pypa/manylinux/issues/1641
CentOS 7 goes to EOL in 06/2024, need to update mirror address
=> ci: fix centos mirror address

crates/llama-cpp-server/src/lib.rs, crates/tabby-common/src/config.rs, crates/tabby/src/main.rs
Explicitly enable fast attention for Qwen2-1.5B-Instruct model, as it has been our recommended default since version 0.13. However, it presents some problems in certain CUDA environments. For details, see https://github.com/TabbyML/tabby/issues/2550. Once upstream issues are resolved, we should remove this workaround.
=> chore: enable fast attention for Qwen2-1.5B-Instruct model

clients/vscode/src/chat/ChatViewProvider.ts
The filepath is not decoded
**Request from VSCode after fix**
**Request from web code browser currently**
=> fix(vscode): chat panel context filepath should be decoded

crates/http-api-bindings/src/completion/mod.rs, crates/http-api-bindings/src/completion/openai.rs, website/docs/administration/model.md
Add support for OpenAI completion API in order for tabby to be plugged to other OpenAI compatible backends (for example vLLM).
Tested with the vLLM backend, autocompletion is a lot faster and can support more concurrent requests than the llama.cpp backend.
=> feat: add support for OpenAI completion API

.changes/unreleased/Fixed and Improvements-20240710-185920.yaml, crates/tabby/src/services/code.rs
Previously, the git_url used in the index was not properly canonicalized, leading to inconsistencies when performing queries. This commit updates the code to ensure that the git_url is canonicalized before performing the code search.
cc @gyxlucy
=> fix(core): canonicalize git_url before performing code search

ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/lib/hooks/use-debounce.ts
Relates #2557 
Before unloading the `/playground` page, try to flush any pending invocations of the debounced function responsible for persisting chats.
=> fix(ui): persist chats on unmount

docker/Dockerfile.cuda
When docker build then log show:
```txt
2 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 9)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 49)
```
=> ci: fix dockerfile warnings: 'as' and 'FROM' keywords' casing do not match

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/src/serve.rs
For closing https://github.com/TabbyML/tabby/issues/2457
- Add `spinner` dep
- If binary is `prod` release, spawn the spinner in a tokio task, if binary is dev release, just print debug log as before
- Use `onshot` channel to coordinate with main thread
Test result:
=> feat: add spinner for prod release

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/tree-mode-view.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/textarea-search.tsx, ee/tabby-ui/lib/constants/index.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-ui/lib/types/chat.ts
Support selecting repositories to enhance answer engine.
https://jam.dev/c/90930692-ae11-4e57-8efd-c459fa4cc64c
=> feat(ui): support selecting repositories in answer engine

clients/tabby-agent/package.json, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/configFile.ts, clients/tabby-agent/src/http/proxy.ts, clients/tabby-agent/tsup.config.ts, pnpm-lock.yaml
Changes:
- Add support for http proxy. The proxy can be configured using:
- environment variables ( http_proxy, https_proxy, no_proxy ) [more detail](https://github.com/nodejs/undici/blob/main/docs/docs/api/EnvHttpProxyAgent.md)
- in `~/.tabby-client/agent/config.toml`, override environment variables
```yaml
[proxy]
url = "http://127.0.0.1:1087"  # or http://user:pass@127.0.0.1:1087  if auth required
```
Proxy config in IDE (VSCode) is not supported for now. This is planned to be supported in a future release.
=> feat(agent): http proxy support

ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/line-menu-extension/line-menu-extension.tsx, ee/tabby-ui/components/codemirror/codemirror.tsx
1. Add multiline highlight in code browser
2. When multiple lines are highlighted, user can use the 'Copy lines' option in the line menus to copy the text content of the selected lines.
https://jam.dev/c/1986db82-b517-454f-b4b7-3a80ed88a7a5
=> feat(ui): add multiline highlight in code browser

clients/vscode/assets/chat-panel.css, clients/vscode/src/chat/ChatViewProvider.ts
**Issue**: When the server instance is not up, the chat panel is currently empty.
**After Fix:** Display a message.
**Issue**: Quickly clicking the refresh button sometimes prevents correct rendering.
**After Fix**: https://jam.dev/c/c6533855-1109-4ba8-9010-b78a5d984eb1
* This PR needs to be cherry-picked for VSCode 1.8.0
* Tested other 1.8.0 chat-panel features as well
* Testing backend version: `0.14.0-rc.0`
=> fix(vscode): improve rendering logic

ee/tabby-ui/app/globals.css
=> fix(ui): truncate text in answer page

clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/Config.ts
This PR is relate issue #2673
- Fixes #2673 
This PR addresses two main issues:
- Managing the recentlyCommand list length:
- Ensures that the list of recently used commands does not exceed the maximum number configured by the user.
- Adding a delete button:
- Adds a delete button to the right of each recentlyCommand, allowing users to remove unwanted commands easily.
=> feat(vscode) vscode config limit recently commands

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/ui/icons.tsx
We want to enable users to manually select context. For example, users can select a piece of code and add it to the context so that it will be included with their message next time.
User selected context as shown in the following screenshots:
For testing purposes, adding client context is triggered via the command palette.
https://jam.dev/c/8477d02f-9e37-4ac7-8bad-ae87d1b11778
1. **Editor adds new context:** By using the new method exposed on the tabby-chat-panel, `this.client?.addClientSelectedContext(Context)`
2. **Receiving context:** tabby-ui receives the context and saves it into its new state `clientSelectedContext`
3. **Displaying context:** tabby-ui displays the clientSelectedContext (as shown in the above screenshot)
4. **Removing context:** tabby-ui can remove the context using …
=> feat(vscode): support client selected context

clients/tabby-agent/src/TabbyAgent.ts
This addresses the remaining part of the issue mentioned in #2581.
- Retrieve client info based on the client configuration during client initialization.
Example User-Agent format:
```
Node.js/v20.9.0 Visual-Studio-Code-desktop/1.91.1 TabbyML.vscode-tabby/1.8.0-dev
```
=> feat: Add general IDE info to User-Agent for Tabby clients

crates/tabby/src/routes/mod.rs
when the url have the `http://` prefix, we can click it in the terminal while holding command
=> chore: add http prefix for tabby server let address clickable

.changes/unreleased/Fixed and Improvements-20240811-124728.yaml, crates/tabby-index/src/doc/public.rs
Fixing bad cases like below:
@xxs-wallace
=> chore(index): skip web documents if body is empty

crates/llama-cpp-server/build.rs
Various `LLAMA_` build flags have been renamed to `GGML_` in llama-cpp-server (See https://github.com/ggerganov/llama.cpp/commit/f3f65429c44bb195a9195bfdc19a30a79709db7b) and need to be renamed in tabby to allow correctly targeting Metal/Rocm/Vulkan.
It appears that this was already done for Cuda.
May be related: https://github.com/TabbyML/tabby/issues/2811
=> fix(llama-cpp-server): fix rocm build by setting `GGML_HIPBLAS`

crates/tabby-common/src/api/code.rs, crates/tabby-common/src/config.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/code.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/completion/completion_prompt.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/webserver.rs
@xxs-wallace 
Example config
```toml
[answer.code_search_params]
num_to_return = 10
num_to_score = 20
min_embedding_score = 0.5
min_rrf_score = -1.0
min_bm25_score = -1.0
```
=> refactor(core): extract CodeSearchParams, make it configurable for completion / answer engine

crates/tabby-common/src/api/code.rs, crates/tabby-common/src/config.rs, crates/tabby-common/src/index/code/mod.rs, crates/tabby-common/src/index/mod.rs, crates/tabby-index/src/code/index.rs, crates/tabby-index/src/code/intelligence.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/lib.rs, crates/tabby/src/services/code.rs, crates/tabby/src/services/completion/completion_prompt.rs, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/repository/git.rs, ee/tabby-schema/src/schema/repository/mod.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/background_job/git.rs, ee/tabby-webserver/src/service/background_job/index_garbage_collection.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/repository/git.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/third_party.rs, ee/tabby-webserver/src/webserver.rs
1. We change the definition of `source_id` in index to be across corpus.
2. We set source_id for code corpus as format of `git:$id`, `provided_repository:$id`, `config:$id`, ...
=> feat(index): BREAKING: change source_id definition to make it across corpus

ee/tabby-db/src/lib.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/constants.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/web_documents.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/web_documents.rs, ee/tabby-webserver/src/webserver.rs
one of https://github.com/TabbyML/tabby/pull/2898
=> refactor(document): add web document service api

ee/tabby-db/src/web_documents.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/constants.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/web_documents.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/preset_web_documents_data.rs, ee/tabby-webserver/src/service/web_documents.rs
one of https://github.com/TabbyML/tabby/pull/2898
=> feat(document): support crawl preset document

ee/tabby-webserver/src/service/background_job/web_crawler.rs
add timeout to prevent one job block the whole background loop
=> refactor(crawler): add timeout for crawler job

clients/vscode/src/Commands.ts
fixing https://github.com/TabbyML/tabby/issues/2923
Please note that it's not currently possible to use the `tab` key to trigger such an action, as the VSCode API does not support it. However, this button should provide sufficient convenience for the time being.
=> feat(vscode): add an edit button in inline edit history

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown.tsx, ee/tabby-ui/lib/types/chat.ts, ee/tabby-ui/lib/utils.ts
When copying an assistant message, if the message content includes a citation pointing to an attachmentCode, the copied value is not correctly formatted
https://jam.dev/c/27b21e4c-0c3f-4d49-9dbb-94d7b4e52950
=> fix(ui): correct the copied content from assistant messages

ee/tabby-db/src/users.rs, ee/tabby-webserver/src/service/auth.rs
Allow impersonate as owner user. 
Developer can set email/password with environment variable TABBY_OWNER_IMPERSONATE_OVERRIDE
=> feat(auth): support  login as impersonate user

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/lib/posthog.tsx
1. fix the PostHogProvider to reduce API cancellations caused by children re-renders
2. dedupe thread message
=> fix(ui): dedupe thread messages in Answer Engine

clients/eclipse/feature/feature.xml, clients/eclipse/plugin/META-INF/MANIFEST.MF, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/chat/ChatView.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/git/GitProvider.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/ConnectionProvider.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/LanguageClientImpl.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/LanguageSupportProvider.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/GitDiffParams.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/GitDiffResult.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/GitRepositoryParams.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/ReadFileParams.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/ReadFileResult.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/lsp/protocol/SemanticTokensRangeResult.java
1. Added support to collect git context from the eclipse plugin, powered by org.eclipse.jgit.
2. Added support to collect declaration code snippets for code completion, requiring an activated language server connected to org.eclipse.lsp4e.
Tested in the environment with eclipse-corrosion installed, providing Rust LSP support based on org.eclipse.lsp4e.
A example completion request:
```
"segments": {
"prefix": "fn main() {\n    println!(\"Hello, world!\");\n\tp",
"suffix": "\n}\n",
"filepath": "src/main.rs",
"declarations": [
{
"filepath": "file:///home/icy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs",
"body": "/// Prints to the standard output, with a newline.\n///\n/// On all platforms, the newline is the LINE FEED character …
```
=> feat(eclipse): support to collect additional context used for code completion.

clients/tabby-agent/src/lsp/ChatEditProvider.ts, clients/tabby-agent/src/lsp/protocol.ts, clients/vscode/src/lsp/ChatFeature.ts
This PR addresses #2830.
This solves the issue where a chat stream can be undone with a single undo-redo operation.
btw, I'm thinking if I should adding undoStop after resolveEdit
=> feat(vscode):  one undo-redo step for one chat stream

clients/vscode/assets/magic-wand.svg, clients/vscode/package.json, clients/vscode/src/Commands.ts
Trying to improve user experience and address issue #2873.
Does not fully support multi-repository situations as there is no built-in feature in VSCode to get the currently selected repository.
Works perfectly in single repository scenarios.
View:
Next Steps:
Track related VSCode API support in the future.
Consider changing the icon.
=> feat(vscode): adding commit message button in source control title

clients/vscode/src/CommandPalette.ts, clients/vscode/src/Issues.ts
- Modified the command in CommandPalette.ts to pass `true` for the modal flag when calling `showHelpMessage`.
- Updated Issues.ts to always use `modal = true` and marked the `modal = false` codepath as deprecated for future removal.
=> chore(vscode): update command palette to pass modal flag correctly

ee/tabby-ui/app/search/components/search.css
=> style(search): adjust vertical alignment in list items (align to top)

ee/tabby-ui/app/search/components/search.css, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/message-markdown/style.css
=> fix(ui): add styles to MessageMarkdown component

clients/tabby-agent/src/AgentConfig.ts
Solving this issue #3002 by adding one line of code, xd
btw, the commit message for this one was automatically generated by Tabby.
=> fix(tabby-agent): remove code block delimiters from commit message

clients/tabby-agent/package.json, clients/tabby-agent/src/lsp/ChatEditProvider.ts, clients/tabby-agent/src/lsp/CodeLensProvider.ts, clients/tabby-agent/src/lsp/protocol.ts, clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/extension.ts, clients/vscode/src/inline-edit/index.ts, clients/vscode/src/lsp/CodeLensMiddleware.ts, clients/vscode/tsconfig.build.json, clients/vscode/tsconfig.json, package.json, turbo.json
cc @Sma1lboy 
https://jam.dev/c/f74c169c-f702-4e62-9ba8-27365a7a8993
=> chore(vscode): use codelens for inline edit actions / decorations

ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/email/mod.rs
split from https://github.com/TabbyML/tabby/pull/2952, support self-signed cert for smtp by reading a cert path from `TABBY_EMAIL_CERT_PATH` env.
this only supports Linux, NOT macOS, because macOS has some more pedantic requirements for self-signed cert.
We may need to dive deeper into the self-signed cert part for macOS support. ref: https://github.com/sfackler/rust-native-tls/issues/210 
fix https://github.com/TabbyML/tabby/issues/2437
=> feat(email): support self-signed smtp cert from env

website/docs/quick-start/installation/apple.md
I had another development server running on 8080 and wanted to change my TabbyML server port resolve a resulting collision.
I struggled a bit to find documentation on how to do this, landing here https://github.com/TabbyML/tabby/blob/ddbbafa17f4505f533f5fc348b87424b99e8c868/crates/tabby/src/serve.rs#L92 before I realized I could just ask for `--help` from the command.
I imagine more developers may already have something else running on 8080, so maybe this note here makes sense?
=> docs: mention server configuration options in Homebrew quick-start

ee/tabby-webserver/src/service/answer.rs
=> chore(answer): improve bullet prefix trimming in answer.rs

ee/tabby-ui/components/prompt-editor/styles.css
=> fix(prompt-editor): remove Tailwind CSS imports from styles.css

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/policy.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/user_group.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/user_group.rs
1. Server admins have full control.
2. Group admins can add users but not modify admin privileges.
3. Group admins can remove non-admin users.
4. `user_groups` is now accessible to all users.
5. user_group.membership is now sorted (admin orders first)
=> chore(webserver): tune user_groups related permissions

ee/tabby-db/src/lib.rs
For closing https://github.com/TabbyML/tabby/issues/3023
The backup file following format of `[dev-]db.backup-${date}.sqlite`
Tested locally
=> feat: backup db before running migration SQLs

clients/vscode/src/util/KeybindingParser.ts
=> fix(VSCode): fix throw error when no VSCode keybinding file

ee/tabby-ui/lib/tabby/gql.ts
https://github.com/urql-graphql/urql/blob/main/packages/core/src/utils/error.ts#L20-L25
In urql, an error with a `message` and `extensions` will not have the originalError field attached. Need to retrieve error information from the message field of the error
https://jam.dev/c/eb411cd1-73ba-4b72-a846-98c242820a1b
https://jam.dev/c/06c91c8f-efe0-4d33-b854-dbe7346e6979
=> fix(ui): handle Mutation response errors correctly

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts
Optimize error handling in the Answer Engine, especially when operating on threads not owned
https://jam.dev/c/d2daaf92-23ff-483d-a5a1-614371619fb5
https://jam.dev/c/de86b9d6-7d02-4c9d-bfd7-b4c84c528664
=> refactor(ui): optimize error handling in Answer Engine

ee/tabby-ui/components/chat/chat.tsx
=> chore(u): correct error message for expired thread

.github/workflows/release-intellij.yml, .github/workflows/test-intellij.yml, clients/intellij/build.gradle.kts
This PR create a workflow for release Tabby Plugin for IntelliJ Platform, which will be triggered on tag `intellij@*`.  
The workflow contains two jobs:
- `release-marketplace`: run `publishPlugin` task to upload zip to marketplace
- `release-github`: build and upload zip to create a github release
=> ci(intellij): add release actions.

.github/workflows/release-vscode.yml, clients/vscode/.vscodeignore, clients/vscode/package.json, clients/vscode/scripts/publish.cjs, pnpm-lock.yaml
This PR updates the release VSCode extension ci action to also publish to [ovsx](https://open-vsx.org/extension/TabbyML/vscode-tabby).
=> ci(vscode): add release to ovsx.

clients/eclipse/feature/feature.xml, clients/eclipse/plugin/META-INF/MANIFEST.MF, clients/eclipse/plugin/plugin.xml, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/commands/inlineCompletion/AcceptNextLine.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/commands/inlineCompletion/AcceptNextWord.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/editor/EditorUtils.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/IInlineCompletionService.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/InlineCompletionService.java
Changes:
- Support using `Ctrl+Right` to accept next word of completion and using `Ctrl+Tab` to accept next line of completion.
=> feat(eclipse): support partially accept inline completion.

ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/types/chat.ts
Add an `edit` button in chat side panel. When clicked, the message is deleted, but its input state will be restored in the chat input box.
https://jam.dev/c/7db17320-158f-408c-844c-1b4ffd303f5f
=> feat(ui): add support of `Edit` button in chat side panel

crates/tabby-download/src/lib.rs
=> fix(download): should not error when the model to be removed not existed

clients/tabby-agent/src/dataStore/index.ts
https://github.com/TabbyML/tabby/issues/3302
=> fix(agent): fix datastore init in vscode web extension.

ee/tabby-webserver/src/service/answer.rs
Adding debug log
Also move start line to 1 when including whole content
=> chore(answer): adding debug log when including whole content triggered in answer engine

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/src/routes/completions.rs, crates/tabby/src/services/completion.rs
fix https://github.com/TabbyML/tabby/issues/3279
test model: CodeLlama-7B
Tabby command:
```sh
tabby serve --model CodeLlama-7B --device metal --chat-model zwpaper/Qwen2.5-Coder-7B-Instruct
```
test command:
```sh
curl -X 'POST' \
'http://localhost:8080/v1/completions' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer TOKEN' \
-d '{
"language": "java",
"segments": {
"prefix": "class MathUtils {\r\n    static double clamp(double value, double min, double max) {\r\n        return math.max(min, math.min(max, value));\r\n    }\r\n\r\n    static double lerp(double a, double b, double t) {\r\n        return a + (b - a) * t;\r\n    }\r\n    \r\n    static int fibonacci(int n) {\r\n        ",
"suffix": "\r\n    }\r\n}"
}
}'
```
=> chore(completion): replace CRLF with LF for code completion LLM requests

ee/tabby-ui/components/textarea-search.tsx
When clicking button to insert a mention's prefix, ensure a space precedes the prefix if the cursor is not at the line's start and no space exists beforehand
https://jam.dev/c/1366b9dd-39d9-46b5-ae81-908b363066ef
=> fix(ui): insert mention prefix with proper spacing in Answer Engine

ee/tabby-webserver/src/service/repository/third_party.rs
this log would print hundreds of lines when I enable all repos with my GitHub token.
if no one needs this info, printing the number should be enough for us
=> chore(webserver): Print the count of repositories imported from third-party integrations instead of listing each one individually

Cargo.lock, crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/model/mod.rs, ee/tabby-schema/Cargo.toml, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/webserver.rs
- backend for https://github.com/TabbyML/tabby/issues/3239
- Both local model and HTTP model tested
notes:
1. the `CompletionService` in tabby-inference is wrapped by `CodeGeneration`, and `CodeGeneration` is then wrapped by `CompletionService` struct in tabby service, we should use the CompltionService in tabby-inference, but it's a bit tricky according to the current implementation, so I returned the `CodeGeneration` from tabby-inference, and use it as the GraphQL context.
2. when failed to connect to the model, GraphQL request will fail, so I just return the latency as the success indication, it's `milliseconds` i32.
4. following the GraphQL convention, the enum is in SCREAMING_SNAKE_CASE by default
=> feat(graphQL): add model check for chat, completion, embedding

clients/tabby-agent/src/chat/index.ts, clients/tabby-agent/src/codeCompletion/index.ts, clients/tabby-agent/src/protocol.ts, clients/vscode/src/lsp/ChatFeature.ts
This PR fixes the registration of the dynamic features.   
The bug with the status bar item loading indicator not functioning properly is caused by the inline completion provider being mistakenly registered twice. This issue should be addressed by this PR.
=> fix(agent&vscode): fix dynamic features registration.

crates/tabby-common/src/config.rs
part of the ticket(https://github.com/TabbyML/tabby/issues/3097)
in toml config file, validate `model_name` belong to `supported_models` field.
- with config.toml
```
[model.completion.http]
kind = "llama.cpp/completion"
api_endpoint = "http://localhost:8888"
prompt_template = "<PRE> {prefix} <SUF>{suffix} <MID>"  # Example prompt template for the CodeLlama model series.
supported_models = ["wsxiaoys/StarCoder-1B"]
model_name = "wsxiaoys/StarCoder-1B"
[model.chat.http]
kind = "openai/chat"
api_endpoint = "http://localhost:8888"
supported_models = ["Qwen2-1.5B-Instruct"]
model_name = "Qwen2-1.5B-Instruct"
```
test passed.
- With 
```
[model.completion.http]
kind = "llama.cpp/completion"
api_endpoint = "http://localhost:8888"
prompt_template = "<PRE> {prefix} <SUF>{suffix} <MID>"  # Example …
```
=> chore(config): validate supported models

ee/tabby-ui/app/(dashboard)/components/main-content.tsx, ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/(dashboard)/layout.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/nav-bar.tsx, ee/tabby-ui/app/(dashboard)/settings/subscription/components/subscription.tsx, ee/tabby-ui/components/header.tsx, ee/tabby-ui/components/license-banner.tsx, ee/tabby-ui/components/license-guard.tsx, ee/tabby-ui/components/providers.tsx, ee/tabby-ui/lib/hooks/use-license.ts
The following two scenarios will display an invalid license prompt, with the messages shown in order. If the first is matched, only that one will be displayed.
1. License insufficient
2. License expired
3. Seats exceeded
----
----
----
=> feat(ui): display alerts for invalid licenses

clients/tabby-agent/src/chat/global.ts, clients/tabby-agent/src/chat/inlineEdit.ts, clients/tabby-agent/src/chat/smartApply.ts, clients/vscode/src/chat/WebviewHelper.ts
Fixing the issue where inline-editing cannot be cancelled when initiated with smart apply
https://github.com/user-attachments/assets/9aca4d85-19f5-41ce-9914-20d74d5df349
=> fix(agent&vscode): use shared mutexAbortController for inlineEdit and smartApply

clients/vscode/src/extension.ts
Fix LSP client registration when opening a remote repository in [vscode.dev](https://vscode.dev/) in the browser.
=> fix(vscode): add support for scheme `vscode-vfs` for web extension.

.github/workflows/docker.yml
fix docker build: https://github.com/TabbyML/tabby/actions/runs/11695005630
=> ci(docker): update docker release runner to buildjet-2vcpu-ubuntu-2204

ee/tabby-schema/src/schema/license.rs, ee/tabby-ui/app/(dashboard)/settings/subscription/components/license-table.tsx
=> chore(license): set team license seat limit

ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread/types.rs
after:
maybe we could also show the message to report the details? @liangfung
=> fix(webserver): forbid empty content message update

website/docs/references/models-http-api/jan.ai.md
janAI [completion](https://cortex.so/docs/capabilities/text-generation) and [embedding](https://cortex.so/docs/capabilities/embeddings) APIs are both under construction, and not yet supported by Jan now
=> docs(models-http-api): add jan.ai chat example

clients/eclipse/feature/feature.xml, clients/eclipse/plugin/META-INF/MANIFEST.MF, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/renderer/InlineCompletionItemRenderer.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/renderer/InlineCompletionItemTextPainter2.java
As using `setLineVerticalIndent` to modify the line vertical indent may conflict with CodeLens, causing a ghost text overlay bug, this PR adds the implementation `InlineCompletionItemTextPainter2`, which uses `setLineSpacingProvider` to modify the line spacing to make space for the under-line inline completion text as a workaround.  
There is a known issue to use `setLineSpacingProvider` when the editor is in word wrap mode: triggering an inline completion at a wrapped line causes the line spacing to appear irregular and results in incorrect line number display. However, these issues only occur while the inline completion item is visible and are resolved once the inline completion item is dismissed. Given this behavior, it may be considered an acceptable workaround for now.
=> fix(eclipse): use lineSpacing insteadof lineVerticalIndent for ghost text rendering.

ee/tabby-webserver/src/service/answer.rs
after:
may need your help @liangfung, looks like it's different error handling from the GraphQL API
=> fix(answer): return error when request to llm failed

crates/http-api-bindings/src/completion/llama.rs, crates/http-api-bindings/src/embedding/llama.rs
Test Model Health pass:
VSCode extension completion works:
=> fix(models-http-api): use completion and embedding endpoint for llama.cpp

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/languageSupport/KotlinLanguageSupportProvider.kt, clients/intellij/src/main/resources/META-INF/plugin-kotlin.xml, clients/intellij/src/main/resources/META-INF/plugin.xml
fix https://github.com/TabbyML/tabby/issues/3421
Related to #3394 
- Added a language support implementaion based on `org.jetbrains.kotlin`(built-in plugin in IDEA and Android Studio)
=> feat(intellij): add kotlin language support for collecting declaration.

clients/vscode/src/Commands.ts, clients/vscode/src/InlineCompletionProvider.ts
still working 
https://github.com/user-attachments/assets/0f1c29ea-5e5d-492a-8e08-44a646a0c473
fix https://github.com/TabbyML/tabby/issues/2965
=> feat(vscode): adding auto-import during accept inline completion item

.github/workflows/release.yml, ci/package-win.sh
Tested on: https://github.com/zwpaper/tabby/releases/tag/v0.78.0
=> ci(release): release filename without version

clients/tabby-agent/src/http/proxy.ts, clients/vscode/src/Config.ts
- Setting 
```
"tabby.settings.advanced": {
"useVSCodeProxy": false
},
```
, `proxy.url` will be ""(empty string).
- 
```
"tabby.settings.advanced": {
"useVSCodeProxy": true
},
```
, `proxy.url` will be "http://localhost:9000".
close #3360
=> chore(vscode): add useVSCodeProxy option to control whether to use Vscode Proxy

clients/tabby-agent/src/codeCompletion/postprocess/index.ts, clients/tabby-agent/src/codeCompletion/postprocess/normalizeIndentation.test.ts, clients/tabby-agent/src/codeCompletion/postprocess/normalizeIndentation.ts
#3263
Fixing wrong indent in inline completion predict solution
https://github.com/user-attachments/assets/34580f0a-ab4b-4c08-8101-ba28f2687701
Only first line has extra spaces:
exactly one extra space in the line indent
exactly one extra space in the line indent
Using whether the current indent is even as the judgment basis. If it's even, the prediction doesn't need any extra spaces and the prediction context will be processed accordingly.
Some users might use odd indent size
This approach is simple and doesn't require adding additional LSP or obtaining the best indent through client operations.
Due to some concern this post-processing not going to fix this situation
All lines in prediction have extra spaces:
=> fix(agent): normalize indentation in code completion postprocess

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/widgets/ChatToolWindowFactory.kt
Related to #3458
Added a help message when failing to create the chat panel, usually caused by the lack of JCEF support in Android Studio.
=> fix(intellij): add help message when failed to create chat panel.

ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/answer/testutils/mod.rs, ee/tabby-webserver/src/service/thread.rs
=> fix(answer): fix panic when failed to gen relevant questions

Cargo.lock, crates/http-api-bindings/Cargo.toml, crates/http-api-bindings/src/embedding/llama.rs, crates/http-api-bindings/src/embedding/mod.rs, crates/http-api-bindings/src/embedding/openai.rs, crates/http-api-bindings/src/embedding/rate_limit.rs, crates/http-api-bindings/src/embedding/voyage.rs, crates/ollama-api-bindings/src/embedding.rs, crates/tabby-common/src/config.rs
=> feat(models-http-api): add rate limit support for embedding

Cargo.lock, crates/http-api-bindings/Cargo.toml, crates/http-api-bindings/src/completion/openai.rs
we can know what is the error when completion failed
```console
2024-11-26T17:46:53.617182Z  WARN http_api_bindings::completion::openai: crates/http-api-bindings/src/completion/openai.rs:107: Error in completion event source: 404 Not Found, {  "error": {    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",    "type": "invalid_request_error",    "param": "model",    "code": null  }}
```
=> chore: log openai completion error

.github/workflows/release.yml
https://github.com/zwpaper/tabby/releases/tag/v0.80.0
=> ci(release): fix linux-vulkan not released

clients/vscode/src/chat/fileContext.ts
Depends on #3504 
Now we can navigate to specific channel by click the reference item on chat panel
https://jam.dev/c/7c970cc9-f958-4725-ac3f-585a1e7615d1
=> feat(VSCode): navigate to format `output` log channel

ee/tabby-webserver/src/service/background_job/third_party_integration.rs
=> fix(index): fix gitlab third party integration by skip indexing gitlab pulls

ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread/inputs.rs
there are two changes in this PR:
1. add `validate(nested)` to enable validation on ThreadRunOptionsInput
2. show a detailed error message when ValidationError is a struct
for `2.`, the validationError had impl Display, so we could use it directly,
for the original code, it can only show error message when the error is a `Field` inside `Struct`:
before:
after:
=> fix(webserver):  validate ThreadRunOptionsInput and return error message

crates/tabby-git/src/serve_git.rs
=> fix(codeBrowser): fix broken tree view on Windows.

clients/tabby-agent/src/codeCompletion/contexts.ts
refer to comment in `clients/tabby-agent/src/codeCompletion/contexts.ts`
cons| -> console  
completionItem: console  
insertPosition: 4  
insertSeg: ole  
currSeg: cons
We should not continue processing the autocomplete item if the `completionItem` is "console" but the user typed "cnt" as `currSeg`. Make sure that the characters typed by the user that trigger the completionItem match the completionItem’s prefix.
=> fix(tabby-agent): correctly handle auto widget completion Item

ee/tabby-ui/components/message-markdown/code.tsx, ee/tabby-ui/components/message-markdown/style.css
=> fix(ui): fix the style of inline code in Answer Engine

ee/tabby-db/src/lib.rs, ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/access_policy.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/auth/testutils.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/thread.rs, ee/tabby-webserver/src/webserver.rs
part of https://github.com/TabbyML/tabby/pull/3503
=> feat(graphQL): add author_email in pull/issue thread attachment

ee/tabby-webserver/src/service/background_job/third_party_integration/error.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs
before:
```
2024-12-11T11:10:39.147465Z DEBUG tabby_webserver::service::background_job::third_party_integration::pulls: ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs:61: Failed to fetch user profile for 0jdxt: JSON Error in name: invalid type: null, expected a string at line 1 column 906
Found at    0: std::backtrace_rs::backtrace::libunwind::trace
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
1: std::backtrace_rs::backtrace::trace_unsynchronized
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2: std::backtrace::Backtrace::create
at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/backtrace.rs:331:13
3: …
```
=> chore: reduce unnecessary GitHub pull backtrace log

Cargo.lock, ee/tabby-webserver/Cargo.toml
before:
```
2024-12-12T02:03:17.881155Z DEBUG tabby_webserver::service::background_job::third_party_integration::pulls: ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs:61: Failed to fetch user profile for Un1q32: Json error: name: invalid type: null, expected a string at line 1 column 920
```
after:
no error log
=> chore: upgrade octocrab to resolve JSON errors when fetching GitHub author

.changes/unreleased/Fixed and Improvements-20241212-095738.yaml, crates/tabby-index/src/indexer_tests.rs, crates/tabby-index/src/structured_doc/public.rs, ee/tabby-schema/src/schema/integration.rs, ee/tabby-schema/src/schema/repository/third_party.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/issues.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs, ee/tabby-webserver/src/service/integration.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/third_party.rs
1. main branch introduces a feature to retrieve the pull request author's email from GitHub, which requires an additional profile API call. This results in an extra 4 minutes of processing time compared to r0.21.  
2. This pull request refactors the pull request synchronization process into pre-sync and sync stages. It skips unnecessary calls for author details or diffs when no updates are required, reducing subsequent indexing time by over 6 minutes.
---
1. first indexing: 
3. second indexing: 
1. first indexing:
2. second indexing: 
1. first indexing:
2. second indexing:
=> refactor(structured_doc): split pre-sync stage to optimize pull request indexing speed

ee/tabby-db/src/notifications.rs, ee/tabby-webserver/src/service/notification.rs
1. admin list all
2. user list users
3. admin mark all read
4. User notifications remain unread
5. Users notifications read
=> fix(graphQL): fix wrong read status when list notifications

website/docs/quick-start/installation/windows/index.mdx
Command must run as Administrator, or it fails:
```powershell
C:\tabby_x86_64-windows-msvc-cuda122>.\tabby.exe serve --model Qwen2.5-Coder-1.5B --chat-model Qwen2-1.5B-Instruct --device cuda
⠹     0.162 s   Starting...←[2m2024-12-14T02:45:52.034764Z←[0m ←[33m WARN←[0m ←[2mllama_cpp_server::supervisor←[0m←[2m:←[0m ←[2mcrates\llama-cpp-server\src\supervisor.rs←[0m←[2m:←[0m←[2m98:←[0m llama-server <embedding> exited with status code -1073741515, args: `Command { std: "C:\\tabby_x86_64-windows-msvc-cuda122\\llama-server.exe" "-m" "C:\\Users\\user1\\.tabby\\models\\TabbyML\\Nomic-Embed-Text\\ggml\\model-00001-of-00001.gguf" "--cont-batching" "--port" "30888" "-np" "1" "--log-disable" "--ctx-size" "4096" "-ngl" "9999" "--embedding" "--ubatch-size" "4096", kill_on_drop: true }`
⠴     1.211 s …
```
=> docs(windows): update quickstart section

crates/tabby-download/src/lib.rs, crates/tabby/src/download.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/model/mod.rs
chat:
completion:
fix https://github.com/TabbyML/tabby/issues/3442
=> feat: validate model capability before download

ee/tabby-db/schema/schema.sql, ee/tabby-db/schema/schema.svg, ee/tabby-db/src/notifications.rs, ee/tabby-webserver/src/service/notification.rs
if you try to mark a notification as read when it was marked as read before.
Before:
After:
=> fix(graphQL): fix error when retry mark notifications read

ee/tabby-schema/src/schema/license.rs, ee/tabby-webserver/src/service/background_job/license_check.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/mod.rs
- Added `expire_in_days` method to `LicenseInfo` to calculate the number of days until license expiration.
- Introduced `LicenseCheckJob` module for handling license checks.
- Integrated `LicenseCheckJob` into the daily cron job schedule.
=> feat(license): add license expiration check and daily cron job

Cargo.lock, Cargo.toml, crates/http-api-bindings/src/embedding/openai.rs, crates/http-api-bindings/src/rate_limit.rs, crates/tabby-index/src/code/mod.rs, crates/tabby/Cargo.toml, crates/tabby/src/main.rs, crates/tabby/src/otel.rs, crates/tabby/src/serve.rs
- add support for openTelemetry
- embedding instrumented
user can use the following command to enable openTelemetry support:
```bash
tabby --otlp-endpoint "http://192.168.100.3:4317" serve --model Qwen2.5-Coder-0.5B --device metal --chat-model Qwen2.5-Coder-0.5B-Instruct
```
- Recent 100 trace
- rate limited embedding request
- embedding endpoint with corpus=code
=> feat: add support for openTelemetry

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenOnlineDocumentation.kt, clients/tabby-agent/README.md, clients/tabby-agent/src/http/tabbyApiClient.ts, clients/vscode/README.md, clients/vscode/assets/walkthroughs/setupServer.md, clients/vscode/package.json, clients/vscode/src/commands/index.ts
Updated links in tabby plugins:
- Tabby Homepage: from `https://tabby.tabbyml.com` to `https://www.tabbyml.com`
- Online Docs:  from `https://tabby.tabbyml.com` to `https://tabby.tabbyml.com/docs`
=> chore(clients): update tabby home link.

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx, ee/tabby-ui/components/error-view.tsx, ee/tabby-ui/lib/hooks/use-health.tsx, ee/tabby-ui/lib/hooks/use-workers.ts
=> fix(ui): handle rate limit error

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/src/services/health.rs
- fix #3042 segmentation error due to a sysinfo crate [bug](https://github.com/GuillaumeGomez/sysinfo/issues/1052) with 0.29.1 to 0.29.9
=> build(deps): upgrade sysinfo to version 0.33.0

crates/tabby-common/src/api/code.rs, crates/tabby-common/src/index/code/mod.rs, crates/tabby-common/src/index/mod.rs, crates/tabby-index/src/code/index.rs, crates/tabby-index/src/code/intelligence.rs, crates/tabby-index/src/code/mod.rs, crates/tabby-index/src/code/repository.rs, crates/tabby-index/src/code/types.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/indexer_tests.rs, crates/tabby/src/services/code.rs, ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/answer/testutils/mod.rs
this PR does:
1. check code indexes, and reindex if no commit field
2. index code with commit as a field
3. return commit in codeAttachment
commit in response:
=> feat(index): add commit to CodeSearchDocument

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/WebviewHelper.ts, clients/vscode/src/chat/fileContext.ts, clients/vscode/src/chat/utils.ts, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/code-references.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/types/chat.ts, ee/tabby-ui/lib/utils/index.ts
=> feat(ui): optimize entire file context in sidepanel display

ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-ui/lib/types/chat.ts, ee/tabby-ui/lib/utils/index.ts
https://jam.dev/c/17d4763d-c78b-48db-8bb6-7252b4da2c93
=> feat(ui): add commit hash to attachmentCode for accurate redirection

ee/tabby-ui/app/(dashboard)/components/dashboard-main.tsx, ee/tabby-ui/app/(dashboard)/profile/components/change-name.tsx, ee/tabby-ui/app/(dashboard)/profile/components/change-password.tsx, ee/tabby-ui/app/(dashboard)/profile/components/email.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/job-trigger.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/custom-doc.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx
1. align job information view
2. add horizontal scroll to the context providers table
https://jam.dev/c/3f5bc57c-d014-4ff1-8b8d-d98bd83c7832
=> fix(ui): align job info view in context providers

clients/tabby-agent/src/http/tabbyApiClient.ts, clients/tabby-agent/src/protocol.ts, clients/tabby-agent/src/status.ts, clients/tabby-agent/src/utils/error.ts, clients/vscode/src/StatusBarItem.ts, clients/vscode/src/commands/commandPalette.ts
https://jam.dev/c/feb4b985-1235-460f-bb96-0a18c6d66776
=> feat(vscode): show status of rate limited

crates/tabby-index/src/code/mod.rs
The condition for setting the `CHUNK_START_LINE` attribute was incorrect. It now checks if the text length is not equal to the body length, ensuring the attribute is set only when necessary.
=> fix(code): correct condition for setting CHUNK_START_LINE attribute

ee/tabby-ui/app/chat/page.css, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/repo-select.tsx
=> fix(ui): set the color of popover in Chat side panel properly

ee/tabby-db/src/job_runs.rs, ee/tabby-db/src/user_events.rs, ee/tabby-webserver/src/service/background_job/db.rs, ee/tabby-webserver/src/service/background_job/mod.rs
…last three months
tested locally:
and added tests codes
=> feat(job): db job should retain job_runs and user_events for only last three months

ee/tabby-webserver/src/service/answer.rs
- Updated debug log message in `answer.rs` to clarify the content being logged and the number of matched documents.
- Improved debug log message in `merge_code_snippets` to make it more descriptive and easier to understand.
=> refactor(answer): improve debug log messages for clarity and readability

crates/tabby-common/src/index/mod.rs, crates/tabby/src/serve.rs
- Removed deprecated `webserver` flag and related warning in `serve.rs`.
- Removed deprecated `WEB` corpus constant in `index/mod.rs`.
=> refactor: remove deprecated code

website/docs/references/models-http-api/perplexity.md
=> docs: adding Perplexity AI use case document in tabby-docs

clients/vscode/CONTRIBUTING.md, clients/vscode/package.json, clients/vscode/src/commands/index.ts, clients/vscode/src/inline-edit/index.ts, clients/vscode/tsup.config.ts
- add inline edit on context menu
- fix VSCode extension build problem on windows
- update VSCode extension contributing doc
demo : 
https://jam.dev/c/cb8d3d3f-5d8e-4edd-bd7d-91d5a697bc87
screenshot:
issue #3423
=> feat(vscode): add inline edit on context menu

crates/http-api-bindings/src/chat/mod.rs, crates/http-api-bindings/src/embedding/azure.rs, crates/http-api-bindings/src/embedding/mod.rs, crates/http-api-bindings/src/lib.rs, crates/tabby-common/src/config.rs, crates/tabby-inference/src/chat.rs
Added HTTP API support for Azure OpenAI Service, enabling seamless integration with all OpenAI API models available through Azure AI Service, including:
- GPT series chat models
- Embedding models 
add the following configuration to your `~/.tabby/config.toml` to get started:
```toml
[model.chat.http]
kind = "azure/chat"
model_name = "gpt-4o-mini"
api_endpoint = "https://xxx.openai.azure.com"  
api_key = "your-api-key"
[model.embedding.http]
kind = "azure/embedding"
model_name = "text-embedding-3-small"
api_endpoint = "https://xxx.openai.azure.com"  
api_key = "your-api-key"
```
- #3668
=> feat(backend): adding Azure AI Foundry OpenAPI support

website/docs/references/models-http-api/openai.md
=> docs(models): emphasize the deprecation of OpenAI completion API

website/docs/references/models-http-api/amazon-bedrock.md
=> docs(amazon-bedrock): add Amazon Bedrock documentation for HTTP API use case

clients/tabby-chat-panel/src/index.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat.tsx
In VSCode, when a user drags the chat panel to another location, the webview is reloaded. To restore the chat state, this PR adds the `fetchSessionState` and `storeSessionState` interfaces. These interfaces store the chat state and reload it when the webview is reloaded.
=> feat(chat-panel): save chat state and reload state when webview reloading

ee/tabby-webserver/src/service/background_job/db.rs, ee/tabby-webserver/src/service/background_job/hourly.rs, ee/tabby-webserver/src/service/background_job/license_check.rs
since we will sent notification and show logs, it would be reasonable to fix it now
=> chore: fix typo

ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/credential-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/ldap-credential-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/sso-type-radio.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/detail/[oauth-provider]/components/oauth-credential-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/detail/ldap/components/ldap-credential-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/new/component/new-page.tsx, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/5287d055-e675-4f5f-8f47-9f77dbd01501
=> chore(ui): add prevalidate to sso creation

ee/tabby-ui/app/(dashboard)/profile/components/change-name.tsx, ee/tabby-ui/app/(dashboard)/profile/components/profile-card.tsx, ee/tabby-ui/app/(dashboard)/profile/components/profile.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-ui/lib/hooks/use-me.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/f959d8e1-77a4-4563-803d-42fa528071dc
=> feat(ui): prevent SSO users from updating their name & password

ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/ldap-credential-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-form.tsx
=> chore(ui): adjust SSO credential form styling

clients/vscode/package.json
Update default configuration for endpoint:  
**From:** `""` (Empty string, which uses the configuration from the agent config file)  
**To:** `"http://localhost:8080"` (Endpoint and token will be saved in VSCode settings)
This change improves the user experience for users who start the Tabby server at `localhost:8080`, then launch VSCode and install the Tabby extension. The status bar will prompt the user to update the token.
**Before the change:**  `Update token` opens the agent config file.
**After the change:**   `Update token` shows an input prompt for the token, which is then saved in VSCode settings.
=> fix(vscode): update the default config for endpoint.

clients/eclipse/feature/feature.xml, clients/eclipse/plugin/META-INF/MANIFEST.MF, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/Version.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/chat/ChatViewUtils.java
=> fix(eclipse): skip version check for non-semantic version string.

clients/vscode/src/chat/webview.ts, clients/vscode/src/findFiles.ts
We want to use the findFiles2 API, but it is still in the proposed state.
Therefore, we implement a findFiles function here that can use the following rules in the exclude pattern:
1. .gitignore files
2. Settings from `files.exclude` and `search.exclude`
See https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.findFiles2.d.ts
=> fix(vscode): exclude ignored files for chat panel at file list.

crates/aim-downloader/src/https.rs
cc @wsxiaoys
This PR is to fix the 401 code encountered in #3771, and I also couldn't download all the models during testing
=> fix(download): remove basic_auth header when password not exist

.github/workflows/release.yml
v3 was deprecated and disabled in jan. 30: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
CI failed: https://github.com/TabbyML/tabby/actions/runs/13066122638/job/36458693862
upgrade test CI: https://github.com/zwpaper/tabby/actions/runs/13066275263/job/36459100515
=> chore(ci): use upload and download artifact v4

website/docs/references/models-http-api/lm-studio.md
=> docs(lm-studio): add documentation for Integration with LM Studio OpenAI compatible APIs

Cargo.lock, Cargo.toml, crates/tabby-download/Cargo.toml
aim-downloader@0.25.0-dev.0
hash-ids@0.25.0-dev.0
http-api-bindings@0.25.0-dev.0
llama-cpp-server@0.25.0-dev.0
ollama-api-bindings@0.25.0-dev.0
sqlx-migrate-validate@0.25.0-dev.0
tabby@0.25.0-dev.0
tabby-common@0.25.0-dev.0
tabby-crawler@0.25.0-dev.0
tabby-db@0.25.0-dev.0
tabby-db-macros@0.25.0-dev.0
tabby-download@0.25.0-dev.0
tabby-git@0.25.0-dev.0
tabby-index@0.25.0-dev.0
tabby-index-cli@0.25.0-dev.0
tabby-inference@0.25.0-dev.0
tabby-schema@0.25.0-dev.0
tabby-webserver@0.25.0-dev.0
Generated by cargo-workspaces
=> chore: bump server to 0.25.0-dev.0

clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/index.ts, clients/tabby-chat-panel/src/react.ts, clients/tabby-threads/source/targets/target.ts, clients/tabby-threads/source/types.ts
The createServer and createClient of chatpanel will exchange methods between both parties at the beginning, so the methods that are not supported will return undefined
=> feat(chat-panel): exchange methods during createServer and createClient by request built-in method in Thread

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-index/Cargo.toml, crates/tabby-index/queries/gdscript.scm, crates/tabby-index/src/code/languages.rs, website/docs/references/programming-languages.md
There seems to be an annoying dependency problem appeared, [tree-sitter-gdscript](https://crates.io/crates/tree-sitter-gdscript) only release a crate that uses `LanguageFn` supported above [v0.23.0](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.23.0) of tree-sitter. The older version however depends on ~0.20.10, which is incompatible with Tabby. I forked [tree-sitter-gdscript](https://github.com/faceCutWall/tree-sitter-gdscript) and bumped tree-sitter to v0.22.6 to make it work. The functionality has been tested, but I'm not sure if it's okay to do so. Looking forward to more suggestions :)
=> feat(index): add GDScript language support.

clients/tabby-agent/src/chat/inlineEdit.ts, clients/tabby-agent/src/chat/utils.ts, clients/tabby-agent/src/config/default.ts, clients/tabby-agent/src/config/type.d.ts, clients/tabby-agent/src/protocol.ts, clients/vscode/.mocha.env.js, clients/vscode/.mocharc.js, clients/vscode/package.json, clients/vscode/src/chat/utils.ts, clients/vscode/src/chat/webview.ts, clients/vscode/src/findFiles.ts, clients/vscode/src/inline-edit/index.ts, clients/vscode/src/inline-edit/quickPick.ts, clients/vscode/src/inline-edit/util.test.ts, clients/vscode/src/inline-edit/util.ts, pnpm-lock.yaml
- Support attach file context to inline edit #2964 
- demo: https://jam.dev/c/41e820ac-9f92-4736-b113-e21f8f9a7d39
=> feat(vscode): support attach file context to inline edit

crates/tabby-git/src/file_search.rs, crates/tabby-git/src/lib.rs, ee/tabby-schema/src/schema/repository/mod.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/prompt_tools.rs
Using BFS to search files instead of DFS preorder traversal. Also adding an is_clipped prompt when the list of files exceeds the limit of files.
=> feat(file-search): implement breadth-first search for file listing

ee/tabby-db/src/threads.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/page.rs, ee/tabby-webserver/src/service/thread.rs
Even no attachment matched, the codeSourceId is saved:
=> chore(thread): always return save codeSourceId if it contains codeQuery

clients/vscode/src/chat/utils.ts, clients/vscode/src/chat/webview.ts
Because lookUpSymbol will only exist in the case of gitUrl existing and gitUrl not existing. When gitUrl does not exist, other situations default to looking for the current rootWorkspaceUri + filepath. filepath as relative path.
=> feat(chat): refactor URI resolution in lookUpSymbol

ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/types/chat.ts
- Remove endline field
- Remove baseDir and instead make all URIs use relative paths when looking up symbols
=> refactor(chat): simplify attachment client code structure

ee/tabby-ui/app/search/components/reading-code-step.tsx
Correct the badge styling for client code in Answer Engine. When hovering over the client code badge, the line number should not be highlighted.
https://jam.dev/c/9c41f338-6d8d-4589-b4a4-dfcc5010d4fe
https://jam.dev/c/3c6a0d84-d62f-4767-a33e-f30bafe28295
=> fix(ui): correct code badge styling in reading code step

clients/tabby-agent/src/codeCompletion/postprocess/normalizeIndentation.ts
=> fix(codeCompletion): normalize indentation handling for lines with tabs

clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/preferences/MainPreferencesPage.java, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/settings/SettingsPanel.kt
Slightly improves a user-facing string displayed in the extension settings in both IntelliJ and Eclipse.
=> fix(intellj,eclipse): correct typo in IntelliJ and Eclipse extension settings panels

crates/tabby-index-cli/src/commands/bench.rs, ee/tabby-webserver/src/ldap.rs, ee/tabby-webserver/src/service/repository/mod.rs
OneLevel does not do a subtree search which is required for effective use of directory server.  See [ldap3 docs](https://docs.rs/ldap3/latest/ldap3/#synchronous-search).
=> fix(webserver): changed ldap search from onelevel to subtree

crates/tabby-crawler/src/lib.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs
ref: https://github.com/TabbyML/tabby/issues/3901
before:
Job Suc even no katana found:
After:
=> fix(background_job): expose crawler job error

ee/tabby-ui/app/chat/components/history-view.tsx, ee/tabby-ui/components/chat/thread-item.tsx
1. fix text overflow
2. adjust spacing and element structure
=> fix(ui): refine chat history view styles

clients/tabby-agent/src/http/tabbyApiClient.ts
adding heartbeat per min when server health ready
=> feat(agent): adding heartbeat per min when server ready

.github/workflows/autofix-rust.yml, .github/workflows/bloat.yml, .github/workflows/release.yml, .github/workflows/test-rust.yml, ci/prepare_build_environment.sh
Test CI run: https://github.com/TabbyML/tabby/actions/runs/13689471133
=> chore: upgrade cache and install vulkan action to fix cache v2 deprecated

.github/workflows/release.yml
fix rustup occasionally failed: https://github.com/TabbyML/tabby/actions/runs/13762221751/job/38482680186
test: https://github.com/zwpaper/tabby/actions/runs/13765096184
ref: https://github.com/rust-lang/rust-analyzer/blob/be4899335135db60f0b12cb0d802c7fc5872aab9/.github/workflows/ci.yaml#L54
=> ci: use the built-in rustup in action image for windows

crates/tabby-crawler/src/lib.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs
Fixed the output not correct, also adding attempt to llms-full.txt when the url endwith llms.txt
start with base url: https://docs.verdn.com/
start with base url: https://docs.verdn.com/llms-full.txt
=> fix(crawler): update URL handling for llms-full.txt 

ee/tabby-ui/app/pages/components/new-page-form.tsx, ee/tabby-ui/app/pages/components/page-content.tsx, ee/tabby-ui/app/pages/components/page-context.ts, ee/tabby-ui/app/pages/components/page-main.tsx, ee/tabby-ui/app/pages/components/section-content.tsx, ee/tabby-ui/app/pages/lib/query.ts, ee/tabby-ui/app/pages/lib/utils.ts, ee/tabby-ui/app/pages/types.ts, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/components/code-range-label.tsx, ee/tabby-ui/components/textarea-search/repo-select.tsx, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-ui/lib/types/chat.ts
https://jam.dev/c/c44e70ef-f295-4791-812d-b51021eac910
=> feat(ui): support query code when creating new pages

Cargo.lock, Cargo.toml, crates/tabby-download/Cargo.toml
aim-downloader@0.27.0-dev.0
hash-ids@0.27.0-dev.0
http-api-bindings@0.27.0-dev.0
llama-cpp-server@0.27.0-dev.0
ollama-api-bindings@0.27.0-dev.0
sqlx-migrate-validate@0.27.0-dev.0
tabby@0.27.0-dev.0
tabby-common@0.27.0-dev.0
tabby-crawler@0.27.0-dev.0
tabby-db@0.27.0-dev.0
tabby-db-macros@0.27.0-dev.0
tabby-download@0.27.0-dev.0
tabby-git@0.27.0-dev.0
tabby-index@0.27.0-dev.0
tabby-index-cli@0.27.0-dev.0
tabby-inference@0.27.0-dev.0
tabby-schema@0.27.0-dev.0
tabby-webserver@0.27.0-dev.0
Generated by cargo-workspaces
=> chore: release 0.27.0-dev.0

.changes/unreleased/Features-20250318-131219.yaml, ee/tabby-ui/app/(dashboard)/settings/general/components/security-form.tsx, ee/tabby-ui/app/auth/signin/components/signin-section.tsx, ee/tabby-ui/lib/hooks/use-server-info.ts
If password login is hidden and LDAP is configured, then only LDAP login is displayed.
When password login is disabled in settings, it can be forcibly displayed by using the search parameter `passwordSignIn=true`.
=> feat(admin): add security option to hide password login in frontend

clients/tabby-chat-panel/src/client.ts
Adding ListFileItem as optional for client-side backward compatibility. If there is no type passed in previous client versions, it will remain undefined as workspace
=> feat(client): add optional file type property to ListFileItem interface

crates/tabby-inference/src/chat.rs
The Mistral API does not accept the `stream_options` field. When an API request contains this field, we cannot get any response.
Therefore, we have to remove the `stream_options` field whenever it is passed through an API request. The Mistral API by default includes usage information at the end of the stream.
=> fix(chat): set stream_options to None for mistral/chat request

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/ConfigurationSync.kt
#4061 
Changes Made:
Added methods getProxyUrl and getProxyAuthorization to retrieve the proxy URL and authorization from IntelliJ's global proxy settings.
Updated buildClientProvidedConfig to include the proxy settings in the ClientProvidedConfig.ProxyConfig.
=> feat(intellij): use ide proxy settings for tabby agent config

ee/tabby-ui/lib/utils/chat.ts, ee/tabby-ui/lib/utils/markdown.ts, ee/tabby-ui/test/utils/markdown.test.ts
- Updated `formatObjectToMarkdownBlock` to accept options for adding prefix and suffix newlines.
- Introduced `shouldAddPrefixNewline` and `shouldAddSuffixNewline` utility functions to determine newline requirements based on context.
- Modified `processingPlaceholder` to utilize the new formatting options for improved message processing.
- Added comprehensive tests for the new functions and updated existing tests to cover the new behavior.
https://jam.dev/c/d8e59473-9486-481c-88d8-10c90f05c0ec
https://jam.dev/c/8c877069-1e83-4651-8c72-5141762396a4
=> feat(markdown): enhance formatting functions with newline options

ci/prepare_build_environment.sh
city-fan.org is recommended from curl official release,
The rpm on city-fan will clean up the old release archives, so we have to get the latest release before downloading them.
ci error: https://github.com/TabbyML/tabby/actions/runs/14313345524/job/40123162578
fixed ci test: https://github.com/zwpaper/tabby/actions/runs/14324472892/job/40147398057
=> ci: fetch latest curl version before downloading it

ee/tabby-ui/components/chat/form-editor/mention.tsx, ee/tabby-ui/components/chat/form-editor/utils.tsx, ee/tabby-ui/components/chat/git/utils.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/constants/regex.ts, ee/tabby-ui/lib/utils/chat.ts, ee/tabby-ui/lib/utils/markdown.ts, ee/tabby-ui/lib/utils/markdown/remark-codeblock-to-placeholder.ts, ee/tabby-ui/lib/utils/markdown/remark-placeholder-parser.ts, ee/tabby-ui/package.json, ee/tabby-ui/test/utils/remark-codeblock-to-placeholder.test.ts, ee/tabby-ui/test/utils/remark-placeholder-parser.test.ts, pnpm-lock.yaml
- Introduced new remark plugins for parsing and transforming placeholders in markdown, allowing for syntax like [[source:type:id]].
- Added functionality to convert code blocks with labels into placeholder nodes, improving markdown processing capabilities.
- Refactored existing markdown utilities to integrate new placeholder features and streamline processing.
- Added comprehensive tests for new functionality, ensuring robust handling of various placeholder types and code block metadata.
This update enhances the flexibility and usability of markdown processing within the application.
=> feat(markdown): enhance placeholder handling and code block processing

.github/workflows/autofix-rust.yml, .github/workflows/bloat.yml, .github/workflows/release.yml, .github/workflows/test-rust.yml
CI: https://github.com/TabbyML/tabby/actions/runs/14338320249/job/40191048753
=> ci: upgrade mozilla-actions/sccache-action to 0.0.9

clients/vscode/src/commands/index.ts
https://jam.dev/c/bea16d25-7e47-4b72-bb3b-d9adb7cf72c9
cc @wsxiaoys
=> chore(VSCode): quick import should not trigger when there are multiple quick fix import actions in code completion

ee/tabby-ui/app/pages/components/section-content.tsx
=> fix(ui): ensure full width for the pull source card

ee/tabby-db/src/pages.rs, ee/tabby-webserver/src/service/page.rs
1. since `convert page`, `new page`, `new sections` need different code query prompt, only pass the code_source_id to page_run
2. use the same source_id with code_query when doc_query is empty but code_query has value(the convert page case)
3. always return doc/code query event with debug data even when no doc/code matched
=> fix(page): add doc query when convert thread to page

clients/tabby-agent/src/config/default.test.ts, clients/tabby-agent/src/config/default.ts
Sometimes the commit message with suffix markdown codeblock syntax
prevent it happen during regex level
=> chore: optimize generate commit message regex match

ee/tabby-ui/components/notification-box.tsx
https://jam.dev/c/ac167e26-10fb-4a98-8bbe-1140916d6c5f
=> chore(ui): mark as read when a link in a notification is clicked

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-index/Cargo.toml, crates/tabby-index/queries/scala.scm, crates/tabby-index/src/code/languages.rs, website/docs/references/programming-languages.md
This PR introduces syntax support for the Scala language. It expands the stop word list specifically for Scala and integrates syntax tree parsing via Tree-Sitter. These changes improve code analysis and facilitate more accurate completions when working with Scala source files.
Changes:
• Added Scala-specific stop words.  
• Integrated Tree-Sitter to parse Scala syntax trees.  
• Updated configuration to handle Scala language nuances.
Testing:
Tested against a range of small Scala code examples to ensure robust parsing and better code insights. No regressions detected.  
Thank you for reviewing this contribution!
=> feat(language): Add Scala support with tree-sitter parsing

crates/tabby-index/src/code/index.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/lib.rs, crates/tabby-index/src/structured_doc/public.rs, ee/tabby-db/src/ingestion.rs, ee/tabby-schema/src/schema/ingestion.rs, ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/routes/ingestion.rs, ee/tabby-webserver/src/routes/mod.rs, ee/tabby-webserver/src/service/background_job/hourly.rs, ee/tabby-webserver/src/service/background_job/index_garbage_collection.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/ingestion.rs
1. for deleting by source, GC by source id would do the cleanup.
2. for deleting by id, list every structured doc source and id, and then range to check whether it is ingested doc and still existed in sqlite.
As for `2.`, Tantivy can not query ingested doc with streaming return, so we are iterating all structured docs
ingested docs:
ingested index:
deleted doc:
after GC:
ingested doc with id `page 123 456 678` has gone in index:
=> feat(ingestion): support delete ingested doc and garbage collection

crates/http-api-bindings/src/completion/llama.rs
it's not necessary to print every request logs.
for debugging purpose, this should be done locally.
=> chore(log): drop unnecessary logs for each llama.cpp request

.github/workflows/release.yml
1.3.239 had been removed from upstream release.
failed CI: https://github.com/TabbyML/tabby/actions/runs/14902885001/job/41858667745
new CI: https://github.com/TabbyML/tabby/actions/runs/14903133478/job/41859433228
=> chore: bump vulkan to 1.3.296 for both linux and windows

.github/workflows/docker.yml
Test CI: https://github.com/zwpaper/tabby/actions/runs/14973940325/job/42061314783
Test image:
- zwpaper/tabby:0.105.0
- zwpaper/tabby:0.105.0-cuda11
test command:
```console
nerdctl run --gpus all --rm   -p 0.0.0.0:8080:8080 \                                                                                              (base)
-v $HOME/.tabby:/data \
zwpaper/tabby:0.105.0 \
serve \
--model Qwen2.5-Coder-1.5B \
--chat-model Qwen2.5-Coder-1.5B-Instruct \
--device cuda --chat-device cuda
docker.io/zwpaper/tabby:0.105.0:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:8f17e50141a54023942160fd391861187b5ad10e52e14600ee22726a9d6d6569:    exists         |++++++++++++++++++++++++++++++++++++++| …
```
=> chore: default use 12.9.0 docker image

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/CodeVisionProvider.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/DiffHighLightingPass.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatIntentionAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatService.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
- feat: add cancel action and loading state for inline chat edits
- fix: wrong inline edit position for scrolled editor
- fix: cant't trigger inline edit when user undo inline diff
=> feat(intellij): add cancel action and loading state for inline chat edits

README.md
Adds a new entry under the "What's New" section in the README for version v0.28.0.
- Includes a link to the v0.28.0 release page
- Summarizes the key update: persistent, shareable pages via Answer Engine messages
No other changes were made.
=> docs: add v0.28.0 release notes to README

Cargo.lock, Cargo.toml, crates/tabby-download/Cargo.toml
aim-downloader@0.30.0-dev.0
hash-ids@0.30.0-dev.0
http-api-bindings@0.30.0-dev.0
llama-cpp-server@0.30.0-dev.0
ollama-api-bindings@0.30.0-dev.0
sqlx-migrate-validate@0.30.0-dev.0
tabby@0.30.0-dev.0
tabby-common@0.30.0-dev.0
tabby-crawler@0.30.0-dev.0
tabby-db@0.30.0-dev.0
tabby-db-macros@0.30.0-dev.0
tabby-download@0.30.0-dev.0
tabby-git@0.30.0-dev.0
tabby-index@0.30.0-dev.0
tabby-index-cli@0.30.0-dev.0
tabby-inference@0.30.0-dev.0
tabby-schema@0.30.0-dev.0
tabby-webserver@0.30.0-dev.0
Generated by cargo-workspaces
=> chore: bump main to 0.30.0-dev.0

crates/http-api-bindings/src/embedding/openai.rs
Fixes #4089 - Removes duplicate "content-type" header in HTTP requests to embedding API endpoints.
When sending requests to model API endpoints, the "content-type" header was being set twice:
1. Automatically by reqwest's `.json()` method 
2. Explicitly via `.header("content-type", "application/json")`
Removed the explicit `.header("content-type", "application/json")` call from the request builder in `/crates/http-api-bindings/src/embedding/openai.rs`.
- Manually verified HTTP request headers no longer contain duplicate content-type entries
=> fix(http): fix repeated content-type in http headers

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/ChatAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/CodeVisionProvider.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/CommandListComponent.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatIntentionAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/SelectionGutterIconManager.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/LanguageClient.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/protocol/ProtocolData.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/protocol/client/LanguageClient.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
- undo inline edit in one undo
https://jam.dev/c/f3107d66-d56c-48cf-adc1-3134d75e978c
- fix cpu high when inline edit input open
- code vision feature check and code vision setting
- disable features(inline edit, chat actions menu) when chat api not available
-
=> fix(intellij): undo inline edit in one undo & add code vision setting

crates/aim-downloader/src/error.rs, crates/aim-downloader/src/https.rs
fix https://github.com/TabbyML/tabby/issues/4278
Before:
After:
=> fix: improve error logging in aim-downloader

.github/workflows/release.yml
ci: https://github.com/TabbyML/tabby/actions/runs/16014572055/job/45178647978
=> ci(llama-server): use windows-2022 to build

.github/workflows/docker.yml
• Update CUDA version from 12.9.0 to 12.4.1 in the Docker workflow configuration
• This change affects the Docker image build process for CUDA-enabled builds
🤖 Generated with [Pochi](https://getpochi.com)
=> chore: update CUDA version from 12.9.0 to 12.4.1 in Docker workflow

website/docs/quick-start/installation/linux/index.mdx, website/docs/quick-start/installation/wsl.mdx
This PR improves the installation experience by updating the documentation for:
- **Linux:** Adds Katana installation instructions, referencing official releases. It is a mandatory dependency to enable developer documentation indexing...
- **WSL2:** Adds a dedicated WSL2 setup page that simplifies local installation with Windows + Ubuntu under WSL2. Encourages users to choose between Ubuntu 22.04 (CUDA 11) or 24.04 (CUDA 12). 
This PR addresses the feedback from PR #4110.
=> docs(install): add Katana install and WSL2 setup guide

ee/tabby-db/src/lib.rs
- Increase max_connections from 1 to 20 for better concurrency in tests
- Add min_connections setting (2) to maintain a minimum pool size
- Add connection timeout configurations:
- acquire_timeout (6 seconds) to prevent indefinite waits
- idle_timeout (5 minutes) to clean up unused connections
- max_lifetime (1 hour) to refresh connections periodically
- Add explicit type annotation for better code clarity
These changes should improve performance and stability for in-memory databases used in tests and test utilities by providing better connection pooling configuration.
🤖 Generated with [Pochi](https://getpochi.com)
=> fix(db): improve connection pool configuration for in-memory databases

website/docs/faq.mdx
- Add FAQ entry explaining that Tabby's root directory should not be placed on NFS filesystems
- Explains SQLite's dependency on proper file locking mechanisms
- References official SQLite documentation about broken/missing lock implementations
🤖 Generated with [Pochi](https://getpochi.com)
=> docs(faq): add warning about NFS filesystem safety with SQLite
