TabbyML/tabby

Makefile, README.md, deployment/.gitignore, deployment/docker-compose.triton.yml, deployment/docker-compose.yml, server/app.py, server/python.py
=> Add python transformer backend for tabby (mainly used for local dev / test in non-cuda environment)

deployment/docker-compose.yml, poetry.lock, pyproject.toml, tabby/admin/Home.py, tabby/admin/pages/Metrics.py, tabby/tasks/duckdb.yaml, tabby/tasks/trainer.yaml, tabby/tools/duckdb/main.sh
=> Add Completion Events & Acceptance Rate in metrics panel.

Dockerfile, README.md, deployment/.env, deployment/config/vector.toml, deployment/docker-compose.yml, deployment/scripts/supervisord.sh, development/docker-compose.dev.yml, development/docker-compose.python.yml, tabby/admin/Home.py, tabby/admin/pages/Metrics.py, tabby/tasks/duckdb.yaml, tabby/tasks/init.yaml, tabby/tools/duckdb/main.sh
=> Add supervisord to support a single docker run deployment

clients/vim/autoload/tabby.vim, clients/vim/node_scripts/package.json, clients/vim/node_scripts/src/TabbyClient.ts, tabby/admin/Home.py
=> fix: fix vim extension linebreak bug

clients/vscode/.vscode/launch.json
=> fix typo in launch.json

clients/vim/README.md, clients/vim/autoload/tabby.vim, clients/vim/autoload/tabby/inline_completion.vim, clients/vim/autoload/tabby/job.vim
#36 
Tested on macos neovim:
```
:version                                                                                                        
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura
```
=> Add neovim support.

tabby/admin/pages/Projects.py, tabby/tools/build_dataset/__main__.py
=> feat: visualize populated dataset in admin

development/Dockerfile, development/docker-compose.dev.yml, poetry.lock, pyproject.toml, tabby/scripts/flags.sh, tabby/server/backend/language_presets.py, tabby/server/backend/prompt_rewriter.py, tabby/server/backend/triton.py, tabby/server/events.py
=> feat: FLAGS_rewrite_prompt_with_search_snippet

clients/vscode/.gitignore, clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/TabbyClient.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/tsconfig.json, clients/vscode/yarn.lock
=> Update vscode use openapi codegen.

README.md
=> Update README.md. Add VSCode extension link to open-vsx.org.

clients/vim/plugin/tabby.vim
=> Vim plugin: only trigger completion request when text changed.

Cargo.lock, Cargo.toml, crates/ctranslate2-bindings/Cargo.toml, crates/ctranslate2-bindings/include/ctranslate2.h, crates/ctranslate2-bindings/src/ctranslate2.cc, crates/ctranslate2-bindings/src/lib.rs
=> refactor: extract TextInferenceEngineImpl to reduce duplications between EncoderDecoderImpl and DecoderImpl

website/docs/server.md
=> docs: update server.md

website/src/components/Monaco/index.js
=> feat: Update playground to support fim.

crates/tabby-download/src/lib.rs
=> fix: vocabulary.txt / shared_vocabulary.txt should be optional

website/docs/self-hosting/01-docker.mdx
migration from docker compose v1 to v2 
[Migrate to Compose V2](https://docs.docker.com/compose/migrate/)
=> docs: Update 01-docker.mdx

crates/tabby-download/src/lib.rs
=> fix: optional file should be put in cache key to avoid internet access when prefer_local_files = true

website/src/components/Monaco/index.js
=> fix: playground segments range error.

clients/vscode/package.json, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/agent.ts, clients/vscode/src/commands.ts, clients/vscode/src/statusBarItem.ts
Complete TAB-84
Settings preview:
=> refactor: VSCode Extension Settings cleanup.

website/src/components/Monaco/index.js
=> fix: Playground completion request cancellation.

clients/vim/README.md
Added a section that explains how to install the extension on packer and lazy.
=> Update the clients/vim/README.md

website/docs/self-hosting/02-apple.md
=> Revert "doc: Update 02-apple.md"

clients/vscode/.eslintrc.json, clients/vscode/.prettierrc.json, clients/vscode/.vscode/launch.json, clients/vscode/.vscodeignore, clients/vscode/assets/walkthroughs/codeCompletion.md, clients/vscode/assets/walkthroughs/server.md, clients/vscode/assets/walkthroughs/toolbar.png, clients/vscode/package.json, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/commands.ts, clients/vscode/src/extension.ts, clients/vscode/src/notifications.ts, yarn.lock
=> feat(vscode): add keybindings for accepting inline completions.

clients/intellij/.idea/misc.xml, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/AcceptCompletion.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/DismissCompletion.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/TriggerCompletion.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/Agent.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/AgentService.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/editor/CompletionScheduler.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/editor/EditorListener.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/editor/InlineCompletionService.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
=> feat(intellij): auto trigger completion and add hotkeys to accept/dismiss.

Cargo.lock, crates/tabby-download/Cargo.toml, crates/tabby-download/src/lib.rs, website/docs/self-hosting/01-docker.mdx
=> fix: improve download logging

clients/intellij/build.gradle.kts
=> chore: bump intellij plugin version to 0.1.0.

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/status/StatusBarWidgetFactory.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
=> fix(intellij): fix compatibility for build 2023.x.  Bump version to 0.1.1.

clients/intellij/README.md, website/docs/getting-started.md
=> docs: add instruction to intellij plugin.

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenAuthPage.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/Agent.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/AgentService.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/status/StatusBarWidgetFactory.kt, clients/intellij/src/main/resources/META-INF/plugin.xml, clients/intellij/src/main/resources/strings.properties
=> feat(intellij): support auth.

clients/vim/autoload/tabby.vim
=> fix(vim): multibytes characters counting.

clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/commands.ts, clients/vscode/src/notifications.ts, clients/vscode/src/statusBarItem.ts
=> fix(vscode): will show warning if editor inline suggest is disabled.

clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/TabbyAgent.ts
=> feat(agent): add anonymous event: Connected.

website/docusaurus.config.js
Fixes the typo in the tagline on the website.
=> Fix typo in tagline

clients/tabby-agent/openapi/tabby.json, clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/ResponseStats.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/vscode/src/TabbyCompletionProvider.ts, clients/vscode/src/commands.ts, clients/vscode/src/notifications.ts, clients/vscode/src/statusBarItem.ts
Complete TAB-165
---
Auto completion requests will expire in 5s by default. Tabby extension will show the notification if most completion requests timed out or average response time is too slow.
---
If running a large model ( >= 1B ) on cpu,  the message will be:
=> feat(agent): monitor completion response time.

clients/tabby-agent/src/postprocess/limitScopeByIndentation.test.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.ts
=> fix(agent): improve postprocess: limitScopeByIndentaion.

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/editor/InlineCompletionService.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
=> fix(intellij): fix inlay text rendering.

crates/ctranslate2-bindings/src/lib.rs, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/completions/prompt.rs
=> feat: add stop words encoding offset for ctranslate model config

.github/workflows/ci.yml, ci/prepare_build_environment.sh, crates/tabby/build.rs
=> chore: add linux static build

clients/tabby-agent/openapi/tabby.json, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/TabbyAgent.ts
=> feat(agent): add server info in AgentConnected event.

crates/ctranslate2-bindings/src/lib.rs, crates/tabby-inference/src/lib.rs, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/completions/prompt.rs
=> feat: implement input truncation with options.max_input_length

Cargo.lock, Cargo.toml, crates/http-api-bindings/Cargo.toml, crates/http-api-bindings/README.md, crates/http-api-bindings/examples/simple.rs, crates/http-api-bindings/src/lib.rs, crates/http-api-bindings/src/vertex_ai.rs, crates/tabby-inference/src/lib.rs
=> feat: add vertex api bindings

Cargo.lock, crates/http-api-bindings/README.md, crates/http-api-bindings/src/vertex_ai.rs, crates/tabby/Cargo.toml, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/mod.rs
fix: TAB-190
cc @gyxlucy 
related #409
=> feat: add support vertex-ai http bindings

clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts, clients/tabby-agent/src/logger.ts, clients/vscode/src/commands.ts
=> refactor(agent): Move data path from ~/.tabby/agent to ~/.tabby-client/agent.  Add config.toml template.

website/docs/03-faq.mdx
=> docs: add faq on utilize multipl NV GPUs

clients/intellij/package.json, clients/tabby-agent/package.json, clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts, clients/tabby-agent/src/logger.ts, clients/vim/package.json, clients/vscode/CHANGELOG.md, clients/vscode/README.md, clients/vscode/assets/walkthroughs/codeCompletion.md, clients/vscode/assets/walkthroughs/server.md, clients/vscode/package.json, clients/vscode/src/agent.ts
- Update document links.
- Fix data.json migration,
- Update anonymous usage tracking client properties. (Fix TAB-199)
=> fix: hotfix vscode extension 0.4.1. 

MODEL_SPEC.md
=> docs: add model spec (unstable) version

clients/vim/README.md
this PR include some suggestion for the vim plugin documentation of Tabby
=> docs:  update vim documentation

Dockerfile
=> feat: Update Dockerfile to ctranslate 3.20.0

website/docs/extensions/intellij.mdx, website/docs/extensions/troubleshooting.md, website/docs/extensions/vim.mdx
=> docs: add client troubleshooting doc

README.md
Update README with 10k star milestone, and also a few nits
=> docs: 10k star update on README

.github/workflows/intellij-test.yml, .github/workflows/tabby-agent-test.yml, .github/workflows/vscode-test.yml, clients/tabby-agent/package.json, clients/tabby-agent/src/CompletionProviderStats.ts, clients/vscode/package.json
Complete TAB-188
Added workflow to test bulding tabby-agent / VSCode Extension / IntelliJ Plugin.
=> chore: add ci test clients.

clients/tabby-agent/src/Agent.ts, clients/tabby-agent/src/AnonymousUsageLogger.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/index.ts, clients/vscode/src/agent.ts
Complete TAB-211
Add user properties `vscode.triggerMode` and `vscode.keybindings` for anonymous usage tracking.
=> feat(agent): add user properties for anonymous usage tracking.

website/blog/2023-09-26-http-streaming-back-pressure-and-cancellation/done.png, website/blog/2023-09-26-http-streaming-back-pressure-and-cancellation/index.md
Format and content improvement
* Code format and comment for a better reading experiece
* Image title for the SEO
* Remove done.png and end with words
=> fix(doc): format and content improvement for the back-pressure blog

MODEL_SPEC.md
=> docs: Update MODEL_SPEC.md

clients/intellij/README.md, clients/vscode/README.md, website/docs/extensions/troubleshooting.md
=> docs(clients): update getting-started and troubleshooting docs.

README.md
1. add latest feature
2. link to documentation page
3. link to Tabby community groups
=> docs: Updates on README

clients/intellij/README.md
=> fix: intellij README.md

crates/tabby-common/src/config.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/mod.rs
1. remove swagger server_url configuration.
2. polish field naming for debug request / response.
=> refactor: improve swagger docs

clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/src/postprocess/trimSpace.test.ts, clients/tabby-agent/src/postprocess/trimSpace.ts, clients/tabby-agent/src/utils.ts
=> fix(agent): improve postprocess to trim whitespace.

Cargo.lock, crates/tabby/Cargo.toml, crates/tabby/tests/golden.json, crates/tabby/tests/goldentests.rs
=> test: add golden test for tabby server

crates/tabby/src/serve/completions/prompt.rs
=> feat: dedup against existing snippets for retrieval augmented code

MODEL_SPEC.md, website/docs/faq.mdx
=> docs: add faq on how to convert own model for tabby

clients/tabby-agent/src/AgentConfig.ts
=> refactor(agent): remove deprecated agent options.

website/docs/configuration.md
=> docs: add example to having two repositories in config.toml

crates/ctranslate2-bindings/src/ctranslate2.cc
=> fix: cap parallelism to 4 for cuda to avoid oom

experimental/modal-deploy/app.py
=> docs: add installation guide on modal

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/Agent.kt, clients/vim/autoload/tabby.vim
=> fix(clients): fix vim & intellij plugin to run node with prefer ipv4 options.

CHANGELOG.md, Cargo.lock, crates/tabby-common/src/config.rs, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/repository.rs
=> feat: support local directory for Repository.git_url.

crates/tabby-common/src/config.rs, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/repository.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/src/serve/mod.rs
=> feat: add server.completion_timeout to control timeout of /v1/completion

.github/workflows/ci.yml, CHANGELOG.md, crates/llama-cpp-bindings/include/engine.h, crates/llama-cpp-bindings/src/engine.cc, crates/llama-cpp-bindings/src/lib.rs, crates/tabby/Cargo.toml, crates/tabby/src/serve/engine.rs, crates/tabby/src/serve/mod.rs, website/docs/models/index.md
=> feat: swtich cpu backend to llama.cpp

.github/workflows/vim-release.yml, clients/vim/CHANGELOG.md, clients/vim/autoload/tabby/globals.vim, clients/vim/package.json
=> fix(action): update github action vim-release using ad-m/github-push-action

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/settings/ApplicationSettingsPanel.kt, clients/tabby-agent/src/AgentConfig.ts, clients/vscode/package.json, website/docs/extensions/configurations.md, website/docs/extensions/intellij.mdx
=> feat(clients): add information about anonymous data tracking.

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/Agent.kt
=> fix(intellij): fix agent IO charset to UTF8.

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, website/docs/programming-languages.md
* feat: add java language configuration
* feat: add java repository context support
=> feat: supports java

crates/tabby/src/main.rs, crates/tabby/src/search.rs, crates/tabby/src/serve/completions.rs, crates/tabby/src/serve/completions/prompt.rs, crates/tabby/src/serve/mod.rs, crates/tabby/src/serve/search.rs
=> refactor: extract IndexServer into CodeSearchService

clients/intellij/README.md, clients/vim/doc/tabby.txt, clients/vscode/README.md, clients/vscode/assets/walkthroughs/server.md, clients/vscode/assets/walkthroughs/setApiEndpoint.md, clients/vscode/assets/walkthroughs/setApiEndpoint.png, clients/vscode/assets/walkthroughs/statusbarReady.png
=> docs: update docs about Tabby Cloud.

crates/llama-cpp-bindings/src/llama.rs
When request channel is queuing, we should eagerly check if tx is closed to avoid enqueue a canceled request.
Previous implementation make every request could at least be inference for one step.
=> fix: llama.cpp queuing logic

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/CompletionProviderStats.ts, clients/tabby-agent/src/TabbyAgent.ts, website/docs/extensions/configurations.md
=> feat(agent): add back agent timeout config.

crates/tabby/src/main.rs, website/blog/2023-11-6-model-evaluation/cceval.png, website/blog/2023-11-6-model-evaluation/human-eval-plus.png, website/blog/2023-11-6-model-evaluation/index.md, website/blog/2023-11-6-model-evaluation/repobench.png, website/blog/2023-11-6-model-evaluation/repocoder.png
=> docs: blogpost for code model evals

clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.test.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/tests/bad_cases/2-typescript.ts
=> refactor(agent): extract calculateReplaceRange and add unit test.

.github/workflows/intellij-test.yml, .github/workflows/tabby-agent-test.yml, .github/workflows/vscode-test.yml, clients/tabby-agent/.gitattributes, clients/tabby-agent/package.json, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/src/postprocess/limitScope.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.ts, clients/tabby-agent/src/postprocess/limitScopeBySyntax.test.ts, clients/tabby-agent/src/postprocess/limitScopeBySyntax.ts, clients/tabby-agent/src/postprocess/testUtils.ts, clients/tabby-agent/src/syntax/parser.ts, clients/tabby-agent/src/syntax/typeList.ts, clients/tabby-agent/tests/golden.test.ts, clients/tabby-agent/tsup.config.ts, clients/tabby-agent/wasm/tree-sitter-go.wasm, clients/tabby-agent/wasm/tree-sitter-python.wasm, clients/tabby-agent/wasm/tree-sitter-ruby.wasm, clients/tabby-agent/wasm/tree-sitter-rust.wasm, clients/tabby-agent/wasm/tree-sitter-tsx.wasm, clients/tabby-agent/wasm/tree-sitter.wasm, clients/vscode/package.json, clients/vscode/tsup.config.ts, yarn.lock
=> feat(agent): add experimental postprocess limit scope by syntax.

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeBySyntax.test.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeBySyntax.ts, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/tests/golden.test.ts
Base on #758 and #764 
Complete TAB-317
=> feat(agent): add exprimental postprocess calculate replace range by syntax.

website/docs/faq.mdx
=> docs: add custom registry information to faq

crates/tabby-common/src/registry.rs, crates/tabby-download/src/lib.rs, crates/tabby/src/serve.rs
=> feat: match remote model cache to MODEL_SPEC.md

clients/vim/autoload/tabby/keybindings.vim
Fix https://github.com/TabbyML/vim-tabby/issues/2
=> fix(vim): fix vim tab keybinding fallback.

clients/vscode/src/TabbyStatusBarItem.ts
=> feat(vscode): show loading status when fetching completion for auto trigger mode.

.github/workflows/ci.yml, Dockerfile
https://github.com/TabbyML/tabby/issues/818
=> fix: rust build caused by 1.74.0 release

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/CheckIssueDetail.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/JoinTabbySlackCommunity.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenModelRegistry.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenOnlineDocumentation.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenTabbyGithubRepo.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/AgentService.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/settings/ApplicationSettingsPanel.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/settings/ApplicationSettingsState.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/status/StatusBarWidgetFactory.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
Complete TAB-325
Related #821
Previews:
=> feat(intellij): Add dont-show-again for warnings. Add more online help links.

Cargo.lock, crates/tabby-common/src/lib.rs, crates/tabby-common/src/path.rs, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/dataset/deps.rs, crates/tabby-scheduler/src/dataset/tags.rs
=> feat: implement basic dependency detection for python / rust

.github/workflows/autofix.yml, Cargo.lock, Makefile, crates/tabby-common/Cargo.toml, crates/tabby-common/src/lib.rs, crates/tabby-common/src/path.rs, crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/dataset/deps.rs
=> fix: keep only direct dependency, clean up path

ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema.rs
- Update GraphQL schema
- Add impl to read token
=> feat: update graphql query to read token

.github/workflows/ci.yml, .github/workflows/docker.yml, Dockerfile
=> fix: manage rust toolchain version with vars

ee/tabby-webserver/src/lib.rs
Found after running: `make fix`
=> fix: Remove redundunt clone()

.github/workflows/ci.yml, .github/workflows/docker.yml
=> refactor: change to vars.RUST_TOOLCHAIN for rust ci

ee/tabby-ui/app/(dashboard)/page.tsx, ee/tabby-ui/app/playground/components/clear-chats-button.tsx, ee/tabby-ui/components/chat-message-actions.tsx, ee/tabby-ui/components/copy-button.tsx, ee/tabby-ui/lib/gql/generates/gql.ts, ee/tabby-ui/lib/gql/generates/graphql.ts, ee/tabby-ui/lib/gql/request-documents.tsx
=> feat: Display registration token in webserver dashboard

website/blog/2023-11-23-coding-llm-leaderboard/index.mdx, website/blog/2023-11-23-coding-llm-leaderboard/leaderboard.png, website/blog/2023-11-23-coding-llm-leaderboard/next-line-accuracy.png
=> docs: add coding llm leaderboard blog

clients/intellij/package.json, clients/tabby-agent/package.json, clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/CompletionContext.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/vim/package.json, clients/vscode/package.json, clients/vscode/src/TabbyCompletionProvider.ts
=> feat(agent): support read clipboard as prompt

crates/tabby-common/src/api/event.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/completion/completion_prompt.rs
=> feat: add clipboard segment

.github/workflows/ci.yml, ci/prepare_build_environment.sh, crates/llama-cpp-bindings/build.rs
=> feat(ci): build linux binary in manylinux container

crates/llama-cpp-bindings/src/engine.cc
This PR resolves the issue of Unicode character decoding errors in the Deepseek Coder model, referencing the content in the following two links:
- https://github.com/ggerganov/llama.cpp/pull/4118
- https://github.com/shibe2/llama.cpp/blob/724dd5c2300ed6df926ddd8a1ed677337280646b/examples/server/server.cpp#L960-L986
=> fix: generate unicode characters error

ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
for easier integration with `react-form-hooks`
=> fix: correct tabby-webserver validation logic

crates/aim-downloader/src/untildify.rs
context: https://github.com/TabbyML/tabby/actions/runs/7155383000/job/19483937261?pr=1000
=> fix: ci build in github runner, simply ignore tild related unit test

ee/tabby-webserver/src/service/cron.rs, ee/tabby-webserver/src/service/db/refresh_tokens.rs
=> refactor: implement delete_expired_token with Utc::now()

Cargo.lock, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/migrations/01-registration-token-table/down.sql, ee/tabby-webserver/migrations/01-registration-token-table/up.sql, ee/tabby-webserver/migrations/02-users-table/down.sql, ee/tabby-webserver/migrations/02-users-table/up.sql, ee/tabby-webserver/migrations/03-invitations-table/down.sql, ee/tabby-webserver/migrations/03-invitations-table/up.sql, ee/tabby-webserver/migrations/04-refresh-tokens/down.sql, ee/tabby-webserver/migrations/04-refresh-tokens/up.sql, ee/tabby-webserver/src/service/db/mod.rs
=> refactor: extract migrations into directory

ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/repositories/mod.rs
=> fix: /repositories should requires authentication as well

crates/tabby-common/src/config.rs, crates/tabby-scheduler/tests/integration_test.rs, ee/tabby-webserver/src/repositories/mod.rs
=> feat(common): add optional name field to RepositoryConfig

clients/intellij/README.md, clients/vim/README.md, clients/vscode/README.md, clients/vscode/assets/walkthroughs/setApiEndpoint.md, website/docs/extensions/configurations.md, website/docs/extensions/troubleshooting.md
=> docs: update clients docs about setting the tabby server auth token.

ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/path.rs, ee/tabby-webserver/src/service/db/mod.rs
=> refactor(webserver): extract mod path.rs for webserver's paths

ee/tabby-webserver/src/service/cron/mod.rs, ee/tabby-webserver/src/service/db/mod.rs, ee/tabby-webserver/src/service/mod.rs
=> refactor(webserver): move run-cron to ServerContext::new

crates/tabby-scheduler/Cargo.toml, crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/index.rs, crates/tabby-scheduler/src/lib.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/Cargo.toml, crates/tabby/src/main.rs
=> refactor(scheduler): extract config argument to reduce boilerplate

crates/tabby-common/src/api/event.rs, crates/tabby/src/routes/events.rs, crates/tabby/src/services/completion.rs
be used for deserialized as well)
=> refactor(common/event): use data structure with ownership (so they can

clients/tabby-agent/src/postprocess/golden/limit_scope/experimental_block_02.toml, clients/tabby-agent/src/postprocess/golden/limit_scope/experimental_syntax_rust_01.toml, clients/tabby-agent/src/postprocess/index.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.test.ts, clients/tabby-agent/src/postprocess/limitScopeByIndentation.ts, clients/tabby-agent/src/postprocess/limitScopeBySyntax.test.ts, clients/tabby-agent/src/postprocess/removeDuplicatedBlockClosingLine.test.ts, clients/tabby-agent/src/postprocess/removeDuplicatedBlockClosingLine.ts, clients/tabby-agent/src/utils.ts
=> fix(agent): fix postprocesing dupplicated block closing line.

website/docs/installation/skypilot/index.md, website/docs/installation/skypilot/service-ready.png, website/docs/installation/skypilot/start-service.png, website/docs/installation/skypilot/tabby-ready.png, website/docs/installation/skypilot/tabby.yaml
cc @concretevitamin for review
=> docs: add installation tutorials for skypilot serving

website/docs/installation/skypilot/index.md, website/docs/installation/skypilot/tabby.yaml
Changes
- add a full link to tabby.yaml
- hint you can use any of a set of GPUs
=> docs: minor updates to skypilot deploy docs

website/docs/faq.mdx, website/docs/roadmap.mdx, website/src/components/Collapse.jsx
=> docs: extract Collapse react component for easier collapsable

ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/job.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/db/job_runs.rs, ee/tabby-webserver/src/service/job.rs, ee/tabby-webserver/src/service/mod.rs
=> refactor(webserver): extract job service

ee/tabby-webserver/src/service/cron/job_utils.rs, ee/tabby-webserver/src/service/db/invitations.rs, ee/tabby-webserver/src/service/db/job_runs.rs, ee/tabby-webserver/src/service/db/mod.rs, ee/tabby-webserver/src/service/db/refresh_tokens.rs, ee/tabby-webserver/src/service/db/users.rs
=> refactor(webserver): add DAO suffix to database bridge objects

ee/tabby-webserver/src/handler.rs, ee/tabby-webserver/src/repositories/mod.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/mod.rs
=> refactor(webserver): return owned instance of service in ServiceLocator

crates/llama-cpp-bindings/src/lib.rs, crates/tabby-common/src/lib.rs, crates/tabby-download/src/lib.rs, crates/tabby-inference/src/lib.rs, crates/tabby-scheduler/src/lib.rs, crates/tabby/src/main.rs, ee/tabby-webserver/src/lib.rs
Add basic descriptions of most tabby crates in doc comments
=> docs: Crate doc comments

ee/tabby-db/migrations/08-repositories-table/down.sql, ee/tabby-db/migrations/08-repositories-table/up.sql, ee/tabby-db/src/lib.rs, ee/tabby-db/src/repositories.rs
=> feat(db): Implement DAO for repositories

ee/tabby-webserver/src/repositories/mod.rs, ee/tabby-webserver/src/repositories/resolve.rs
For fixing issue: https://github.com/TabbyML/tabby/issues/1182
Idea comes from https://github.com/TabbyML/tabby/issues/1182#issuecomment-1883282935
=> fix(webserver): filter repository file without meta info

website/blog/2023-09-18-release-0-1-1-metal/index.md, website/docusaurus.config.js
=> Revert "docs: fix redirect error."

ee/tabby-db/src/lib.rs, ee/tabby-db/src/repositories.rs, ee/tabby-webserver/src/oauth/mod.rs, ee/tabby-webserver/src/schema/dao.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/schema/repository.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/job.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/repository.rs
Builds on top of the email-creds-graphql PR. Closes #1143.
Also in this PR: Refactored some common logic for converting GraphQL query parameters into our internal search filters
=> feat: Create GraphQL endpoints for repositories

clients/example-vscode-lsp/.gitattributes, clients/example-vscode-lsp/.gitignore, clients/example-vscode-lsp/README.md, clients/example-vscode-lsp/demo.png, clients/example-vscode-lsp/package.json, clients/example-vscode-lsp/src/extension.ts, clients/example-vscode-lsp/tsconfig.json, clients/example-vscode-lsp/tsup.config.ts, package.json, yarn.lock
Follow up #1172 
Complete TAB-389
=> feat(lsp): add example VSCode client for Tabby agent LSP.

ee/tabby-webserver/docs/api_spec.md, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/oauth/github.rs, ee/tabby-webserver/src/oauth/google.rs, ee/tabby-webserver/src/oauth/mod.rs
Followup of PR: https://github.com/TabbyML/tabby/pull/1194
=> fix(webserver): update graphql api schema, update api doc, fix warning

ee/tabby-ui/app/globals.css
=> feat(ui): set background color for dark mode

clients/example-vscode-lsp/package.json, clients/intellij/package.json, clients/tabby-agent/.npmignore, clients/tabby-agent/CHANGELOG.md, clients/tabby-agent/LICENSE, clients/tabby-agent/README.md, clients/tabby-agent/package.json, clients/tabby-agent/wasm/LICENSES, clients/vim/package.json, clients/vscode/package.json
=> chore(agent): bump tabby-agent version to 1.3.0

crates/tabby-common/src/lib.rs, crates/tabby-common/src/terminal.rs, crates/tabby-common/src/usage.rs, crates/tabby/src/services/model.rs, ee/tabby-webserver/src/schema/auth.rs
=> feat: Add warning for using CPU mode

Cargo.lock, clients/tabby-agent/README.md, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/schema/email.rs, ee/tabby-webserver/src/service/email.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver): Implement send_mail method in EmailService

ee/tabby-ui/app/globals.css
=> feat(tabby-ui): adjust color palette of dark mode

ee/tabby-ui/components/user-panel.tsx
previously, the click region of menu option is not fully reactive
=> feat(ui): adjust user panel click area

clients/tabby-agent/src/postprocess/golden/remove_duplication/duplicated_block_closing_line_01.toml, clients/tabby-agent/src/postprocess/removeDuplicatedBlockClosingLine.ts
thanks to contribution of @erfanium
=> fix(agent): fix postprocess remove duplicated block closing line.

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/settings/ApplicationSettingsPanel.kt
=> fix(intellij): fix check connection never ends when endpoint left empty.

clients/vscode/src/TabbyCompletionProvider.ts
=> fix(vscode): do not trigger completion when text selected.

ee/tabby-webserver/src/schema/mod.rs
=> fix(webserver): Return standard error code for unauthorized graphql access

ee/tabby-webserver/src/service/cron/mod.rs, ee/tabby-webserver/src/service/mod.rs
=> fix(webserver): Remove redundant scheduler code

ee/tabby-ui/lib/tabby/auth.tsx, ee/tabby-ui/lib/tabby/gql.ts
=> fix(ui): Update condition logic in did-auth-error

crates/tabby-scheduler/src/dataset.rs
=> fix(scheduler): Give more error info when a file cannot be accessed

crates/tabby-common/src/config.rs, ee/tabby-webserver/src/hub/api.rs, ee/tabby-webserver/src/hub/mod.rs
=> feat(webserver): Add endpoint to fetch repositories from hub server

crates/llama-cpp-bindings/include/engine.h, crates/llama-cpp-bindings/src/engine.cc, crates/llama-cpp-bindings/src/lib.rs, crates/llama-cpp-bindings/src/llama.rs, crates/tabby-inference/src/lib.rs, crates/tabby/src/services/completion.rs, crates/tabby/tests/goldentests.rs
=> feat(core): Add support for passing temperature as a parameter

clients/tabby-agent/src/postprocess/golden/remove_duplication/duplicated_line_suffix.toml
I'm not sure about test description and file name, feel free to change it
=> test(agent): add a fail case test for postprocess

crates/tabby-inference/src/lib.rs, crates/tabby/src/services/chat.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/mod.rs, crates/tabby/tests/goldentests_chat.rs
=> feat(tabby): Allow passing temperature and seed to chat completion requests

ee/tabby-ui/app/files/components/file-directory-panel.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/lib/tabby/auth.tsx
1. fix invitation link doesn't work
2. refactoring empty display of source code browser
=> fix(ui): properly handle invitation link page redirect (shouldn't got to sign-in)

ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): Prevent disabled accounts from authenticating

clients/tabby-agent/tsup.config.ts
=> chore(agent): add banner for bundled cli script.

clients/vscode/src/TabbyCompletionProvider.ts
=> fix(vscode): fix vscode notebook context, add newline before suffix cells.

clients/tabby-agent/src/CompletionCache.ts, clients/tabby-agent/src/CompletionContext.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.test.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/postprocess/formatIndentation.ts, clients/tabby-agent/src/postprocess/golden/replace_range/jsx_tags_01.toml, clients/tabby-agent/src/postprocess/golden/replace_range/jsx_tags_02.toml, clients/tabby-agent/src/utils.ts
=> fix(agent): fix support for html/jsx auto closing chars.

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/postprocess/calculateReplaceRangeBySyntax.ts, clients/tabby-agent/src/postprocess/golden/limit_scope/to_block_03.toml, clients/tabby-agent/src/postprocess/golden/limit_scope/to_line_01.toml, clients/tabby-agent/src/postprocess/golden/replace_range/experimental_syntax_javascript_01.toml, clients/tabby-agent/src/syntax/typeList.ts
Complete TAB-357
Changes:
- Enabled experimental feature by default:
- Strip auto-closing characters in prompt suffix.
- Syntax-based post-processing.
=> feat(agent): enable experimental syntax based features by default.

ee/tabby-ui/app/(dashboard)/team/components/invitation-table.tsx, ee/tabby-ui/app/(dashboard)/team/components/user-table.tsx, ee/tabby-ui/app/globals.css, ee/tabby-ui/components/simple-pagination.tsx, ee/tabby-ui/components/ui/badge.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/tailwind.config.js, ee/tabby-webserver/graphql/schema.graphql
=> feat(ui, webserver): allow deactivating a user

ee/tabby-ui/app/(dashboard)/team/components/user-table.tsx, ee/tabby-ui/app/layout.tsx, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/types/common.ts
1. enrich the content of toast
2. try to fix the bg color bug of toast component
=> fix(ui): enrich the content of acticating/deactivating toast

ee/tabby-db/src/invitations.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/email.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/email.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver): Send an email whenever an invitation is created

crates/tabby/src/routes/completions.rs, crates/tabby/src/services/completion.rs, ee/tabby-db/src/users.rs, ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver): Populate the user field in completions requests if the user authenticated

Cargo.lock, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/oauth/mod.rs, ee/tabby-webserver/src/ui.rs
Path: `http://localhost:8080/_next/static/chunks/app/(dashboard)/sso/detail/%5Bprovider%5D/page-03bedeef65986523.js`
Local file name: `_next/static/chunks/app/(dashboard)/sso/detail/[provider]/page-03bedeef65986523.js`
=> fix(ui): support url encoded path in ui handler

crates/tabby-scheduler/src/dataset.rs, crates/tabby-scheduler/src/index.rs, crates/tabby-scheduler/src/lib.rs, crates/tabby-scheduler/src/repository.rs, crates/tabby-scheduler/tests/integration_test.rs, crates/tabby/src/job.rs, crates/tabby/src/main.rs, crates/tabby/src/serve.rs, crates/tabby/src/worker.rs, ee/tabby-webserver/src/handler.rs, ee/tabby-webserver/src/hub/api.rs, ee/tabby-webserver/src/hub/mod.rs, ee/tabby-webserver/src/lib.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/cron/job_utils.rs, ee/tabby-webserver/src/service/cron/mod.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver, scheduler): Enable pulling repositories from hub server in cron jobs

ee/tabby-ui/app/(dashboard)/settings/team/components/invitation-table.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/dao.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
Remove old Invitation, rename InvitationNext to Invitation
=> refactor(core): Remove Invitation and replace it with InvitationNext (renamed)

ee/tabby-webserver/src/oauth/github.rs, ee/tabby-webserver/src/oauth/google.rs, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/dao.rs, ee/tabby-webserver/src/schema/mod.rs
=> fix: fill oauth secret to client

ee/tabby-ui/app/(dashboard)/settings/general/components/form-section.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/general.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/network-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/security-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/page.tsx, ee/tabby-ui/components/ui/checkbox.tsx, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/schema/setting.rs, ee/tabby-webserver/src/service/setting.rs
https://jam.dev/c/0213fd14-1aab-45d6-8e69-92a0ab9d741d
=> feat(ui, webserver): add general settings

Makefile, rules/avoid-unwrap.yml
=> Revert "fix(core): Change unwrap check to clippy lint"

website/docs/installation/docker-compose.mdx, website/docs/installation/docker.mdx
=> docs: update docker documentation for cpu

Cargo.lock, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/schema/email.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/email.rs
=> refactor(email): switch email send to backend

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/mod.rs
=> feat(webserver): Add endpoint to check if email is configured

crates/tabby-common/src/config.rs
=> fix(common): Fix repository name validation

ee/tabby-ui/app/(dashboard)/settings/subscription/components/license-table.tsx, ee/tabby-ui/app/(dashboard)/settings/subscription/components/subscription.tsx, ee/tabby-ui/components/sub-header.tsx, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/license.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/license.rs, ee/tabby-webserver/src/service/mod.rs
=> feat(webserver): update subscription limits.

website/docs/faq.mdx
Hello,
it took me a few hours to find a way loading otherer models from huggingface, therefore please accept this little description addition as a hint for other users.
Local model.json path description added.
=> docs: faq.mdx load model from local directory

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/agent/AgentService.kt, clients/vscode/src/TabbyStatusBarItem.ts
Complete TAB-480
Changes (VSCode Extension & IntelliJ Platform Plugin):
- Removed the notification when disconnected; the status bar icon will remain to indicate the disconnected status.
=> fix(clients): Remove the notification when disconnected, keep only status bar icon.

ee/tabby-ui/app/(dashboard)/page.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/git/components/repository-table.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/general.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/network-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/security-form.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/invitation-table.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-role-dialog.tsx, ee/tabby-ui/app/layout.tsx, ee/tabby-ui/lib/hooks/use-network-setting.tsx
1.  display the correct external url
2. refresh network settings
3. git table truncate
=> fix(ui): display the correct external url

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/license.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/license.rs
=> feat(webserver): Add endpoint to delete license

ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): fix the logic toggle admin user's active status

ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/dao.rs
=> feat(webserver): Add authenticated endpoint to update password

ee/tabby-ui/components/client-only.tsx, ee/tabby-ui/components/header.tsx
bug: https://jam.dev/c/6d8db403-2640-4bbd-9950-d043888184ff
=> fix(ui): display correct theme icon

ee/tabby-ui/app/(dashboard)/page.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx
1. copy
2. not allow to update role of an inactive member
=> fix(ui): not allow to update role of an inactive member 

ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): Better error message when the email does not match the code

crates/llama-cpp-bindings/build.rs
=> fix: disable LLAMA_NATIVE in build

ee/tabby-ui/app/(dashboard)/settings/(integrations)/mail/components/mail-testing-form.tsx
=> fix(ui): update toast message in MailTestingForm component

ee/tabby-ui/app/globals.css
=> feat(ui): update dark mode background color in globals.css

ee/tabby-ui/app/(dashboard)/profile/components/change-password.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/git/components/create-repository-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/mail/components/mail-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/mail/components/mail-testing-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/network-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/security-form.tsx, ee/tabby-ui/app/(dashboard)/settings/subscription/components/license-form.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/create-invitation-form.tsx, ee/tabby-ui/app/auth/reset-password/components/reset-password-form.tsx, ee/tabby-ui/app/auth/signin/components/reset-password-request-form.tsx, ee/tabby-ui/app/auth/signin/components/self-signup-form.tsx, ee/tabby-ui/app/auth/signin/components/signin-section.tsx, ee/tabby-ui/app/auth/signin/components/user-signin-form.tsx, ee/tabby-ui/app/auth/signup/components/user-register-form.tsx
1. space-y between form items:
a. signin / signup form: 4
b. others: 6
2. space-y between root error msg and submit btn: 2
=> fix(ui): uniformly adjust the form space

ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): improve error messages for sign-in

ee/tabby-db/src/refresh_tokens.rs, ee/tabby-db/src/users.rs, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
=> feat(webserver): Add endpoint to logout all user sessions

ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): Disallow resetting a password to the same value

ee/tabby-db/src/refresh_tokens.rs, ee/tabby-webserver/src/service/auth.rs
=> refactor(db): Enable query_as! for RefreshTokenDAO

ee/tabby-webserver/src/cron/mod.rs, ee/tabby-webserver/src/cron/scheduler.rs, ee/tabby-webserver/src/handler.rs, ee/tabby-webserver/src/repositories/resolve.rs
=> feat(webserver): Reload repository cache when scheduler job finishes

ee/tabby-ui/app/(dashboard)/settings/(integrations)/mail/components/mail-form.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/components/user-panel.tsx
1. Disable signout btn during loading
2. Use the correct select structure in the form to resolve warnings and errors.
=> fix(ui):  use the correct select structure in the form to resolve warnings and errors

crates/tabby/src/main.rs, crates/tabby/src/services/event.rs
=> fix(tabby): Make event log user-private

Cargo.lock, crates/tabby-common/Cargo.toml, crates/tabby-common/src/config.rs
=> fix(common): Sanitize repository names generated from filenames

CHANGELOG.md, ee/tabby-webserver/src/service/mod.rs
derive from https://github.com/TabbyML/tabby/pull/1651
=> fix(webserver): incorrect node limit check on worker register

website/docs/installation/windows/index.mdx, website/docs/installation/windows/status.png, website/docs/installation/windows/win-release.png
=> docs: add windows installation

yarn.lock
=> chore(agent): update yarn.lock for #1657.

README.md
=> docs: adding activity chart

.github/workflows/release.yml, crates/llama-cpp-bindings/build.rs
Complete TAB-485
Related: #1620
Added ci job to build manylinux binary with vulkan support.
=> chore(ci): build manylinux binary with vulkan support.

crates/aim-downloader/src/error.rs, crates/aim-downloader/src/https.rs, crates/aim-downloader/src/lib.rs, crates/tabby-download/src/lib.rs
Fixes #1582, fixes #1575, fixes #1581, closes TAB-534
=> fix(download): Display errors and stop downloading when server returns an error

crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/completion/completion_prompt.rs
Complete TAB-529
Followed by #1682
=> feat(api): add file info in completion request.

ee/tabby-webserver/src/schema/auth.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): Check admin status via auth service instead of JWT

ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/markdown-view.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/text-file-view.tsx, ee/tabby-ui/app/globals.css, ee/tabby-ui/components/codemirror/codemirror.tsx, ee/tabby-ui/components/providers.tsx, ee/tabby-ui/components/topbar-progress-indicator.tsx, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock
1. add markdown preview.
2. add a progress bar when fetching raw files.
3. add `Suspense` for CodeMirror and Markdown.
https://jam.dev/c/90e7840d-be85-4496-94d6-46dce375287d
=> feat(ui): add markdown preview to code browser

crates/tabby-scheduler/src/lib.rs
Fixes TAB-553
cc @liangfung want to know if this process panicking will lead to it showing as failed?
=> fix(scheduler): Panic when now jobs fail

ee/tabby-ui/app/(dashboard)/settings/(integrations)/git/components/repository-table.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/sso/components/oauth-credential-list.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/network-form.tsx, ee/tabby-ui/app/(dashboard)/settings/general/components/security-form.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/invitation-table.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-ui/components/loading-wrapper.tsx, ee/tabby-ui/components/skeleton.tsx, ee/tabby-ui/lib/hooks/use-debounce.ts, ee/tabby-ui/lib/hooks/use-network-setting.tsx
Rebase after #1679 
1. Use 'useDebounceValue' to avoid page flicker.
2. Consider making the 'loading-wrapper' a general component for displaying loading skeleton logic.
=> refactor(ui): Optimize LoadingWrapper experience

website/docs/extensions/troubleshooting/index.md, website/docs/extensions/troubleshooting/vscode-output-view.png
Changes:
Updated the documentation for the feature of logging to the VSCode output channel.
=> docs: update logs section of IDE extensions toubleshooting docs.

crates/tabby-scheduler/src/index.rs
=> fix(scheduler): Improve error message on tag range out-of-bounds

ee/tabby-db-macros/src/lib.rs, ee/tabby-db/src/job_runs.rs, ee/tabby-db/src/lib.rs, ee/tabby-webserver/src/service/dao.rs
=> refactor(db): Convert job run DAO to be usable with query_paged_as

website/docs/administration/smtp/index.md, website/docs/administration/smtp/mail-delivery.png, website/docs/administration/smtp/ses.png, website/docs/administration/smtp/test-email.png
=> docs: add Mail Delivery page

website/docs/administration/distributed/chat-playground.png, website/docs/administration/distributed/cluster-information.png, website/docs/administration/distributed/completion-worker.png, website/docs/administration/distributed/index.mdx, website/docs/administration/smtp/index.md, website/docusaurus.config.js, website/src/theme/Admonition.js
https://jam.dev/c/3445e976-7667-4d4f-ae62-d69368d5ba02
=> docs: add guide on configuring distribution support

ee/tabby-db/migrations/0020_job-run-index.down.sql, ee/tabby-db/migrations/0020_job-run-index.up.sql, ee/tabby-db/src/job_runs.rs, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/job.rs, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/service/job.rs
=> feat(webserver): Implement new job runs APIs

ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/components/chat.tsx
=> feat(ui): request the default prompt in search params

crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/completion/completion_prompt.rs
Complete TAB-515
Replace #1699
=> feat(core): add relevant snippets in completion request.

ee/tabby-ui/app/(dashboard)/profile/components/avatar.tsx, ee/tabby-ui/app/(dashboard)/profile/components/change-password.tsx, ee/tabby-ui/app/(dashboard)/profile/components/profile.tsx, ee/tabby-ui/components/ui/avatar.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/components/user-avatar.tsx, ee/tabby-ui/components/user-panel.tsx, ee/tabby-ui/lib/utils.ts, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock, ee/tabby-webserver/development/Caddyfile
Close TAB-541
Screen record: https://jam.dev/c/4558b9c5-9a28-44b3-8e63-7cd290333547
=> feat(ui): frontend implementation for avatar uploading in profile

ee/tabby-ui/app/(dashboard)/profile/components/avatar.tsx, ee/tabby-ui/app/(dashboard)/profile/components/change-password.tsx, ee/tabby-ui/app/(dashboard)/profile/components/profile.tsx, ee/tabby-ui/components/ui/avatar.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/components/user-avatar.tsx, ee/tabby-ui/components/user-panel.tsx, ee/tabby-ui/lib/utils.ts, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock, ee/tabby-webserver/development/Caddyfile
Close TAB-541
Screen record: https://jam.dev/c/4558b9c5-9a28-44b3-8e63-7cd290333547
=> feat(ui): support avatar changing in the profile page

ee/tabby-ui/components/chat-message.tsx
=> feat(ui): use user's avatar in playground

ee/tabby-db/src/repositories.rs, ee/tabby-webserver/src/service/repository.rs
=> refactor(db): Make RepositoryDAO use query_paged_as!

ee/tabby-db/src/user_completions.rs
=> chore(db): Change UserCompletionDAO to use query_as!

ee/tabby-ui/components/chat-list.tsx, ee/tabby-ui/components/chat-message.tsx, ee/tabby-ui/components/chat.tsx, ee/tabby-ui/lib/hooks/use-patch-fetch.ts
Close TAB-578
1. scroll to bottom after request
2. add request loading indicator
https://jam.dev/c/ad3f8161-25b8-4381-8ad9-2b7dcc05c773
=> refactor(ui):  add request loading indicator to chat playground

ee/tabby-db/src/lib.rs, ee/tabby-db/src/user_completions.rs, ee/tabby-webserver/src/service/analytic.rs
Caused by https://github.com/TabbyML/tabby/pull/1752
=> fix(webserver): fix tabby build

ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/components/prompt-form.tsx, ee/tabby-ui/components/search-select.tsx, ee/tabby-ui/components/searchable-select.tsx
1. rename
2. mv from `components/ui/` to `components/`
=> refactor(ui): rename component `combobox` to `searchableSelect`

ee/tabby-ui/app/(dashboard)/cluster/page.tsx, ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/(dashboard)/layout.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(dashboard)/settings/subscription/components/license-table.tsx, ee/tabby-ui/components/ui/icons.tsx
=> chore(ui): adjust ui sidebar and reports page

ee/tabby-ui/components/chat.tsx, ee/tabby-ui/lib/hooks/use-patch-fetch.ts
=> fix(ui): prevent consecutive messages from same source

ee/tabby-webserver/src/repositories/mod.rs, ee/tabby-webserver/src/repositories/resolve.rs
=> fix(webserver): /resolve/all should read from RepositoryService

ee/tabby-webserver/src/service/auth.rs
=> fix(webserver): disallow changing row of inactive user

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-detail.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx
=> fix(ui): add spinner when job duration is undefined

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx
=> fix(ui): small adjust of the jobs color in jobs page

Cargo.lock, ee/tabby-db/Cargo.toml, ee/tabby-db/src/cache.rs, ee/tabby-db/src/lib.rs, ee/tabby-db/src/user_completions.rs, ee/tabby-webserver/src/schema/analytic.rs, ee/tabby-webserver/src/service/analytic.rs
=> chore(db): Implement LRU cache for usage analytics

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/components/ui/command.tsx, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock
=> feat(ui): support multi selection of language in reports page

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/user-panel.tsx
=> fix(ui): add links to the home page

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx
=> fix(ui): user selection width in reports page

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/stats.tsx, ee/tabby-ui/app/(home)/page.tsx
https://jam.dev/c/8981214a-6c70-4509-8cd6-b42ae09328e5
=> fix(ui): make the home and report page to be column layout in lg size

ee/tabby-ui/app/(home)/components/completion-charts.tsx
=> fix(ui): correct accept rate box display height

ee/tabby-ui/lib/tabby/auth.tsx, ee/tabby-ui/lib/tabby/fetcher.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/token-management.ts
=> refactor(ui): handle the auto-refresh conflict

clients/tabby-agent/src/AgentConfig.ts
Complete TAB-512
Related: #1844
=> fix(agent): enable feature of collecting snippets from recent changed files.

clients/vscode/src/CodeSearchEngine.ts
Related #1844
Fixed the chunking range calculation.
=> fix(vscode): fix the chunking range calculation.

clients/vscode/package.json, clients/vscode/src/TabbyStatusBarItem.ts, clients/vscode/src/agent.ts, clients/vscode/src/extension.ts
=> fix(vscode): fix updating chat feature when clause context variables.

website/blog/2024-03-25-deploy-tabby-in-air-gapped-environment-with-docker/index.md
Bash command is wrong according to this comment:
https://github.com/TabbyML/tabby/issues/1623#issuecomment-1990977241
=> docs: fix Wrong Bash Command

ee/tabby-ui/app/(dashboard)/profile/components/change-password.tsx, ee/tabby-ui/app/auth/signup/components/user-register-form.tsx, ee/tabby-ui/components/password-check-list.tsx, ee/tabby-ui/components/password-checklist.tsx
Screen record for the flow:
Admin:
https://jam.dev/c/fbc5106c-f7a2-47ef-9dfb-387bfbe86fc8 
Member:
https://jam.dev/c/8c77e051-0d5a-442c-a995-1085df2e2410
Profile:
https://jam.dev/c/dc80268b-4d00-4f6c-8a99-1b5b7504a2e9
Copies:
Dark colors:
fix TAB-613
=> feat(ui): show password schema for registration

ee/tabby-webserver/src/schema/auth.rs
=> fix(webserver): Validate password in password reset input object

ee/tabby-db/src/user_events.rs
To fix error
```
{
"data": null,
"errors": [
{
"message": "error returned from database: (code: 1) near \"04\": syntax error",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"userEvents"
]
}
]
}
```
=> fix(db): list_user_events condition not working

ee/tabby-ui/app/files/components/action-bar-widget/action-bar-widget-extension.tsx, ee/tabby-ui/app/files/components/action-bar-widget/action-bar-widget.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/lib/event-emitter.ts, ee/tabby-ui/components/chat-message.tsx, ee/tabby-ui/components/ui/accordion.tsx, ee/tabby-ui/package.json, ee/tabby-ui/yarn.lock
Close TAB-583
https://jam.dev/c/adf12c50-8e30-471e-bd55-718465c719d2
=> feat(ui): add embed context display in chat playground

ee/tabby-db/src/github_repository_provider.rs, ee/tabby-db/src/invitations.rs, ee/tabby-db/src/job_runs.rs, ee/tabby-db/src/lib.rs, ee/tabby-db/src/password_reset.rs, ee/tabby-db/src/refresh_tokens.rs, ee/tabby-db/src/user_completions.rs, ee/tabby-db/src/user_events.rs, ee/tabby-db/src/users.rs, ee/tabby-webserver/src/service/analytic.rs, ee/tabby-webserver/src/service/dao.rs, ee/tabby-webserver/src/service/github_repository_provider.rs, ee/tabby-webserver/src/service/user_event.rs, rules/use-datetimeutc-in-tabby-db.yml
=> ci: add lint to check around all DateTime<Utc> usage in tabby-db

ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/components/basic-info-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/components/git-privoders-page.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/components/header.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/components/oauth-application-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/detail/components/detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/detail/components/new-repository-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/detail/components/provider-detail-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/detail/page.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/detail/query.ts, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/new/components/confirm-view.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/new/components/new-page.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/new/page.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/gitops/page.tsx, ee/tabby-ui/app/integrations/callback/components/callback.tsx, ee/tabby-ui/app/integrations/callback/page.tsx, ee/tabby-ui/components/steps/steps.css, ee/tabby-ui/components/steps/steps.tsx, ee/tabby-ui/components/ui/alert.tsx, ee/tabby-ui/components/ui/command.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/popup-window-management.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-ui/yarn.lock, ee/tabby-webserver/development/Caddyfile
=> feat(ui): add github integration

clients/vscode/package.json
=> chore(agent&vscode): setting display format

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/github/components/github-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/github/detail/components/detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/github/detail/components/provider-detail-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/github/new/components/new-page.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/file-tree-panel.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/components/ui/form.tsx
https://jam.dev/c/21861ba1-90ad-4a48-8350-44f2c8f49f3b
https://jam.dev/c/1da462e8-fb4b-42bc-ae04-fd413261f848
=> fix(ui): justify context displays in chat playground

ee/tabby-ui/app/(dashboard)/reports/components/daily-activity.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx
=> fix(ui): fix the date display format in analytic charts.

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx
=> chore(ui): accept rate -> acceptance

ee/tabby-ui/lib/hooks/use-patch-fetch.ts
=> chore(ui): switch to /v1/chat/completions

ee/tabby-db/src/github_repository_provider.rs, ee/tabby-db/src/gitlab_repository_provider.rs, ee/tabby-webserver/graphql/schema.graphql, ee/tabby-webserver/src/schema/mod.rs, ee/tabby-webserver/src/schema/repository/github.rs, ee/tabby-webserver/src/schema/repository/gitlab.rs, ee/tabby-webserver/src/service/repository/github.rs, ee/tabby-webserver/src/service/repository/gitlab.rs
=> feat(webserver): support filtering github/gitlab repos by active status

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx
=> fix(ui): update storage usage ui

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx, ee/tabby-ui/lib/hooks/use-workers.ts
Adding skeleton loader to the System page
https://jam.dev/c/4ecb175b-8776-41ad-aceb-3c9e719c57a8
=> fix(ui): add skeleton to system page

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/components/common-provider-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/components/provider-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/github-provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/gitlab-provider-detail.tsx
* Align `px-` between Card header and Card content
* Adjust `mx-`
* Increase placeholder length to 36
* Placeholder vertically centered
* Placeholder color be the same as the input content
=> fix(ui): detail polishing for the provider page

website/blog/2024-05-01-vulkan-support/completion.png, website/blog/2024-05-01-vulkan-support/index.md, website/blog/2024-05-01-vulkan-support/vulkan-installed-on-arch.png, website/blog/2024-05-01-vulkan-support/vulkan-running.png
=> docs: create blog post for vulkan support

crates/tabby-common/assets/languages.toml, website/docs/programming-languages.md
Let me know if there needs to be any changes.
=> feat: add support for `r`

.github/workflows/deploy-demo.yml, experimental/demo/app.py
=> ci: add auto deployment for tabby live demo

Cargo.lock, ee/tabby-webserver/Cargo.toml
related: https://github.com/geofmureithi/apalis/issues/301
=> fix: do not use async-timer to avoid BorrowMut error

ee/tabby-ui/app/(home)/page.tsx
Avoid using `<a>` tag to 
* keep align with the UserPanel (top-right popup in the setting page)
* fix the bug of signout
Screen record: https://jam.dev/c/4fef52c8-e013-44a8-a2f1-7e16609c16d3
=> fix(ui): avoid using a tag for the menu links on the homepage

ee/tabby-ui/app/(dashboard)/components/main-content.tsx, ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/(dashboard)/layout.tsx, ee/tabby-ui/app/layout.tsx, ee/tabby-ui/components/demo-banner.tsx, ee/tabby-ui/components/ui/icons.tsx
Screen record: https://jam.dev/c/d2958662-d7ee-4b97-ba81-504f571219cb
=> feat(ui): add a banner to the page in demo mode

ee/tabby-ui/app/auth/signin/components/user-signin-form.tsx, ee/tabby-ui/lib/constants/index.ts
Screen record: https://jam.dev/c/a3f3d6b6-57f7-4ba8-a33e-465b17b6c01b
The auto-login state is stored in SessionStorage.
Auto-login occurs only in a new tab
Otherwise, it simply autofills the fields.
=> feat(ui): support auto login for the demo

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/components/common-provider-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/github-provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/gitlab-provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/update-github-provider-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/update-gitlab-provider-form.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/new/components/new-page.tsx
https://jam.dev/c/c3dd2623-8ddc-45da-8e49-3d14eb418ba2
* Allow the user to update only the display name
* After updating the display name, the top displaying name should be updated as well
* The form should trim the display name
=> fix(ui): modify provider form schema for updating

ee/tabby-webserver/docs/api_spec.md
One thing worth noting is that the token used for the resolve endpoints isn't easily visible to the user, how should we document this?
=> docs(webserver): update api_spec.md

ee/tabby-schema/src/schema/mod.rs
fix https://github.com/TabbyML/tabby/discussions/2110
=> fix(webserver): repositoryList should be accessible by non-admin users

ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/yarn.lock
=> fix(ui): use the proper URL to request the repository entry

ee/tabby-ui/app/playground/components/chat-sessions.tsx, ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/app/playground/page.tsx, ee/tabby-ui/components/button-scroll-to-bottom.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat-scroll-anchor.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/demo-banner.tsx, ee/tabby-ui/lib/hooks/use-at-bottom.tsx
https://jam.dev/c/ad6b2539-f2e5-45c0-bd25-101fd00bfe7e
=> refactor(ui): make chat session position fixed on scroll

ee/tabby-ui/components/button-scroll-to-bottom.tsx
Add `offset` interface on the ButtonScrollToBottom
I just found I need add custom offset when using this button in the search page
=> fix(ui): add offset props to ButtonScrollToBottom

ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/ui/codeblock.tsx
1. Fix bug in clearing chat messages function
2. Fix action button style in code block
before: https://jam.dev/c/8eeca413-67b1-4b6d-baa9-1b28680d8ca9
after: https://jam.dev/c/cad936b9-28e8-440d-974e-ef0c790cd207
=> fix(ui): clearing chat messages

ee/tabby-schema/src/schema/integration.rs, ee/tabby-webserver/src/service/integration.rs, ee/tabby-webserver/src/service/repository/third_party.rs
Mostly copied from the previous tests with some minor changes
=> test(webserver): add tests for IntegrationService and ThirdPartyRepositoryService

clients/vim/README.md
Add description in document to add vim plugin by [Vundle](https://github.com/VundleVim/Vundle.vim)
=> docs: apply plugin to vim by Vundle.vim

clients/vscode/src/Commands.ts
Get git remote url for explain code.  @wwayne
=> fix(vscode): Get git remote for explain code.

clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/logger.ts
Fix 2237
This fix will be cherrypick and release in VSCode Extension 1.6.3
=> fix(agent): fix file logger unintended output.

ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/empty-screen.tsx, ee/tabby-ui/components/chat/question-answer.tsx
* I reduce the margin-left of question-answer or it has displaying issue in VSCode, web doesn't have such issue
* Add props to set welcome message
=> fix(ui): chat page welcome message & margin-left

clients/tabby-agent/src/lsp/Server.ts, clients/tabby-agent/src/lsp/protocol.ts, clients/vscode/package.json, clients/vscode/src/Config.ts, clients/vscode/src/chat/ChatViewProvider.ts, clients/vscode/src/extension.ts, clients/vscode/src/lsp/AgentFeature.ts, pnpm-lock.yaml
Changes: 
- tabby-agent: add `ServerInfo` sync feature to lsp protocol.
- vscode: check the server info, show help message if chat panel not available.
help message:
=> feat(vscode): check server info for chat panel.

clients/tabby-agent/package.json, pnpm-lock.yaml
=> Revert "chore: fix pnpm ci build"

ee/tabby-ui/app/(dashboard)/activities/components/activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/user-panel.tsx, ee/tabby-ui/lib/hooks/use-all-members.tsx, ee/tabby-ui/lib/tabby/query.ts
=> feat(ui): display user name

ee/tabby-ui/app/(dashboard)/activities/components/activity.tsx, ee/tabby-ui/app/(dashboard)/reports/components/report.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/user-panel.tsx
=> fix(ui): if name is empty

crates/http-api-bindings/src/completion/mistral.rs, crates/http-api-bindings/src/completion/mod.rs, crates/http-api-bindings/src/lib.rs, crates/tabby/src/services/model/mod.rs
https://github.com/TabbyML/tabby/issues/2287
=> feat(core): Add mistral/completion for fim completion

ee/tabby-ui/app/files/components/code-editor-view.tsx
https://jam.dev/c/4a89a80e-76c4-46f5-983f-f6bb1de82de6
=> fix(ui): select line menu shouldn't affect scrolling

crates/tabby/src/routes/chat.rs, crates/tabby/src/services/chat.rs
=> Revert "feat(tabby): populate user field for chat completion logging"

crates/tabby-common/src/languages.rs
=> chore: add starcoder special tokens to fim stop words

crates/tabby/src/serve.rs, crates/tabby/src/services/embedding.rs
=> chore: fix embedding default model

ee/tabby-ui/lib/types/chat.ts
=> fix: fix error in #2342

crates/tabby-common/src/config.rs, ee/tabby-db/src/integrations.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/integration.rs
Also fixes a bug where a provider would not be synced after being updated
=> fix(db): set error to null when integration is updated

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/integration.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/repository/types.rs
cc @liangfung 
old endpoints will be removed in follow-up PR after frontend is updated
=> refactor(schema): write new provider-agnostic graphql endpoints for integrations and integrated repositories

crates/http-api-bindings/README.md
fix https://github.com/TabbyML/tabby/issues/2353
cc @TennyZhuang
=> docs: remove staled crates/http-api-bindings/README.md

.github/workflows/release.yml
fix https://github.com/TabbyML/tabby/issues/2358
=> fix: append suffix for windows exe

crates/tabby-common/src/config.rs, crates/tabby-scheduler/src/lib.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/embedding.rs
=> fix(scheduler): fix scheduler not having default embedding config

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/search.css, ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/ee7ed283-c4a3-467d-8c77-963ec8fc20a6
=> fix(ui): search page improvement

ee/tabby-ui/app/search/components/search.tsx
1. When regenerate an answer, the relavent documents should be clean
2. Adding margin between citations
=> chore(ui): search page polishment

website/docs/administration/context/index.mdx
=> docs: fix openai/embedding example for remote embedding provider

ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/repository/git/components/repository-table.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/5238ed2d-bc3c-4cf7-b0bb-c5ef8da7f992
=> feat(ui): add sync repositories job status mock

.github/workflows/docker.yml
try bump github action version to fix rocm image build stuck and fix warnings
=> chore: try bump github action version to fix rocm image build stuck

ee/tabby-ui/app/(home)/components/search.css, ee/tabby-ui/app/(home)/components/search.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/textarea-search.tsx
https://jam.dev/c/5cc0b9f2-08a9-4e00-92f0-f31a627fae02
=> chore(ui): optimize answer page

ee/tabby-ui/app/(home)/components/search.tsx, ee/tabby-ui/components/textarea-search.tsx, ee/tabby-ui/components/user-panel.tsx
* Stop button
* Hide the link of playground
=> fix(ui): stop button in searching page

ee/tabby-ui/app/(home)/components/search.tsx, ee/tabby-ui/app/(home)/page.tsx
=> fix(ui): new header for the search page

ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx
=> feat(ui): adding path to the user's code block

ee/tabby-ui/app/(home)/page.tsx
=> chore(ui): beta label

ee/tabby-ui/app/files/components/error-view.tsx, ee/tabby-ui/app/files/components/file-directory-view.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/utils.ts
1. Remove rev fallback
2. Add more detailed error scenario views
=> refactor(ui): better error page for code browser

clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/lib/utils.ts
URL example: http://localhost:8080/files/git/tabby/-/blob/main/Cargo.toml?line=2-5
=> refactor(ui):  optimize line query to support multiple lines

clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/text-file-view.tsx, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/app/playground/components/chats.tsx, ee/tabby-ui/lib/hooks/use-hash.ts, ee/tabby-ui/lib/hooks/use-router-stuff.ts, ee/tabby-ui/lib/utils.ts
URL example: http://localhost:8080/files/git/tabby/-/blob/main/Cargo.toml#L3
=> chore(ui): use hash to implement line range query

crates/tabby-inference/src/code.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/job.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/web_crawler.rs, ee/tabby-webserver/src/service/background_job/git.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/job.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/repository/git.rs, ee/tabby-webserver/src/service/repository/third_party.rs, ee/tabby-webserver/src/service/web_crawler.rs, ee/tabby-webserver/src/webserver.rs
=> feat: implement triggerJobRun graphql api

ee/tabby-schema/src/schema/mod.rs, ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-detail.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/jobs.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/utils.ts, ee/tabby-ui/app/(dashboard)/(logs)/jobs/utils/state.ts, ee/tabby-webserver/src/service/background_job/web_crawler.rs
https://jam.dev/c/cb478f54-3b20-458c-850f-38ca17817942
=> chore(webserver): expose git / github_gitlab / web jobs to frontend

ee/tabby-webserver/src/routes/ui.rs
=> feat(webserver): rewrites /files/... to /files

ee/tabby-schema/src/schema/license.rs, ee/tabby-ui/app/(dashboard)/settings/subscription/components/license-table.tsx
=> chore(ee): bump the team license seat limit to 200

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/tabs-header.tsx
https://jam.dev/c/8d402d55-e29d-49d5-9817-64c64002e758
=> chore(ui): beta badge on web provider

ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/repository/types.rs
Also removes some unused input types
=> fix(schema): fix validations for web crawler URLs and integrations

crates/tabby-scheduler/src/crawl/mod.rs, crates/tabby-scheduler/src/lib.rs, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/web/layout.tsx, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs
New error will suggest double-checking whether katana is installed when the job fails
=> fix(webserver): improve error handling and report stdout for doc indexing pipeline

ee/tabby-db/src/job_runs.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/job.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/background_job/git.rs, ee/tabby-webserver/src/service/background_job/helper/logger.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/integration.rs, ee/tabby-webserver/src/service/job.rs, ee/tabby-webserver/src/service/repository/git.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/third_party.rs, ee/tabby-webserver/src/service/web_crawler.rs, ee/tabby-webserver/src/webserver.rs
=> refactor(job): switch to sqlite as background job queue

ee/tabby-ui/app/files/components/file-directory-breadcrumb.tsx, ee/tabby-ui/app/files/components/file-directory-view.tsx, ee/tabby-ui/app/files/components/utils.ts
Screen record:
https://jam.dev/c/12dd1449-2d9f-4409-8371-82fd2ace54a6
=> fix(ui): parse directory basename properly

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/web/components/crawler-url-table.tsx
screen shot: https://jam.dev/c/d40fd22c-3da1-425f-ad75-655d740b4ae5
1. display pending job entry after triggering
2. remove the 3000ms delay after job trigger for immediate refresh.
=> fix(ui): display pending job entry after triggering

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/nav-bar.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/tabs-header.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/layout.tsx
=> feat(ui): adjust providers navbar

ee/tabby-schema/src/schema/integration.rs, ee/tabby-webserver/src/service/integration.rs
=> fix(webserver): require apiBase to be specified for self-hosted providers in backend

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/job-trigger.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/layout.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/web/components/crawler-url-table.tsx
https://jam.dev/c/10d14971-4c3f-4e85-ace8-f43d23548c19
=> feat(ui): display job info in Context Providers

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/layout.tsx
=> fix(ui): adjust providers layout style

ee/tabby-webserver/src/service/mod.rs
=> fix(webserver): support http protocol for gitlab

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-detail.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx, ee/tabby-ui/app/(dashboard)/(logs)/jobs/utils.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/91c642c8-ca58-4c18-9f26-755d2a5f669c
=> feat(ui): display started_at of jobRun

ee/tabby-ui/app/search/components/search.tsx
=> fix(ui): search box / favicon z-index issue

crates/tabby-scheduler/src/crawl/mod.rs, crates/tabby-scheduler/src/lib.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs
=> feat(scheduler): pipe Katana output to job logs

ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/utils.ts
https://jam.dev/c/a5d53a01-6ad7-484e-824d-979f63335b88
=> fix(ui):  folders with special characters should display the highlight properly

ee/tabby-ui/app/files/components/blob-mode-view.tsx, ee/tabby-ui/app/files/components/raw-file-view.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/text-file-view.tsx, ee/tabby-ui/app/files/components/tree-mode-view.tsx, ee/tabby-ui/app/files/components/types.ts, ee/tabby-ui/components/topbar-progress-indicator.tsx
Here are previews with network throttling
https://jam.dev/c/dbcd86c6-894f-4935-880e-3910f6169976
https://jam.dev/c/89d3d07b-e4f2-4ab1-a80c-b9fa484aa8dc
1. adjust the display logic to eliminate the blank phase when switching to the blob view mode.
2. adjust the code structure to make it clearer when integrating other view modes.
=> refactor(ui): ajust the structure of file blob view in code browser

clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/chat/page.tsx
I wanna simplify the query parameters of chat panel rendering
just `client` info would be enough
=> chore(vscode): simplify chat page rendering

clients/tabby-agent/package.json, clients/tabby-agent/src/lsp/GitContextProvider.ts, clients/tabby-agent/src/lsp/Server.ts, pnpm-lock.yaml
Changes:
- Added a system command based Git context provider. This should be useful for cases that tabby-agent is running outside of the VSCode or IntelliJ plugin.
=> feat(agent): add system command based git context provider as default.

clients/vscode/src/extension.ts, clients/vscode/src/git/GitProvider.ts, clients/vscode/src/lsp/GitProviderFeature.ts
Changes:
- Fixed a bug where the Tabby extension was not initializing properly when the Git extension was unable to provide the required git API. (when no git executable in system path)
=> fix(vscode): fix initialization error when git extension unavailable.

crates/tabby-scheduler/src/doc/mod.rs
=> feat: add title embedding tokens to enhance search results

ee/tabby-ui/app/files/components/code-search-result-view.tsx
=> fix(ui): correct the result counts of code searching

website/docs/administration/model.md
fix https://github.com/TabbyML/tabby/issues/2617
=> docs: mark openai completion is going to be released in 0.14

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/hooks/use-tabby-answer.ts
=> feat(ui): display relevant code in answer engine

ee/tabby-ui/components/chat/question-answer.tsx
https://jam.dev/c/a6621e2a-f56d-4373-9b9b-bbc579893063
=> fix(ui): code browser reference not clickable

ee/tabby-ui/components/textarea-search.tsx
https://jam.dev/c/a878598e-a5ad-4a49-93db-97c0f97eb7cc
=> fix(ui): adjust style of chat box in answer engine

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx
Display the selected code's **file path** in VSCode.
Clicking it will navigate the user to the corresponding position in the editor
https://jam.dev/c/98f933a1-9793-4a33-a645-22fa6e157706
=> feat(vscode): chat panel selected code path is clickable

ee/tabby-ui/app/search/components/search.tsx
1. add more bottom padding
2. correct the zIndex of scroll-to-buttom button
=> fix(ui): adjust the style of answer page

clients/intellij/build.gradle.kts, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/TextDocumentSync.kt
=> fix(intellij): resolve issue with initialization getting stuck due to an editor with null virtualFile.

ee/tabby-ui/app/files/components/file-tree-header.tsx
https://jam.dev/c/e9972f57-d6e1-4f4b-8e75-a585dd5d9a0e
=> fix(ui): hide branch select when there's no selected repo

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/components/provider-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/git.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/web/components/crawler-url.tsx, ee/tabby-ui/components/load-more-indicator.tsx, ee/tabby-ui/lib/tabby/gql.ts
1. adjust the layout of provider list page
2. add the componet `load-more-indicator`
https://jam.dev/c/6144acb4-ab69-4ff3-9e0a-dd4d25b27f97
=> fix(ui): add infinite scroll loading to the providers page

ee/tabby-ui/app/files/components/file-tree-header.tsx
https://jam.dev/c/8eb6656c-22c2-468b-8724-25779d2cd6aa
=> feat(ui): navigate to current repo's directory view on 'Files' click

crates/llama-cpp-server/src/lib.rs, crates/llama-cpp-server/src/supervisor.rs, crates/tabby-common/src/config.rs, crates/tabby/src/main.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/model/mod.rs, crates/tabby/tests/goldentests_chat.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs
close https://github.com/TabbyML/tabby/issues/2638
=> feat(config): support configure input length

clients/tabby-agent/tsup.config.ts
=> fix(agent): fix build script path regex for windows.

ee/tabby-ui/app/chat/page.tsx
change `while we get thins ready` to `while we get things ready`
=> Fix chat page welcome message

ee/tabby-ui/README.md
=> feat(ui): add contributing markdown

ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx
Display raw text if redirected to a markdown file and a lineNumber is specified.
=> fix(ui): display raw text while redirecting to markdown file

website/blog/2024-03-25-deploy-tabby-in-air-gapped-environment-with-docker/index.md
=> docs: add Nomic-Embed-Text to air gapped deployment model downloading

.changes/unreleased/Fixed and Improvements-20240725-111058.yaml, ee/tabby-webserver/src/service/background_job/third_party_integration/issues.rs
https://github.com/TabbyML/tabby/issues/2724
=> feat: Make description field optional in GitlabIssue struct

.changes/unreleased/Fixed and Improvements-20240726-202912.yaml, crates/http-api-bindings/src/chat/mod.rs, crates/http-api-bindings/src/completion/llama.rs, crates/http-api-bindings/src/embedding/llama.rs, crates/http-api-bindings/src/lib.rs, crates/llama-cpp-server/src/supervisor.rs
cc @gyxlucy 
https://github.com/TabbyML/tabby/issues/2713
=> fix: when connecting to localhost endpoint, do not use proxy settings

website/blog/2024-05-01-vulkan-support/index.md
Both the windows and linux vulkan run commands incorrect afaik.
=> Fix windows and linux run commands for vulkan

ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/files/components/code-search-bar.tsx, ee/tabby-ui/app/files/components/code-search-result.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/tabby/query.ts
1. Add help message in search bar
2. Add file search in search bar
3. Highlight the pathname in search results when the query includes the `f:` prefix 
https://jam.dev/c/6b6647f2-d47e-4032-8974-d5f654e955a0
=> feat(ui): add help message in codeSearch

ee/tabby-ui/app/files/components/code-search-bar.tsx
https://jam.dev/c/32901d4e-77fa-4495-aeab-feb7af6c8c09
=> fix(ui): correct the help message in search bar

ee/tabby-ui/app/files/components/source-code-browser.tsx
https://jam.dev/c/34adb523-eb70-4579-8fc1-c9d4fb276d77
=> feat(ui): display the `elapsedMs` value returned from endpoint

ee/tabby-ui/components/codemirror/codemirror.tsx, ee/tabby-ui/package.json, pnpm-lock.yaml
=> feat(ui): add GraphQL syntax highlighting in Code Browser

ee/tabby-ui/app/files/components/code-search-bar.tsx
https://jam.dev/c/bf5f3568-445a-476d-87c4-34ad80e7bb19
=> fix(ui): remove prefix pairs when making requests to the `repositorySearch`

ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/code-search-result.tsx, ee/tabby-ui/app/files/components/file-directory-breadcrumb.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/app/files/components/file-tree-panel.tsx, ee/tabby-ui/app/files/components/file-tree.tsx, ee/tabby-ui/app/files/components/line-menu-extension/line-menu-extension.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/tree-mode-view.tsx, ee/tabby-ui/app/files/components/types.ts, ee/tabby-ui/app/files/components/utils.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/c53452db-23a8-432a-bc32-304c6bfcbc6d
=> feat(ui): add functionality to copy permalink in code browser

ee/tabby-ui/components/textarea-search.tsx
https://jam.dev/c/987eba2d-8328-481d-b33e-5ebe1f6ae77f
=> feat(ui): add tooltip in search engine

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/OpenChatToolWindow.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatBrowser.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/widgets/ChatToolWindowFactory.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
Changes:
- Add chat tool window entrance in statusbar item menu.
- Code cleanup.
=> feat(intellij): add chat window entrance in statusbar item menu.

ee/tabby-ui/app/files/components/code-search-bar.tsx
https://jam.dev/c/9512c853-5dae-44d6-9521-9818fca599e8
=> fix(ui): allow keyboard-based deselection of options in search bar

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/completion/InlineCompletionService.kt
=> fix(intellij): fix the offset of documentChanged listener triggers inline completion.

ee/tabby-ui/app/files/components/code-search-bar.tsx
https://jam.dev/c/5c6f0a30-d5c5-4a9f-91e5-e22458ddeb30
=> fix(ui): fix bg color of search bar

ee/tabby-ui/components/chat/question-answer.tsx
=> feat(ui): enable clickable code references within the workspace

Cargo.lock, ee/tabby-schema/Cargo.toml, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/axum/extract.rs, ee/tabby-webserver/src/axum/mod.rs, ee/tabby-webserver/src/routes/mod.rs
cc @xxs-wallace @liangfung 
Demo:
https://jam.dev/c/01a6901b-b75a-4668-852c-e74d38c18c0c
=> chore(webserver): support graphql subscriptions (streaming)

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/c0295beb-1b45-4592-b852-1a2d2c6620fe
=> fix(ui): prevent flickering of the dev panel in answer engine

ee/tabby-ui/app/files/components/code-search-bar.tsx
https://jam.dev/c/2936f6c0-891a-4ff6-887f-b7b4750f6717
=> fix(ui): fix the repository search pattern

ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/file-tree-header.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx
1. ensure the search bar shortcut functions properly
2. optimize the chat sidebar interaction so that it automatically focuses when expanding from a collapsed state
https://jam.dev/c/8e39b201-5747-4b63-aa3b-bbb02baac83e
https://jam.dev/c/8f58222b-2e77-4f98-bdb7-fe8bb0176049
=> fix(ui): ensure the search bar shortcut functions properly

Cargo.lock, crates/tabby-common/assets/languages.toml, crates/tabby-index/Cargo.toml, crates/tabby-index/src/code/languages.rs, website/docs/programming-languages.md
Based at [Ruby Support](https://github.com/TabbyML/tabby/pull/597)
=> feat: add Elixir Language support

website/docs/quick-start/installation/bentoml/bentofile.yaml, website/docs/quick-start/installation/bentoml/index.md, website/docs/quick-start/installation/bentoml/service.py
Add some explanations for storage and extra packages to `bentofile.yaml`
=> docs: Update the BentoCloud doc

crates/tabby/src/serve.rs
=> fix(core): fix openapi schema missing type AnswerCodeSnippet.

crates/tabby-common/src/api/doc.rs, crates/tabby-index/src/code/languages.rs, crates/tabby/src/services/completion.rs, ee/tabby-webserver/src/service/answer.rs
https://github.com/TabbyML/tabby/commit/4008f67c5b759b114c05b721a996a5805b728d12
=> chore: run make fix after autofix-ci rework

Cargo.lock, ee/tabby-schema/Cargo.toml, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/repository/git.rs, ee/tabby-schema/src/schema/repository/types.rs, ee/tabby-schema/src/schema/setting.rs
=> chore: upgrade validator to 0.18.1

crates/tabby-common/src/config.rs
=> chore: allow completion config fields being set individually

ee/tabby-schema/src/schema/auth.rs, ee/tabby-webserver/src/axum/mod.rs, ee/tabby-webserver/src/jwt.rs, ee/tabby-webserver/src/routes/mod.rs, ee/tabby-webserver/src/service/auth.rs
cc @liangfung this PR allows graphql subscription authentication with `auth_token`.
https://jam.dev/c/ef8b29e0-4203-4da0-9018-dbaf026cfeef
cc @xxs-wallace
=> chore: allow auth with auth_token in graphql subscriptions

crates/http-api-bindings/src/completion/mistral.rs, crates/http-api-bindings/src/completion/mod.rs, crates/http-api-bindings/src/completion/openai.rs
=> fix(core): add suffix support for openai completion legacy interface

.changes/unreleased/Fixed and Improvements-20240810-221045.yaml, crates/llama-cpp-server/src/lib.rs, crates/tabby-common/src/config.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/completion.rs, crates/tabby/src/services/model/mod.rs
fix https://github.com/TabbyML/tabby/issues/2654
=> feat(llama-cpp-server): reuse local server for completion and chat

website/docs/quick-start/register-account/index.md
I was confused and wondering whether I should register an account on a central Tabby server, maybe there would be someone being confused like me.
this may help to clarify that.
=> docs: add server guide in quick start

ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/thread.rs
=> feat(webserver): add threads / threadMessages graphql api

ee/tabby-ui/app/files/components/file-tree-header.tsx
https://jam.dev/c/5b4922c2-5c77-47bf-95f3-4cfa1aecf892
=> fix(ui): adjust the offset for the revision selection dropdown

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx
https://jam.dev/c/3ed5474a-0d27-4f63-b17c-08fe64ca23f5
=> fix(ui): rendering citation for code snippet in Answer Engine

ee/tabby-ui/app/files/components/code-search-result.tsx, ee/tabby-ui/components/codemirror/codemirror.tsx
https://jam.dev/c/02f97f40-bcc1-4b84-bc1c-d618366595b7
=> fix(ui): adjust the layout height of code snippet in code search result page

crates/tabby-common/src/index/code/mod.rs
fix https://github.com/TabbyML/tabby/pull/2837/files#r1714621116
=> fix(search): change source query to const score query

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/thread/inputs.rs, ee/tabby-webserver/src/service/answer.rs
cc @liangfung - this is for future debug console to override scoring in FE.
=> chore(webserver): add CodeQueryParams override to code query input

ee/tabby-webserver/development/Caddyfile, ee/tabby-webserver/src/routes/ui.rs
=> chore(webserver): rewrite /search/* to /search

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/thread.rs
=> chore(webserver): add scores field to streaming code / docs

clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/dataStore.ts, clients/tabby-agent/src/lsp/CommandProvider.ts, clients/tabby-agent/src/lsp/ConfigProvider.ts, clients/tabby-agent/src/lsp/Server.ts, clients/tabby-agent/src/lsp/StatusProvider.ts, clients/tabby-agent/src/lsp/feature.ts, clients/tabby-agent/src/lsp/protocol.ts
- Introduce `tabby/config/*` and `tabby/status/*` methods.
- Deprecate `tabby/agent/*` methods.
=> refactor(agent): refactor config and status related lsp methods.

ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread.rs, ee/tabby-webserver/src/service/thread.rs
=> chore(webserver): add deleteThreadMessagePair mutation

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/messages-skeleton.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/package.json, ee/tabby-webserver/development/Caddyfile, pnpm-lock.yaml
https://jam.dev/c/b29b8a8c-eda9-46c8-9c40-8786c94f3b39
=> feat(ui): integrate thread api in Answer Engine

crates/tabby-common/src/api/code.rs, crates/tabby-common/src/config.rs, crates/tabby-common/src/index/code/mod.rs, crates/tabby-common/src/index/mod.rs, crates/tabby-index/src/code/index.rs, crates/tabby-index/src/code/intelligence.rs, crates/tabby-index/src/code/mod.rs, crates/tabby-index/src/code/repository.rs, crates/tabby-index/src/code/types.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/lib.rs, crates/tabby/src/serve.rs, crates/tabby/src/services/code.rs, crates/tabby/src/services/completion/completion_prompt.rs, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/repository/git.rs, ee/tabby-schema/src/schema/repository/mod.rs, ee/tabby-schema/src/schema/repository/third_party.rs, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/background_job/git.rs, ee/tabby-webserver/src/service/background_job/index_garbage_collection.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/repository/git.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/third_party.rs, ee/tabby-webserver/src/webserver.rs
make source_id an individual field
=> refactor(webserver): decouple CodeRepository from RepositoryConfig

ee/tabby-db/src/threads.rs, ee/tabby-webserver/src/service/thread.rs
=> fix(db): fix implementation of delete_thread_message_pair

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/ui/icons.tsx
https://jam.dev/c/700e7404-d654-4d1d-9521-ea1accc275c7
=> feat(ui): support thread sharing in Answer Engine

clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/chat/ChatViewProvider.ts
=> chore(vscode): support add file context

clients/vscode/package.json, clients/vscode/src/Commands.ts, clients/vscode/src/chat/ChatViewProvider.ts
=> chore(vscode): add relevant context menu in context menu

ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/axum/mod.rs, ee/tabby-webserver/src/jwt.rs, ee/tabby-webserver/src/routes/mod.rs
=> chore(auth): allow delete_thread_message_pair auth with auth_token

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/8f4d5825-1d36-4dc1-919c-dc05323669a4
=> fix(ui): update slug as soon as thread created

clients/vscode/src/CommandPalette.ts, clients/vscode/src/Commands.ts, clients/vscode/src/StatusBarItem.ts, clients/vscode/src/extension.ts, clients/vscode/src/logger.ts
=> feat(vscode): use CommandPalette to display tabby menu

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown.tsx
1. update id as soon as message created
2. if the total number of attachmentCodes exceeds five, collapse by default
=> fix(ui): update id as soon as message created

ee/tabby-ui/app/search/components/search.tsx
1. correct pagniation for messages
2. add error view for Answer Engine
=> fix(ui): correct pagination for messages in Answer Engine

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/code-references.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown.tsx
1. collapse status of attachment code view
2. font weight of citation badge
https://jam.dev/c/1615a4ac-fb41-4834-861b-aad3289ea281
=> fix(ui): correct the collapse status of attachment code view

clients/tabby-agent/src/TabbyAgent.ts, clients/vscode/package.json, clients/vscode/src/CommandPalette.ts, clients/vscode/src/Commands.ts, clients/vscode/src/Config.ts, clients/vscode/src/extension.ts
fix https://github.com/TabbyML/tabby/issues/2962
cc @liangfung
=> feat(vscode): add command to select server config from history

crates/tabby-index/src/code/index.rs, crates/tabby-index/src/code/types.rs, crates/tabby-index/src/doc/public.rs
(this issue is introduced in 0.16)
=> fix(index): fix broken code incremental indexing

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/648134b5-075e-4440-a1df-ecd8d3490665
https://jam.dev/c/6faa942c-e7ee-4827-bf50-f5ff5caf575b
=> style(search): adjust the style of header in Answer Engine

ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread.rs, ee/tabby-schema/src/schema/thread/inputs.rs, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/lib/hooks/use-router-stuff.ts, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-webserver/src/service/thread.rs
Only threads that are shared (share button clicked) will be persisted (is_ephemeral = false) in backend.
=> chore(webserver): new thread are by default ephemeral

clients/vscode/src/InlineEditCodeActionProvider.ts, clients/vscode/src/extension.ts, clients/vscode/src/lsp/Client.ts
This PR addresses issue #2966 by adding inline editing to the quick fix bar.
=> feat(vscode): adding inline edit into quick fix bar

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/components/job-trigger.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/custom-doc.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/preset-doc.tsx
https://jam.dev/c/3f28b401-6b56-49c9-a6fd-4ffce9b40957
=> fix(ui): adjust the table layout in developer docs

clients/tabby-agent/src/lsp/ChatEditProvider.ts, clients/vscode/package.json, clients/vscode/src/lsp/ChatFeature.ts, clients/vscode/src/lsp/CodeLensMiddleware.ts, pnpm-lock.yaml
https://jam.dev/c/a6e06f55-c046-4cde-922e-6138e887c04b
=> style(vscode): tune line editing insertion mode to minimize editing

clients/tabby-chat-panel/src/index.ts, ee/tabby-ui/app/chat/page.tsx
=> fix(chat-panel): add support for custom headers.

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/prompt-editor/index.tsx, ee/tabby-ui/components/prompt-editor/mention-extension.ts, ee/tabby-ui/components/prompt-editor/mention-extensions.ts, ee/tabby-ui/components/prompt-editor/mention-list.tsx, ee/tabby-ui/components/prompt-editor/styles.css, ee/tabby-ui/components/prompt-editor/suggestion.tsx, ee/tabby-ui/components/prompt-editor/types.ts, ee/tabby-ui/components/textarea-search.tsx, ee/tabby-ui/package.json, pnpm-lock.yaml
https://jam.dev/c/f605281d-60cf-47fc-af02-d2cba9127584
=> feat(ui): enable `#` prefix for referencing codebase context in Answer Engine

ee/tabby-ui/components/mention-tag.tsx, ee/tabby-ui/components/prompt-editor/mention-list.tsx, ee/tabby-ui/components/ui/icons.tsx
=> chore(ui): add Emoji and IconEmojiBook, IconEmojiGlobe components for at / sharp menu

ee/tabby-ui/components/textarea-search.tsx
https://jam.dev/c/9a2eaaa6-c21e-414f-82f5-9b41e3a1e7ea
=> chore(ui): update placeholder text and editor height for answer engine search box

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/ui/icons.tsx
https://jam.dev/c/e0510cbd-04b9-45bd-ab8f-d5c333c1cb07
=> feat(ui): display share button in Answer Engine

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/d16cfa4c-7f1e-463d-8b9d-6361004248d4
=> feat(ui): add ability to delete message pairs in Answer Engine

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/06ee1f96-927c-4348-a3be-c8f097a53ea4
=> fix(ui): ensure correct display of share button in Answer Engine

ee/tabby-ui/app/search/components/search.tsx
=> fix(ui): correct query input processing in Answer Engine

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/preset-doc.tsx, ee/tabby-ui/components/ui/table.tsx
https://jam.dev/c/7cd07732-1484-4e93-81c9-3346130a4cca
=> fix(ui): set proper min-height for Developer Docs

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/constants/regex.ts
=> fix(ui): update citation regex for proper display

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/ChatViewProvider.ts, ee/tabby-ui/app/chat/page.css, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/code-references.tsx, ee/tabby-ui/components/chat/question-answer.tsx
=> refactor(ui/chat): cleanup client usage in chat page

ee/tabby-ui/app/(dashboard)/(logs)/jobs/utils.ts
=> fix(ui): update display name for developer documentation jobs

clients/vscode/src/chat/ChatViewProvider.ts
=> fix(chat): improve theme detection in ChatViewProvider

clients/vscode/src/chat/ChatViewProvider.ts
=> refactor(vscode/chat): remove unused getTheme function and related code

crates/llama-cpp-server/build.rs
related: https://github.com/TabbyML/tabby/issues/3101
=> fix(build): disable GGML_NATIVE explicitly

ee/tabby-schema/src/schema/mod.rs
=> fix(schema): correct field path in validation error object

Makefile
#3120
- Add a dev target to avoid prompting for three separate commands.
=> chore(makefile): adding dev target for makefile

clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/ChatViewProvider.ts, clients/vscode/src/chat/chatPanel.ts, clients/vscode/src/util/KeybindingParser.ts, clients/vscode/tsconfig.json, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/prompt-form.tsx, website/docusaurus.config.js, website/src/pages/index.js
This PR is relate to #3032
What I fix in this PR
Demo:
https://github.com/user-attachments/assets/b385666b-0d5f-4c68-b077-cece0d4285be
=> feat(VSCode): trigger focus from the chat panel box to the active editor

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/custom-doc.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx
=> refactor(ui): revamp empty state styling for provider source list

ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-webserver/src/service/auth.rs
https://jam.dev/c/a7e9cf6e-344c-4e8d-89c7-cae2e2d8f8a3
=> feat(ui, server): enable admin to generate user reset password links

ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/team-nav.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/team.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/create-user-group.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/membership-view.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/types.ts, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/upsert-member-dialog.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/upsert-member-form.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/user-group-item.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/user-group-page.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/page.tsx, ee/tabby-ui/app/(dashboard)/settings/team/layout.tsx
https://jam.dev/c/e1409eb4-c766-48bb-995e-390991f567ca
https://jam.dev/c/d607165b-8d42-4560-acd6-0c783ccf94a8
=> refactor(ui): merge members page and user groups page

ee/tabby-ui/components/chat/code-references.tsx, ee/tabby-ui/components/chat/question-answer.tsx
1. add minimum height for avatars
2. adjust the style of code references on large screens
https://jam.dev/c/2026e8c2-42c3-4261-a008-ddf7ff11e1ba
=> fix(ui): adjust height for avatars in Chat

ee/tabby-schema/src/schema/email.rs, ee/tabby-ui/app/(dashboard)/settings/(integrations)/mail/components/mail-form.tsx, ee/tabby-ui/lib/utils/index.ts
=> fix(ui, schema): correct form validation for Mail Delivery settings

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/ui/codeblock.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/components/ui/switch.tsx
Add a button to enable/disable line wrapping after stream completion.
https://jam.dev/c/4860fbc8-1c85-48e6-8fe3-b3fa1919201a
=> feat(ui): enable wrap long lines in code block

ee/tabby-ui/app/(dashboard)/settings/team/groups/components/membership-view.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/user-group-page.tsx
https://jam.dev/c/07b66e37-37fb-44f3-8f1f-5921384dfa06
=> fix(ui): set max height for user group card

ee/tabby-ui/app/(dashboard)/settings/team/groups/components/membership-view.tsx
https://jam.dev/c/29c7174d-e0bc-4123-8d32-c59896edce54
https://jam.dev/c/a4b32ba6-e4da-4bc9-be91-cd347da02d5e
=> fix(ui): ensure correct scroll position for user group card

clients/tabby-agent/src/AgentConfig.ts, clients/tabby-agent/src/TabbyAgent.ts, clients/tabby-agent/src/lsp/ChatEditProvider.ts, clients/tabby-agent/src/lsp/protocol.ts, clients/vscode/src/CodeActions.ts, clients/vscode/src/Commands.ts, clients/vscode/src/code-action/InlineEdit.ts, clients/vscode/src/code-action/QuickFix.ts, clients/vscode/src/extension.ts, clients/vscode/src/inline-edit/index.ts
#3129
Demo:
https://github.com/user-attachments/assets/4df4486a-3b3a-4913-9431-88740334fba5
=> feat(VSCode): add IDE & LSP error message as LLM context.

ee/tabby-ui/app/(dashboard)/profile/components/avatar.tsx, ee/tabby-ui/app/(dashboard)/settings/team/groups/components/membership-view.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/header.tsx, ee/tabby-ui/components/user-avatar.tsx
https://jam.dev/c/df96e04c-bc1d-49e3-8714-31e2f8b4dc1f
=> feat(ui): add avatar in user group page

clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/WebviewHelper.ts
Add chat-panel api version check when `onLoaded` in vscode.
=> feat(chat-panel&vscode): add chat panel api version check.

ee/tabby-ui/components/user-avatar.tsx
=> fix(ui): display user avatar properly

ee/tabby-ui/app/(dashboard)/settings/team/groups/components/membership-view.tsx
Fixed the bug where user options could not be filtered by name or email
https://jam.dev/c/212c127a-d07f-4a6b-a2de-19ff039ba12f
=> fix(ui): correct the member select filter

clients/vscode/src/Commands.ts, clients/vscode/src/code-action/QuickFix.ts
I'm thinking of adding a range offset to select some code when there is no selection.
Current demo:
=> feat(vscode): Adding explain using tabby with LSP&IDE error

clients/tabby-agent/src/http/tabbyApiClient.ts
=> fix(agent): fix api availability check.

clients/vscode/src/Commands.ts
=> fix(vscode): retain context when chat panel is hidden

ee/tabby-schema/src/policy.rs, ee/tabby-webserver/src/service/job.rs, ee/tabby-webserver/src/service/thread.rs
=> test(webserver&schema): adding more backend test cases for cov

ee/tabby-ui/components/ui/codeblock.tsx
https://jam.dev/c/07fbf347-7791-4a2e-a549-4f63cf51d1a5
=> fix(ui): resolve line wrapping display issue in code block

ee/tabby-schema/src/schema/mod.rs, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/constants/index.ts, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/query.ts
=> fix(ui): handle expired threads

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/completion/InlineCompletionService.kt
=> fix(intellij): fix divide by zero bug when cycling through completion items.

clients/tabby-agent/src/dataStore/dataFile.ts
=> fix(agent): fix FileDataStore initialization

clients/tabby-agent/src/dataStore/dataFile.ts
=> fix(agent): fix agent datafile readjson return empty instead of null.

clients/vscode/README.md
=> docs(vscode): update installation in readme.

clients/tabby-agent/src/certsLoader.ts
=> fix(agent): Prevent VSCode extension crash when loading TLS CA certificates

clients/eclipse/feature/feature.xml, clients/eclipse/plugin/META-INF/MANIFEST.MF, clients/eclipse/plugin/plugin.xml, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/commands/inlineCompletion/Next.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/commands/inlineCompletion/Previous.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/commands/inlineCompletion/Trigger.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/IInlineCompletionService.java, clients/eclipse/plugin/src/com/tabbyml/tabby4eclipse/inlineCompletion/InlineCompletionService.java
Changes:
- Support using `Alt+\` to manually trigger inline completion.
- Support using `Alt+[` `Alt+]` to cycle through multiple completion choices.
=> feat(eclipse): support cycle multiple choices.

clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/ChatPanelViewProvider.ts, clients/vscode/src/chat/ChatSideViewProvider.ts, clients/vscode/src/chat/WebviewHelper.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx
Closes #3260 
https://jam.dev/c/7075aaee-a183-430c-985e-75b4c4b6f975
=> feat(vscode):  dynamically display the active selection context in chat side panel

ee/tabby-ui/app/(home)/components/thread-feeds.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/ui/icons.tsx
https://jam.dev/c/5f20067e-3bdc-46b7-a10c-56343a089702
=> chore(ui): tune thread-feeds component

ee/tabby-ui/app/files/components/action-bar-widget/action-bar-widget-extension.tsx, ee/tabby-ui/app/files/components/blob-header.tsx, ee/tabby-ui/app/files/components/blob-mode-view.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/code-search-bar.tsx, ee/tabby-ui/app/files/components/editor-search-extension/search-panel.tsx, ee/tabby-ui/app/files/components/editor-search-extension/search.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/text-file-view.tsx, ee/tabby-ui/components/codemirror/codemirror.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/components/ui/toggle.tsx, ee/tabby-ui/package.json, pnpm-lock.yaml
https://jam.dev/c/66fbf7cf-f0de-420b-b149-b49e67731505
=> feat(ui): support code search in code browser

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/f5c52160-3078-4882-be26-a67bbc5a3dba
=> fix(ui): resolve stale message display issue in Answer Engine

ee/tabby-ui/app/files/components/blob-header.tsx, ee/tabby-ui/app/files/components/blob-mode-view.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx, ee/tabby-ui/app/files/components/tree-mode-view.tsx
=> fix(ui): adjust blob view border style in Code Browser

ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/user_group.rs
related: https://github.com/TabbyML/tabby/issues/3328
=> fix(answer): handle cases that no choices is returned from chat model.

ee/tabby-ui/app/(home)/page.tsx
https://jam.dev/c/50f38a0b-2b77-449e-8213-c7528cde2e9b
=> fix(ui): correct homepage header style in demo mode

ee/tabby-ui/app/(home)/components/thread-feeds.tsx, ee/tabby-ui/components/mention-tag.tsx, ee/tabby-ui/components/ui/icons.tsx
=> feat(ui): display mention tags in Recent Activities

.changes/unreleased/Fixed and Improvements-20241031-155759.yaml
fix https://github.com/TabbyML/tabby/issues/3305
=> chore(llama.cpp): bump version to b3995

.changes/unreleased/Features-20241031-152952.yaml, ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/policy.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/thread.rs
related: https://github.com/TabbyML/tabby/pull/3334
=> feat(webserver): add graphql api update_thread_message

clients/vscode/src/chat/ChatSideViewProvider.ts, clients/vscode/src/chat/WebviewHelper.ts, clients/vscode/src/logger.ts
=> fix(vscode): log every n for selection sync failed warning.

ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/search.tsx
1. Hide action buttons and message input for non-owners of the thread
2. Fixed the issue of the bottom action button obstructing other visible elements
=> feat(ui): restrict thread interactions for non-owners

clients/tabby-agent/src/config/index.ts, clients/tabby-agent/src/dataStore/dataFile.ts, clients/tabby-agent/src/dataStore/index.ts, clients/tabby-agent/src/feature.ts, clients/tabby-agent/src/protocol.ts, clients/tabby-agent/src/server.ts, clients/tabby-agent/src/status.ts, clients/vscode/src/lsp/DataStoreFeature.ts
=> fix(agent&vscode): fix data store for vscode web extension 

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx, ee/tabby-ui/app/(dashboard)/system/components/worker-card.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/hooks/use-workers.ts
https://jam.dev/c/cfccd620-93ae-4f02-be4a-fa4410fbd261
=> feat(ui): add test connection button

crates/tabby-download/src/lib.rs
fix: https://github.com/TabbyML/tabby/issues/3333
=> fix(download): should check local models validate download urls

clients/vscode/src/Commands.ts, clients/vscode/src/chat/ChatPanelViewProvider.ts, clients/vscode/src/chat/ChatSideViewProvider.ts, clients/vscode/src/chat/WebviewHelper.ts, clients/vscode/src/chat/fileContext.ts, clients/vscode/src/git/GitProvider.ts
Fix the cases of cannot find the navigate target when the VSCode workspace is not at the root of the git repository containing the target file.
=> fix(vscode): fix chat panel navigate to file context.

ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/76ada706-3b3c-4556-8410-5a4c55407aac
=> fix(ui): display loading skeleton during answer generation

ee/tabby-schema/src/schema/mod.rs
Only OpenAI API Error has the type info in error message.
```rust
#[derive(Debug, thiserror::Error)]
pub enum OpenAIError {
/// Underlying error from reqwest library after an API call was made
#[error("http error: {0}")]
Reqwest(#[from] reqwest::Error),
/// OpenAI returns error object with details of API call failure
#[error("{:?}: {}", .0.r#type, .0.message)]
ApiError(ApiError),
/// Error when a response cannot be deserialized into a Rust type
#[error("failed to deserialize api response: {0}")]
JSONDeserialize(serde_json::Error),
/// Error on the client side when saving file to file system
#[error("failed to save file: {0}")]
FileSaveError(String),
/// Error on the client side when reading file from file system
#[error("failed to read file: {0}")]
FileReadError(String),
/// Error on SSE …
```
=> fix(graphQL): use better err msg for openai api error

ee/tabby-ui/app/(dashboard)/system/components/worker-card.tsx, ee/tabby-ui/components/ui/icons.tsx
=> feat(ui): display error message for unreachable model

ee/tabby-ui/components/user-panel.tsx
https://jam.dev/c/ce6d9f8e-8068-404c-82c9-e25311c86f78
=> fix(ui): enable scrolling for overflowing user panel

ee/tabby-ui/components/chat/chat-panel.tsx
1. Adjust the line number style of the code selection.
2. For active selections, add a `Current file` tag.
https://jam.dev/c/b8994f45-0426-4baf-b44f-b22d167a81e1
=> chore(ui): adjust the style of the active selection in chat side panel

clients/vscode/src/Commands.ts, clients/vscode/src/code-action/QuickFix.ts
fix quick fix cannot cover all error range
=> fix(vscode): fix QuickFix codeaction cannot correct get correct range

clients/vscode/src/Commands.ts
https://github.com/user-attachments/assets/7e5e215e-4115-44f0-823b-bad79c6a1599
=> fix(vscode): add relevant context only chat view is visible

ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/types/common.ts
https://jam.dev/c/3fd7f9d7-cbd0-452d-bd9f-b3a15da1507e
=> fix(ui): fix the error handling for thread editing

ee/tabby-db/src/threads.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/policy.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/thread.rs, ee/tabby-webserver/src/service/thread.rs
=> feat(graphQL): add deleteThread mutation

ee/tabby-ui/app/not-found.tsx, ee/tabby-ui/app/search/components/header.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/not-found-page.tsx, ee/tabby-ui/lib/tabby/gql.ts
1. Support for deleting entire thread
2. Add global 404 page for handling redirects to non-existent threads and other invalid URLs.
https://jam.dev/c/c33d9233-b301-46ce-a747-4e818803cbcb
----
=> feat(ui): add functionality to delete entire thread

ee/tabby-ui/app/(home)/components/animation-wrapper.tsx, ee/tabby-ui/app/(home)/components/thread-feeds.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/textarea-search.tsx, ee/tabby-ui/lib/hooks/use-server-info.ts, ee/tabby-ui/lib/stores/answer-engine-store.tsx, ee/tabby-ui/lib/stores/scroll-store.ts
1. Add pagination to recent activities.
2. Adjust and optimize animation performance.
3. Simplify scroll-store and add a store to track pageNo on page navigation back.
4. Fix overflow style issue in the question input.
https://jam.dev/c/0af02cba-03f4-4740-8cdb-3726c258467c
=> feat(ui): add pagination to recent activities

clients/tabby-agent/src/codeCompletion/contexts.ts, clients/tabby-agent/src/codeCompletion/index.ts, clients/tabby-agent/src/codeCompletion/solution.ts, clients/tabby-agent/src/config/default.ts, clients/vscode/src/InlineCompletionProvider.ts
Demo
https://github.com/user-attachments/assets/be2974ae-7811-4645-b272-5c68d6f29305
=> feat(agent): add context support for auto complete widget in InlineCompletion

ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-ui/lib/utils/index.ts
https://jam.dev/c/b16de9ab-7a25-4fc2-b0fe-ca42b6f88780
=> feat(ui): richer format for Issue/PR sources

clients/vscode/src/chat/WebviewHelper.ts, ee/tabby-ui/components/chat/chat.tsx
https://jam.dev/c/c9f11ed8-245c-42c3-88f3-b2533c0fc7bf
=> fix(vscode): add auto-sync for selection in untitled files

ee/tabby-ui/app/(home)/components/thread-feeds.tsx
https://jam.dev/c/76ff2f26-a035-44b5-b1da-402a45daeffb
=> fix(ui): resolve spacing issue in Recent Activities section

ee/tabby-ui/app/(dashboard)/components/sidebar.tsx, ee/tabby-ui/components/ui/sidebar.tsx, ee/tabby-ui/components/ui/tooltip.tsx
https://jam.dev/c/805d073e-ee66-4630-a3ec-a9f84853985e
=> fix(ui): correct submenu display issue in collapsed sidebar

.github/workflows/release.yml, ci/package-win.sh
Align the version to correspond with Linux
=> chore(llama.cpp): detect version and bump to b3995 for win

ee/tabby-ui/components/textarea-search.tsx
=> fix(ui): resolve model select clipping in Answer Engine

website/docs/references/cloud-deployment/modal/index.md
Commit edc181d1b1c7a8dc00c49536b34529f3cc4345ff moved the `app.py` file. This PR adjusts sources to changes.
=> docs: update `app.py` reference

website/docs/extensions/troubleshooting/index.md, website/docs/extensions/troubleshooting/intellij-choose-boot-runtime-for-the-ide.png
=> docs: update trouble shooting doc for chat panel.

.github/workflows/release.yml, crates/llama-cpp-server/build.rs
pipeline: https://github.com/zwpaper/tabby/actions/runs/11951452245/job/33315134871
before:
after:
=> ci(llama-server): update vulkan build option and use manylinux_2_28

clients/vscode/src/chat/WebviewHelper.ts
when resolving webview second time, webview does not…
- Description: fix when resolving webview second time, webview does not display.
- Recording: https://jam.dev/c/4cbbfdef-98ec-4729-98ef-f808d5c62f9f
=> fix(vscode): fix blanking when dragging chat panel to secondary sidebar (vice versa)

ee/tabby-ui/app/(home)/components/animation-wrapper.tsx, ee/tabby-ui/app/(home)/components/completion-charts.tsx, ee/tabby-ui/app/(home)/components/stats.tsx, ee/tabby-ui/app/(home)/components/thread-feeds.tsx, ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/components/quick-nav-pagination.tsx, ee/tabby-ui/lib/utils/pagination.ts
https://jam.dev/c/dd378bcb-09ad-4996-b8d0-1003a10e9ba8
=> chore(ui): update pagination for threads

website/docs/references/models-http-api/llamafile.md
depend on https://github.com/TabbyML/tabby/pull/3409
after #3409 merged, everything works:
=> docs(models-http-api): add llamafile example

crates/tabby-common/src/index/mod.rs, crates/tabby-index/src/code/index.rs, crates/tabby-index/src/code/intelligence.rs, crates/tabby-index/src/code/mod.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/indexer_tests.rs, crates/tabby-index/src/lib.rs, crates/tabby-index/src/structured_doc/mod.rs, crates/tabby-index/src/structured_doc/types.rs, crates/tabby-index/src/structured_doc/types/issue.rs, crates/tabby-index/src/structured_doc/types/pull.rs, crates/tabby-index/src/structured_doc/types/web.rs, crates/tabby-index/src/testutils.rs
Signed-off-by: Wei Zhang <kweizh@tabbyml.com>
=> fix: code index has no failed chunk count even when embed failed

ee/tabby-ui/app/search/components/search.tsx
=> chore(ui): prevent thread persistence on error

ee/tabby-webserver/src/routes/mod.rs
=> chore: enable subscriptions endpoint on graphiql

ee/tabby-db/src/users.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
part of https://github.com/TabbyML/tabby/pull/3503
=> feat(graphQL): support list users by email

clients/tabby-agent/src/codeCompletion/solution.ts
issue demo:
https://jam.dev/c/b63c3031-39fb-49cd-8643-3ac31ca73157
after fix
https://jam.dev/c/189e4ca9-ce87-4d82-acfe-795cbaed5776
=> fix(tabby-agent): Fix when auto completion shown wrong processed range

.github/workflows/release.yml
context: https://github.com/actions/checkout/issues/1809#issuecomment-2494994881
=> ci(release): migrate to manylinux_2_28

ee/tabby-db/src/users.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs
Reverts TabbyML/tabby#3529
revert if https://github.com/TabbyML/tabby/pull/3530 goes to join user_id directly
=> Revert "feat(graphQL): support list users by email"

ee/tabby-ui/components/prompt-editor/index.tsx, ee/tabby-ui/components/textarea-search.tsx, ee/tabby-ui/lib/constants/index.ts
https://jam.dev/c/04bb2f81-7981-4488-9911-521c9097734e
=> fix(ui): prevent extra newline on line break in question input box

clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/index.ts, clients/vscode/src/chat/WebviewHelper.ts, clients/vscode/src/chat/chatPanel.ts, clients/vscode/src/chat/fileContext.ts, clients/vscode/src/chat/utils.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/code.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/message-markdown/markdown-context.tsx
Test preview:
https://jam.dev/c/efdbde67-37bb-4427-8349-c7e9d4cacc0d
=> fix(chat-panel): improve the implement of lookup symbol.

ee/tabby-ui/components/message-markdown/code.tsx
https://jam.dev/c/ecf6b77b-3a59-497a-8783-c24c258de0c7
=> chore(ui): adjust the style of symbols in chat sidebar

crates/tabby-common/src/registry.rs
=> chore: show guide to registry when model not found

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/header.tsx, ee/tabby-ui/components/header.tsx, ee/tabby-ui/components/notification-box.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/components/user-panel.tsx, ee/tabby-ui/lib/tabby/gql.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/16500104-4af9-4681-aabb-3e6a0752be8c
=> feat(ui): add notifications box

ee/tabby-ui/components/notification-box.tsx
https://jam.dev/c/df358d9b-d282-4b4e-a7d9-d642f3e02746
=> chore(ui): remove navigation logic from notifications

ee/tabby-ui/components/license-banner.tsx
https://jam.dev/c/f969f243-5201-4e5f-8845-ff38c14c29a6
=> fix(ui): resolve the height issue in admin panel

crates/tabby-common/src/index/mod.rs, crates/tabby-index/src/code/index.rs, crates/tabby-index/src/indexer.rs
main branch, indexed without commit:
backfill:
=> backfill commit in source code without redo calculate

ee/tabby-ui/components/chat/question-answer.tsx
=> chore(ui): update startLine to be optional

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/header.tsx, ee/tabby-ui/app/search/components/search-context.ts, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/app/search/components/types.ts, ee/tabby-ui/app/search/components/user-message-section.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/prompt-editor/index.tsx, ee/tabby-ui/components/textarea-search/index.tsx, ee/tabby-ui/components/textarea-search/model-select.tsx, ee/tabby-ui/components/textarea-search/repo-select.tsx, ee/tabby-ui/lib/hooks/use-models.tsx, ee/tabby-ui/lib/hooks/use-repositories.ts, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/stores/chat-actions.ts, ee/tabby-ui/lib/stores/chat-store.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/c4f90134-b75a-4e06-99f5-5ecf72d062f6
https://jam.dev/c/9f8c4203-409e-466e-985e-68fbdddecdea
=> feat(ui): add repository select in Answer Engine

clients/tabby-agent/src/codeCompletion/contexts.ts, clients/tabby-agent/src/codeCompletion/index.ts, clients/tabby-agent/src/codeCompletion/postprocess/calculateReplaceRange.ts, clients/tabby-agent/src/codeCompletion/postprocess/calculateReplaceRangeByBracketStack.test.ts, clients/tabby-agent/src/codeCompletion/postprocess/calculateReplaceRangeByBracketStack.ts, clients/tabby-agent/src/codeCompletion/postprocess/calculateReplaceRangeBySemiColon.test.ts, clients/tabby-agent/src/codeCompletion/postprocess/calculateReplaceRangeBySemiColon.ts, clients/tabby-agent/src/utils/string.ts
[demo](https://jam.dev/c/9ad85b02-8c90-4c62-b8f0-c03e78728b44)
=> feat(codeCompletion): Optimize FIM request to get appropriate suffixReplaceRange

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/lib/constants/index.ts, ee/tabby-ui/lib/stores/chat-actions.ts, ee/tabby-ui/lib/stores/chat-store.ts
1. removed the sessionStorage used to pass question content & ctx
2. modify the display logic of top action buttons
https://jam.dev/c/14d18654-042b-4492-b68b-488e928dc81b
=> fix(ui):  ensure top action buttons in answer engine display timely

ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/source-code-browser.tsx
https://jam.dev/c/6557db05-adec-4e9a-84d9-539606657019
=> chore(ui): add readWorksapceRepositories to chat sidebar in code browser

ee/tabby-ui/app/auth/signin/components/ldap-signin-form.tsx
=> fix(ui): correct the placeholder of LDAP signin form

ee/tabby-webserver/src/service/background_job/db.rs
tested error log:
```log
2025-01-08T15:30:03.716642Z  WARN tabby_webserver::service::background_job: ee/tabby-webserver/src/service/background_job/mod.rs:136: Database maintainance failed: Other(Failed to run db maintenance job:
Failed to delete expired password resets: error returned from database: (code: 1) no such table: password_reset;
Failed to read active sources: error returned from database: (code: 1) no such table: repositories)
```
hold for: https://github.com/TabbyML/tabby/pull/3640
=> chore(job): db job collect errors instead of returning when met error

website/docs/references/models-http-api/deepinfra.md
=> docs: adding deepinfra model HTTP api use case doc

ee/tabby-db/src/lib.rs
Based on https://til.simonwillison.net/sqlite/enabling-wal-mode
cc @Sma1lboy
=> feat(db): enable WAL mode for SQLite database connections

clients/vim/autoload/tabby/inline_completion.vim
https://github.com/TabbyML/vim-tabby/pull/27
=> fix(vim): fix keybinding not setup on new opened buffers.

crates/ollama-api-bindings/src/model.rs, crates/tabby-git/src/grep/output.rs
for context:
unnecessary update: https://github.com/TabbyML/tabby/pull/3666
=> chore: apply auto fix to avoid other unnecessary auto update

website/docs/references/models-http-api/fireworks.md
=> docs(fireworks): adding fireworks HTTP Api example 

website/docs/references/models-http-api/openrouter.md
=> docs(openrouter): add documentation for OpenRouter API

clients/vscode/src/chat/chatPanel.ts, clients/vscode/src/chat/createClient.ts, clients/vscode/src/chat/html/main.html, clients/vscode/src/chat/webview.ts
VSCode side implementation for #3664
=> feat(vscode): support store chat session state.

website/docs/references/models-http-api/azure-openai.md
=> docs(azure-openai): add Azure OpenAI HTTP API reference documentation

ee/tabby-webserver/src/service/repository/mod.rs
https://github.com/TabbyML/tabby/issues/3720
=> fix(repository): fix garbage collection, add missing repositories in config.toml

ee/tabby-ui/app/files/components/chat-side-bar.tsx, ee/tabby-ui/app/files/components/code-editor-view.tsx, ee/tabby-ui/app/files/lib/selection-extension/index.ts, ee/tabby-ui/lib/utils/index.ts
https://jam.dev/c/4bc02a43-b0dc-4f8e-b6af-58a0f4f080b6
=> chore(ui): set active text tab as default context in Code Browser chat

ee/tabby-ui/app/(home)/components/thread-feeds.tsx
https://jam.dev/c/dd7b1107-5144-4385-b674-073c869f0882
=> fix(ui): ensure recent activities are shown only when threads exist

website/docs/administration/backup.md
fix https://github.com/TabbyML/tabby/issues/3174#event-15985022658
=> docs(admin): update backup guide to use .backup command

clients/vscode/src/chat/utils.ts
=> fix(vscode): fix pr 3738.

ee/tabby-ui/app/(dashboard)/profile/components/change-name.tsx, ee/tabby-ui/app/(dashboard)/settings/team/components/user-table.tsx
=> chore(ui): update text for users created through SSO

website/docs/references/models-http-api/anthropic-claude.md, website/docs/references/models-http-api/anthropic.md
=> docs: add documentation for Anthropic API integration

ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/form-editor/mention.tsx, ee/tabby-ui/components/chat/form-editor/types.ts, ee/tabby-ui/components/chat/form-editor/utils.tsx, ee/tabby-ui/components/chat/prompt-form.tsx, ee/tabby-ui/components/chat/repo-select.tsx
1. optimize styling
2. deduplicate mention list
https://jam.dev/c/8cd5eecc-0ade-43f2-904f-1487e6b12ac1
=> chore(ui): optimize styling of chat mention tags

.github/workflows/gh-pages.yml
test: https://github.com/zwpaper/tabby/actions/runs/13177839751/job/36781235045
=> chore(ci): upgrade deploy ci actions

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/repository/mod.rs, ee/tabby-webserver/src/service/answer/prompt_tools.rs, ee/tabby-webserver/src/service/common_prompt_tools.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/repository/prompt_tools.rs, ee/tabby-webserver/src/service/utils/mod.rs, ee/tabby-webserver/src/service/utils/prompt.rs
Provides a query readRepositoryRelatedQuestions interface, as well as a cache of the same source_id with 30mins. This interface allows you to get three questions about the current repository to help you get started with your current project. 
https://jam.dev/c/70930e68-577a-4e12-a71f-d216417b452c
=> feat(tabby-webserver): adding readingRepositoryRelatedQuestion query and related functionality

.github/workflows/release.yml, ci/package-win.sh
failed ref: https://github.com/TabbyML/tabby/actions/runs/13246934900/job/36998915026
test:
=> fix(ci): update release file name for llama.cpp

ee/tabby-webserver/src/service/repository/prompt_tools.rs
=> fix(prompt-tools): reduce maximum question length to 10 words in related_questions_with_repo_dirs function

ee/tabby-db/src/users.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/auth.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/auth.rs, ee/tabby-webserver/src/service/auth/testutils.rs
=> chore(graphQL): support list user by ids

ee/tabby-ui/app/search/components/header.tsx, ee/tabby-ui/app/search/components/search.tsx
https://jam.dev/c/07dad1a0-5d7c-449f-b975-a5e574b29dd2
=> chore(ui): `Convert to page` button to be displayed for non-shared threads

ee/tabby-ui/app/(home)/components/related-questions.tsx, ee/tabby-ui/components/ui/carousel.tsx, ee/tabby-ui/package.json, pnpm-lock.yaml
https://jam.dev/c/6f65df80-dd6b-4849-8a79-63985f42822e
=> chore(ui): implement carousel for related questions on homepage

ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/intermediate-step.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/app/search/components/reading-doc-step.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/app/search/components/types.ts, ee/tabby-ui/components/message-markdown/doc-detail-view.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/ui/icons.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts
https://jam.dev/c/20c4bba6-9a7d-4177-ad26-eed05344ff95
https://jam.dev/c/7ca03dc2-1d0f-4bd3-8129-51f471fd4d79
https://jam.dev/c/95e42659-e1e7-4ae8-8dd9-2c4bd17775ee
=> feat(ui): add step for displaying documentation search in Answer Engine

ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/types/chat.ts, ee/tabby-ui/lib/utils/index.ts
Improving the logic to trigger lookOnSymbol, provide more clickable symbols when conversing in the chat panel
https://jam.dev/c/573b76bb-79fc-4f97-974c-65c1f1d720e2
=> feat(tabby-ui): optimize the trigger logic of lookOnSymbol

ee/tabby-ui/app/search/components/header.tsx
https://jam.dev/c/a05b96e9-6dc0-4007-9650-5f5c83d8a674
=> fix(ui): resolve 'convert to page' functionality not working

ee/tabby-ui/app/chat/page.tsx
passing listSymbol into children component to enable mention symbol feature
=> chore(tabby-ui): add support for listing symbols in the editor

website/docs/references/cloud-deployment/bentoml/index.md
update link to git example for bento cloud
=> docs(bentoml):update bento cloud github link

ee/tabby-ui/components/ui/carousel.tsx
=> chore(ui): adjust carousel button icons

ee/tabby-ui/components/chat/code-references.tsx
=> fix(ui): hide code reference component when empty

ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/components/message-markdown/index.tsx
https://jam.dev/c/2916cd81-e26e-4dab-a3b3-8a489404e59c
=> fix(ui): resolve tooltip text overflow issue

ee/tabby-webserver/src/rate_limit.rs
increase limit from 60 to 120 per min
=> feat(rate_limit): increase user request limit from 60 to 120 per minute

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/analytic.rs, ee/tabby-ui/lib/language-utils/index.ts
https://github.com/TabbyML/tabby/issues/3896
=> chore(webserver): add 'PHP' to the reports' filter search list

crates/tabby-index-cli/src/commands/bench.rs, ee/tabby-db/src/pages.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/page.rs, ee/tabby-schema/src/schema/page/types.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-ui/app/pages/components/new-section-form.tsx, ee/tabby-ui/app/pages/components/page-main.tsx, ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/page.rs, ee/tabby-webserver/src/service/page/prompt_tools.rs, ee/tabby-webserver/src/service/repository/mod.rs, ee/tabby-webserver/src/service/utils/mod.rs, ee/tabby-webserver/src/service/utils/prompt.rs
=> feat(graphQL): add createPageSectionRun API to append sections

clients/vscode/package.json, clients/vscode/src/ContextVariables.ts, clients/vscode/src/chat/sidePanel.ts, clients/vscode/src/chat/webview.ts, clients/vscode/src/commands/index.ts
=> feat(vscode): add chat panel navigation menu items.

ee/tabby-ui/app/files/components/chat-side-bar.tsx
https://jam.dev/c/2672d340-74b3-4dcc-9876-702db2a592bc
=> feat(ui): support chat navigation in the Code Browser

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/ChatAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/ChatNavigationAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/OpenChatToolWindow.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/ShowChatHistory.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/ShowNewChat.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatBrowser.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatBrowserFactory.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatPanelData.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/widgets/ChatToolWindowFactory.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
=> feat(intellij): add chat panal toolbar for navigation, update chat-panel api 0.8.0.

ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/retrieval.rs, ee/tabby-webserver/src/service/thread.rs, ee/tabby-webserver/src/webserver.rs
Signed-off-by: Wei Zhang <kweizh@tabbyml.com>
=> refactor(retrieval): introduce retrieval service to retrieval code, docs

ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/codebase-tree.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/app/search/components/types.ts, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/9a9e2b66-8cc1-4d14-bb4b-bbfb1ec89acb
=> feat(ui): display codebase tree in code reading stepper

README-ja.md
=> 💬Generate LLM translations

crates/tabby-common/src/index/mod.rs, crates/tabby-git/src/commit.rs, crates/tabby-index/src/indexer.rs, crates/tabby-index/src/structured_doc/types/pull.rs, ee/tabby-webserver/src/service/background_job/index_commits.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs
=> chore: only retain pull diff less than 1M and cleanup commit diff indexing

ee/tabby-ui/app/pages/components/section-content.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/app/search/components/reading-doc-step.tsx, ee/tabby-ui/components/message-markdown/doc-detail-view.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/lib/hooks/use-thread-run.ts, ee/tabby-ui/lib/tabby/query.ts
https://jam.dev/c/d4cb1de0-d785-449c-8e7c-af465ff308df
=> chore(ui): reorganize and optimize relevant commits display

.changes/unreleased/Notice-20250307-103044.yaml, crates/tabby-crawler/src/lib.rs, docker/Dockerfile.cuda, ee/tabby-webserver/src/service/background_job/web_crawler.rs, website/docs/references/cloud-deployment/bentoml/setup-docker.sh
cc @Sma1lboy 
https://github.com/TabbyML/tabby/issues/3914#issuecomment-2705374277
=> fix(deps): update katana to v1.1.2

ee/tabby-ui/app/chat/components/history-view.tsx, ee/tabby-ui/components/chat/empty-screen.tsx
=> chore(ui): optimize display for empty chat history

ee/tabby-ui/app/chat/components/history-view.tsx, ee/tabby-ui/app/chat/page.css, ee/tabby-ui/app/chat/page.tsx
=> fix(ui): apply background color to chat side panel

ee/tabby-ui/components/chat/form-editor/utils.tsx
=> fix(ui): correct symbol display in recent activities tab

ee/tabby-db/src/pages.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/page.rs, ee/tabby-schema/src/schema/page/types.rs, ee/tabby-webserver/src/service/page.rs
Tests:
- page content
- ![CleanShot 2025-03-10 at 02 38 22@2x](https://github.com/user-attachments/assets/fbb86549-364d-4c03-a4da-21a602d77e96)
- ![CleanShot 2025-03-10 at 02 40 26@2x](https://github.com/user-attachments/assets/ba3a3efc-29e4-456d-b31c-fe57b2a80de8)
- section title
- ![CleanShot 2025-03-10 at 02 42 29@2x](https://github.com/user-attachments/assets/bed8d65f-19b2-4d7b-a3d9-29b3058984a7)
- ![CleanShot 2025-03-10 at 02 43 18@2x](https://github.com/user-attachments/assets/a70290b7-5d7c-4ff9-82ed-8f7b9c5d69c9)
- section content
- ![CleanShot 2025-03-10 at 02 43 55@2x](https://github.com/user-attachments/assets/7b2e17f1-bc0c-41f9-892d-381fe53a04a6)
- ![CleanShot 2025-03-10 at 02 44 15@2x](https://github.com/user-attachments/assets/ad4be38f-0c9f-43ab-a712-d761f2f8a695)
=> feat(page): support update page content, section title and content

ee/tabby-ui/app/pages/components/message-content-form.tsx, ee/tabby-ui/app/pages/components/new-section-form.tsx, ee/tabby-ui/app/pages/components/page-content.tsx, ee/tabby-ui/app/pages/components/page-main.tsx, ee/tabby-ui/app/pages/components/section-content.tsx, ee/tabby-ui/app/pages/components/section-title.tsx
https://jam.dev/c/9c7087b7-182a-4ba1-a8e6-7aed0d49517a
=> feat(ui): enable inline editing of pages

clients/vscode/src/extension.ts
=> fix(vscode): fix tryReadAuthenticationToken to return undefined when endpoint config is empty.

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/GenerateCommitMessage.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/events/FeaturesState.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/events/StartupActivity.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/LanguageClient.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/protocol/ProtocolData.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/protocol/server/ChatFeature.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/protocol/server/LanguageServer.kt, clients/intellij/src/main/resources/META-INF/plugin-Git4Idea.xml, clients/intellij/src/main/resources/META-INF/plugin.xml
Added an action `Generate Commit Message` in `Git` menu.  
This action is available when connecting to a Tabby server with chat model.
Preview:
=> feat(intellij): support generate commit message.

ee/tabby-ui/app/chat/components/history-view.tsx, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/skeletion.tsx, ee/tabby-ui/components/chat/thread-item.tsx
https://jam.dev/c/11206f4b-764a-4ce3-8209-1248a5f504a7
=> fix(chat): resolve message count errors and remove stale threads

ee/tabby-ui/components/chat/form-editor/mention.tsx, ee/tabby-ui/components/chat/prompt-form.tsx
https://jam.dev/c/769add9b-0d38-460a-bf57-8b4f6f4839ed
=> fix(ui): eliminate flickering when mentioning in chat panel

ee/tabby-ui/app/(home)/components/thread-feeds/all-threads.tsx, ee/tabby-ui/app/(home)/components/thread-feeds/index.tsx, ee/tabby-ui/app/(home)/components/thread-feeds/my-threads.tsx, ee/tabby-ui/lib/stores/answer-engine-store.tsx
=> chore(ui): hide empty activities

crates/tabby-index/src/structured_doc/public.rs, ee/tabby-webserver/src/service/background_job/index_commits.rs
=> fix(index): skip indexing existed commits

ee/tabby-webserver/src/service/page.rs
=> chore: return section id before attachment when append section

ee/tabby-ui/app/(home)/components/thread-feeds/index.tsx
https://jam.dev/c/682890d6-95c5-4dd1-bcab-d396b4c0c84d
=> chore(ui): prefetch my activities

ee/tabby-ui/app/(home)/components/thread-feeds/index.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/textarea-search/index.tsx, ee/tabby-ui/components/textarea-search/repo-select.tsx
During follow-up questioning, updating or selecting the repository is not allowed
https://jam.dev/c/7f834cf1-de6a-4c4d-877c-2d94e3d4517a
=> chore(ui): disable repository edits while asking follow-up questions

crates/tabby-common/src/path.rs, ee/tabby-webserver/src/path.rs, ee/tabby-webserver/src/service/background_job/helper/logger.rs, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/job.rs
- `should_rotate` covered by unit test
- test by change rotates by minutes:
=> chore: save background_job stdout to local file

clients/vscode/src/chat/webview.ts
enhance file search when no open tabs and no query 
with tabs
with tabs over limit
without tabs
=> feat(vscode): enhance file search listFileInWorkspace fallback when no open editors are found

ee/tabby-ui/app/(home)/page.tsx, ee/tabby-ui/app/pages/components/new-page-form.tsx, ee/tabby-ui/components/textarea-search/repo-select.tsx, ee/tabby-ui/lib/hooks/use-repositories.ts
https://jam.dev/c/82cd8554-c845-4d63-b585-f36c245525c0
=> chore(ui): cache the selected repository in browser

crates/tabby/src/routes/chat.rs, crates/tabby/src/serve.rs
After calling `v1/chat/completions`, statistics show the count
=> chore: log v1/chat/completion event

clients/tabby-chat-panel/src/server.ts, ee/tabby-ui/lib/utils/index.ts
=> feat(tabby-ui): adding code-review as predefined command

clients/tabby-threads/exports/create-thread-from-iframe.ts, clients/tabby-threads/package.json, clients/tabby-threads/rollup.config.js, pnpm-lock.yaml
revert #3574 as it is no longer required.
=> chore(tabby-threads): revert adding iife output build script

ee/tabby-ui/components/ui/codeblock.tsx
=> fix(tabby-ui): fix that only bash code block can be execute in chat panel

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/actions/chat/CodeReview.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatBrowser.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/chat/ChatPanelData.kt, clients/intellij/src/main/resources/META-INF/plugin.xml
=> feat(intellij): add 'code review' action for intelliJ IDEA

ee/tabby-schema/src/schema/mod.rs, ee/tabby-ui/app/chat/components/history-view.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/app/search/components/reading-doc-step.tsx, ee/tabby-ui/components/chat/chat-context.ts, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/empty-screen.tsx, ee/tabby-ui/components/chat/form-editor/utils.tsx, ee/tabby-ui/components/chat/imtermediate-step.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/chat/reading-doc-stepper.tsx, ee/tabby-ui/components/chat/reading-repo-stepper.tsx, ee/tabby-ui/components/chat/types.ts, ee/tabby-ui/components/message-markdown/doc-detail-view.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/message-markdown/markdown-context.tsx, ee/tabby-ui/lib/types/chat.ts
https://jam.dev/c/ac4d4c4f-7bc5-4096-b48c-d0d5d1fa84dd
----
=> feat(ui): add doc query in Chat Panel

Cargo.lock, Cargo.toml, crates/aim-downloader/Cargo.toml, ee/tabby-db/src/job_runs.rs, ee/tabby-schema/src/schema/job.rs, ee/tabby-webserver/Cargo.toml, ee/tabby-webserver/src/routes/mod.rs, ee/tabby-webserver/src/service/job.rs
=> refactor(background-jobs): use rest api to fetch job logs

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/page/types.rs, ee/tabby-webserver/src/service/page.rs
=> chore(page): support returning debug data when create page run

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-detail.tsx, ee/tabby-webserver/development/Caddyfile
https://jam.dev/c/0bad1b92-4bfb-463d-8d48-97d40308efbd
=> chore(ui): use rest api to fetch job logs

ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/lib/utils/chat.ts, ee/tabby-ui/lib/utils/markdown.ts, ee/tabby-ui/package.json, ee/tabby-ui/test/utils/markdown.test.ts, pnpm-lock.yaml
=> fix(markdown): handle JSON parsing errors in processCodeBlocksWithLabel

ee/tabby-ui/components/chat/form-editor/mention.tsx
=> fix(tabby-ui): fix windows cannot display filepath

website/docs/administration/usage-analytics/activity_chart.png, website/docs/administration/usage-analytics/chat_section.png, website/docs/administration/usage-analytics/code_completions_section.png, website/docs/administration/usage-analytics/index.mdx
=> docs(analytics): add usage analytics documentation

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-detail.tsx, ee/tabby-ui/components/load-more-indicator.tsx
https://jam.dev/c/8fca2618-24ef-41da-b749-111c8e1e0aa8
=> refactor(ui): implement streaming for job log loading

ee/tabby-ui/app/auth/signin/components/signin-section.tsx
=> chore(ui): optimize text on signin page

ee/tabby-ui/app/pages/components/page-main.tsx
https://jam.dev/c/f242c99a-52ba-41ac-9272-b278961c5de3
=> chore(ui): add support to stop pages creation

ee/tabby-ui/app/chat/page.tsx
https://jam.dev/c/f216e693-85a6-4206-ac7c-a7466e57cd5b
=> chore(chat): navigate to chat view after ececuting commands

ee/tabby-ui/app/(dashboard)/experiments/components/feature-list.tsx, ee/tabby-ui/app/pages/components/page-main.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/app/search/components/reading-doc-step.tsx, ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/chat/reading-doc-stepper.tsx, ee/tabby-ui/components/message-markdown/doc-detail-view.tsx, ee/tabby-ui/lib/experiment-flags.ts, ee/tabby-ui/lib/utils/attachment.ts, ee/tabby-ui/lib/utils/chat.ts
=> feat(ui): enable search pages in Answer Engine

ee/tabby-ui/app/search/components/header.tsx, ee/tabby-ui/app/search/components/search.tsx
=> chore(ui): display share button in the Answer Engine header

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/schema/mod.rs, ee/tabby-schema/src/schema/page.rs, ee/tabby-schema/src/schema/page/types.rs, ee/tabby-webserver/src/service/page.rs
1. support debug data for convert thread to page
2. return doc/code query
---
docQuery:
codeQuery:
=> chore(page): return code and doc query debug data

ee/tabby-ui/app/search/components/search.tsx, ee/tabby-ui/app/search/components/types.ts, ee/tabby-ui/lib/hooks/use-thread-run.ts
https://jam.dev/c/eaffc036-06d0-4a8d-b4c3-0087cb045513
=> chore(ui): display chat completion messages in dev mode

ee/tabby-ui/app/pages/components/section-content.tsx
https://jam.dev/c/f9494316-5fc0-43e4-84f3-c1d1270cd142
=> fix(ui): correctly render page sources

ee/tabby-ui/app/pages/components/page-main.tsx
1. correct improper redirect bug on pages
2. fix a brief full-screen skeleton flash during page generation
https://jam.dev/c/1b5ad4d1-78bf-4ea8-b171-368f25b3a018
=> fix(page): correct improper redirect bug on pages

ee/tabby-ui/app/(dashboard)/(logs)/jobs/components/job-row.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/custom-doc.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/components/preset-doc.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/git/components/repository-table.tsx
=> chore(ui): implement automatic job status polling

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/components/provider-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/lib/tabby/query.ts
=> chore(ui): optimize notification error message display

website/docs/administration/config-toml.md
=> docs(config-toml): add config.toml documentation

ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/integration.rs, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/components/provider-list.tsx, ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx, ee/tabby-ui/lib/tabby/query.ts, ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/background_job/web_crawler.rs, ee/tabby-webserver/src/service/integration.rs, ee/tabby-webserver/src/service/repository/third_party.rs
cc @liangfung for integration error message fe update
=> chore(notification): optimize error and notification messages

clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/completion/InlineCompletionService.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/CodeVisionProvider.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/inlineChat/InlineChatIntentionAction.kt, clients/intellij/src/main/kotlin/com/tabbyml/intellijtabby/lsp/LanguageClient.kt
fix issue #1053 
https://github.com/user-attachments/assets/0d68068f-f596-4a11-a21a-214a764bfd31
=> fix(intellij): use completion info on inline completion

ee/tabby-ui/app/search/components/reading-doc-step.tsx
=> fix(ui): resolve web documentation hover card display issue

crates/tabby-common/src/api/structured_doc.rs, ee/tabby-db/src/attachment.rs, ee/tabby-db/src/ingestion.rs, ee/tabby-db/src/lib.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/context.rs, ee/tabby-schema/src/schema/ingestion.rs, ee/tabby-schema/src/schema/retrieval.rs, ee/tabby-schema/src/schema/thread/types.rs, ee/tabby-webserver/src/service/context.rs, ee/tabby-webserver/src/service/ingestion.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/retrieval.rs, ee/tabby-webserver/src/webserver.rs
Thread:
Page:
cc @liangfung for FE update
=> feat(retrieval): add ingested doc attachment support for thread

ee/tabby-db/src/ingestion.rs, ee/tabby-db/src/lib.rs, ee/tabby-schema/graphql/schema.graphql, ee/tabby-schema/src/dao.rs, ee/tabby-schema/src/schema/ingestion.rs, ee/tabby-schema/src/schema/mod.rs, ee/tabby-webserver/src/service/ingestion.rs
@liangfung please help to update fe
=> feat(graphQL): add ingestion status api

clients/tabby-chat-panel/package.json, clients/tabby-chat-panel/src/client.ts, clients/tabby-chat-panel/src/server.ts, clients/tabby-chat-panel/src/types.ts, clients/vscode/package.json, clients/vscode/src/ContextVariables.ts, clients/vscode/src/chat/context.ts, clients/vscode/src/chat/sidePanel.ts, clients/vscode/src/chat/utils.ts, clients/vscode/src/chat/webview.ts, clients/vscode/src/commands/index.ts, clients/vscode/src/terminal.ts, ee/tabby-ui/app/chat/page.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/reading-code-step.tsx, ee/tabby-ui/components/chat/chat-panel.tsx, ee/tabby-ui/components/chat/chat.tsx, ee/tabby-ui/components/chat/code-references.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/chat/reading-repo-stepper.tsx, ee/tabby-ui/components/chat/types.ts, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/message-markdown/markdown-context.tsx, ee/tabby-ui/lib/types/chat.ts, ee/tabby-ui/lib/utils/chat.ts, ee/tabby-ui/lib/utils/index.ts
https://github.com/user-attachments/assets/28e42799-d0e5-451e-ba8e-759de81542d4
https://github.com/user-attachments/assets/ebfd77ff-1505-45a6-82ca-26c34d85a62b
=> feat(vscode): support explain & add selection to chat on terminal

ee/tabby-webserver/src/routes/mod.rs
=> chore(http-api): ingestion api should use registration token as auth

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx, ee/tabby-ui/app/(dashboard)/system/components/ingestion-table.tsx
https://jam.dev/c/bee2bb4b-0d35-41f5-ada2-1b253af31953
=> chore(ui): reduce the width of ingestion status

crates/llama-cpp-server/build.rs
fixed CI: https://github.com/TabbyML/tabby/actions/runs/14903312586/job/41859983704
=> chore: disable curl feature from llama.cpp

crates/tabby/src/services/health.rs
current health response for local models:
```json
{
"model": "Qwen2.5-Coder-1.5B",
"chat_model": "Qwen2.5-Coder-1.5B-Instruct",
"chat_device": "cuda",
"device": "cuda",
"cuda_devices": [
"NVIDIA GeForce RTX 4060 Ti"
],
"models": {
"completion": {
"local": {
"model_id": "Qwen2.5-Coder-1.5B",
"device": "cuda",
"cuda_devices": [
"NVIDIA GeForce RTX 4060 Ti"
]
}
},
"chat": {
"local": {
"model_id": "Qwen2.5-Coder-1.5B-Instruct",
"device": "cuda",
"cuda_devices": [
"NVIDIA GeForce RTX 4060 Ti"
]
}
},
"embedding": {
"local": {
"model_id": "Jina-Embeddings-V2-Code",
"device": "cuda",
"cuda_devices": [
"NVIDIA GeForce RTX 4060 Ti"
]
}
}
},
"arch": "x86_64",
"cpu_info": "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz",
"cpu_count": 4,
"version": {
"build_date": "2025-05-12",
"build_timestamp": …
```
=> refactor(api): refactor health api to show detail of models health

ee/tabby-ui/app/pages/components/section-content.tsx, ee/tabby-ui/app/search/components/assistant-message-section.tsx, ee/tabby-ui/app/search/components/user-message-section.tsx, ee/tabby-ui/components/chat/question-answer.tsx, ee/tabby-ui/components/message-markdown/code.tsx, ee/tabby-ui/components/message-markdown/index.tsx, ee/tabby-ui/components/message-markdown/markdown-context.tsx, ee/tabby-ui/components/ui/codeblock.tsx
https://jam.dev/c/1dd46ccb-d4ec-47d6-9a2e-0f9c68dc3e66
=> chore(ui): hide actions of codeblock when streaming

ee/tabby-ui/app/(dashboard)/reports/components/report.tsx
https://jam.dev/c/7d1eca44-7954-47b0-a62b-15709e168380
=> chore(ui): make the member filter on the report page sticky

ee/tabby-ui/app/(dashboard)/system/components/cluster.tsx, ee/tabby-ui/app/(dashboard)/system/components/worker-card.tsx, ee/tabby-ui/lib/hooks/use-health.tsx, ee/tabby-ui/lib/hooks/use-workers.ts
=> chore(ui): optimize the display of model card

ee/tabby-schema/src/schema/context.rs
=> fix: strip source id in query for page and ingested docs

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/[kind]/detail/components/provider-detail.tsx
https://jam.dev/c/81ace139-f346-4556-a161-2fdad1a7ebe6
=> chore(ui): implement polling for context provider when status is pending

ee/tabby-webserver/src/service/background_job/mod.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/error.rs, ee/tabby-webserver/src/service/repository/third_party/fetch.rs
=> chore: optimise sync repositories error message

website/docs/administration/model.md, website/docs/administration/model/index.mdx, website/docs/administration/model/model_card.png
=> docs(model): enhance model configuration documentation

ee/tabby-ui/app/(dashboard)/activities/components/activity.tsx
=> chore(ui): adjust rendering logic for activity event kind

ee/tabby-ui/app/(dashboard)/settings/(integrations)/providers/doc/page.tsx, website/docs/administration/context/index.mdx
=> docs(context): add notes for developer documentation

crates/tabby-common/src/api/structured_doc.rs, ee/tabby-webserver/src/service/background_job/third_party_integration.rs, ee/tabby-webserver/src/service/background_job/third_party_integration/pulls.rs
Diff in PR is currently not indexed in GitLab.
Test:
index-cli:
```json
{"attributes":{"author_email":"","body":"Remove header","diff":null,"kind":"pull","link":"https://gitlab.com/kweizh/public/-/merge_requests/2","merged":false,"title":"Edit README.md remove header"},"corpus":"structured_doc","id":"https://gitlab.com/kweizh/public/-/merge_requests/2","source_id":"provided_repository:1WZoYg","updated_at":"2025-05-09T17:06:11.967716Z"}
{"attributes":{"author_email":"","body":"Remove Empty","diff":null,"kind":"pull","link":"https://gitlab.com/kweizh/public/-/merge_requests/1","merged":false,"title":"Edit README.md"},"corpus":"structured_doc","id":"https://gitlab.com/kweizh/public/-/merge_requests/1","source_id":"provided_repository:1WZoYg","updated_at":"2025-05-09T17:06:12.022068Z"} …
```
=> feat(third_party_integration): add gitlab pulls indexing support

website/docs/administration/user/access_control.png, website/docs/administration/user/groups.png, website/docs/administration/user/index.mdx, website/docs/administration/user/invite_link.png, website/docs/administration/user/invite_member.png
=> docs(user): add users & groups documentation

website/docs/administration/general-settings/index.mdx, website/docs/administration/general-settings/sign-in.png
=> docs(general): add general settings documentation

README.md
Fix Archive formatting + add Pochi
=> docs(readme): fix archive and introduce Pochi

ee/tabby-webserver/src/service/answer.rs, ee/tabby-webserver/src/service/answer/testutils/mod.rs, ee/tabby-webserver/src/service/mod.rs, ee/tabby-webserver/src/service/page.rs
The debug log indicates that the answer was invoked prior to the page generation:
New Page has more details:
=> chore(page): leverage answer engine before create new page

docker/Dockerfile.cuda
=> feat(docker): Update CUDA base image to 12.8

README.md
Adds a new entry under the "What's New" section in the README for version v0.30.0.
=> docs: add v0.30.0 entry to README
